### ISSUE TITLE
Zoom level switched to highest possible when browsing backwards in doc viewer

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#108]
To reproduce the phaenomen,
1. open http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/0/gsa_390028.xml&page=1&view=structure
2. browse the structure view and click somewhere, e.g. between page 9 and 11 (http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/0/gsa_390028.xml&page=10&view=structure)
3. switch to the facsimile view ***

Not able to reproduce it right now, but it looks like this:
![issue108](https://cloud.githubusercontent.com/assets/10358005/14076647/f5f2f976-f4e3-11e5-8882-b6e71ad38213.PNG)

**Comment by thvitt** [comment]
This was probably an issue with the event handling during image loading. It should have been fixed by #15.
