### ISSUE TITLE
Replace fast-forward symbol by "go-to-end" symbol in document viewer

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#110]
What I mean is this:
![go-to-end-symbol](https://cloud.githubusercontent.com/assets/10358005/14556994/464bc3ba-02fb-11e6-8609-e43ba1eaef3e.PNG)
or this:
`>|`
instead of this: `>>`

**Comment by thvitt** [comment]
`>|` is not in the symbol font, so its the other one. If we do this, we need to replace the single › button with `.fa-right-dir` or `.fa-fast-fw` — cf. [the webfont overview](http://dev.faustedition.net/webfonts/fa-cheatsheet)

**Comment by thvitt** [comment]
Reopen with a better suggestion if the current solution is unacceptable.

**Comment by gerritbruening** [comment]
I like it!
