### ISSUE TITLE
Soften colours

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#111]
When compared to the general design, the colours in the bar diagram and the red colour in the structure view are quite intensive. Is it possible to soften them a little bit?

**Comment by sbruemmer** [comment]
colours in the bar diagram:
- black = printed version
- blue = handwritten version
- lightgreen = paralipomena (not sure)
- green = paralipomena

**Comment by thvitt** [comment]
there is also [lightblue for `verseLineVariant`](http://dev.faustedition.net/genesis_bargraph?rangeStart=8275&rangeEnd=8487 "e.g., v.8743 in 2 II H.69") (@gerritbruening, we need a label re #117 for that!), and there used to be `verseLineUncertain` (orange), but that probably won't show up again?

@gerritbruening, will there ever be `schema` and `schemaUncertain`? (Currently not implemented, this was violet in some mockups IIRC)?

**Comment by gerritbruening** [comment]
We once planned to differentiate between different kinds of paralipomena (schema, draft, etc.). But that was never encoded in the data, IIRC.

**Comment by sbruemmer** [comment]
I have implemented the colors of the bar diagram:
- printed = soft black
- handwritten version = yellow
- handwritten version (variant) = light yellow
- handwritten version (not sure) = lighter yellow
- paralipomena = warmgrey
- paralipomena (not sure) = light warmgrey

So in general i kept black for printed and the most highlighted color for the handwritten versions (blue vs, yellow). All handwritten versions now carry yellow (not blue, lightblue and orange).

**Comment by gerritbruening** [comment]
These two are identical, aren't they?
- handwritten version (variant) = light yellow
- handwritten version (not sure) = lighter yellow

@sbruemmer , could you give me an impression of how it looks like?

**Comment by sbruemmer** [comment]
> These two are identical, aren't they?
No. These are slightly different. I have faked a screenshot where i inserted the different coloured bars. All three yellow tones could be found in row "2 I H.48".

![color-bar-diagram](https://cloud.githubusercontent.com/assets/13978063/16161882/2526ddbc-34d0-11e6-858b-9878be6d4078.png)

**Comment by gerritbruening** [comment]
Yes, your colors are different (and nice, actually!), but I do not understand the conceptual differentiation:
* handwritten version = yellow
* handwritten version (variant) = light yellow
* handwritten version (not sure) = lighter yellow

i.e., the technical difference between the latter two. @thvitt , can you give me a hint?

**Comment by thvitt** [comment]
Sure (cf. [create-bargraph-info.xsl](https://github.com/faustedition/faust-gen-html/blob/master/xslt/create-bargraph-info.xsl#L91)), it depends on the verse numbers:

* `4711` → verseLine → yellow
* `4711a` → verseLineVariant → light yellow
* `4711?` → verseLineUncertain → [currently not in the data]

**Comment by gerritbruening** [comment]
Ah, interesting. I was not aware of something like `4711?`.

**Comment by gerritbruening** [comment]
@thvitt, is this closed?

**Comment by gerritbruening** [comment]
I like the general impression. But the **genetic bar diagram** now has two issues:
* (Draft) manuscript versions are prioritized by the use of the basic color.
* Black for the printed versions has a natural association with a material feature (printing ink), while the other colors have not.

**Comment by gerritbruening** [comment]
For [above mentioned](https://github.com/faustedition/faust-web/issues/111#issuecomment-229887236) remaining problem, see https://github.com/faustedition/faust-web/issues/157.
