### ISSUE TITLE
Improve navigation in the bar diagram

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#112]
- Create buttons to go to the next / previous scene.
- Create buttons to zoom in and out.
- Think about a kind of mask to exactly specify the displayed range (any small or large interval of verse numbers).

**Comment by sbruemmer** [comment]
We can create a navigational bar liek in the document viewer (e.g. [2 H](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=1&view=facsimile)).

The page navigation allows to navigate to the next / previous or first / last scene.
In the middle of the page navigation there are input field where the user can specify individual view ranges.

![bar-diagramm navigation](https://cloud.githubusercontent.com/assets/13978063/16189634/8c4bf150-36db-11e6-827d-b4b758f83a34.png)

**Comment by gerritbruening** [comment]
Thank you, I like it!
I am only not sure about “Szene” followed by “1530” because the first does not fit to the latter (verse number). Maybe just leave out “Szene”?

**Comment by thvitt** [comment]
* if the outer buttons navigate to the first/last scene, they should probably be labeled `|<` instead of `<<`?
* when using the zoom buttons or entering individual line ranges, some issues arise. Assume the user currently views verses [9000 – 10000](http://dev.faustedition.net/genesis_bargraph?rangeStart=8000&rangeEnd=10000).

    * we need a solution for the breadcrumbs. Probably sth. like `Genese › (v. 9000 – 10000)`
    * it is not quite clear what `<<` / `>>` should do.   
    
        a) Should `<<` align the starting verse number to the nearest scene boundary < 9000 and leave the upper verse limit alone, i.e. [8488 – 10000](http://dev.faustedition.net/genesis_bargraph?rangeStart=8488&rangeEnd=10000)?
        b) Should it move the upper limit by the same amount?, i.e. [8488 – 9488](http://dev.faustedition.net/genesis_bargraph?rangeStart=8488&rangeEnd=9488)?
        c) Should it move both the lower and the upper to align with the nearest smaller verse boundary, i.e. [8488 – 9573](http://dev.faustedition.net/genesis_bargraph?rangeStart=8488&rangeEnd=9573) 
        d) Should it align the right border to the end of the scene starting at the left border?
        e) Or should it just ignore borders and move by a fixed amount of verses?

    * if not (d), we probably need a reset zoom button that aligns at exactly one scene.
    * which effect should the `+` and `–` buttons have on the verse limits? enlarge/shrink the interval by adjusting both limits by a fixed or variable amount each (e.g., 50 or (_e_–_s_) / 8)?

**Comment by sbruemmer** [comment]
thvitt https://github.com/faustedition/faust-web/issues/112#issuecomment-227457149:

> if the outer buttons navigate to the first/last scene, they should probably be labeled |< instead of <<?

I do agree. Unfortunately the iconset doesn't provide an icon of this type, We have to insert an custom icon as we did for the text overlay of the facsimile.

**Comment by gerritbruening** [comment]
Right you are, @thvitt . I did not care about resulting problems.
* I would prefer d).
* Maybe we should refrain from `+` and `-`.

**Comment by sbruemmer** [comment]
Prepared in de075e9. The logic has to be done.

To activate [line 16 in  includes/header.php](https://github.com/sbruemmer/faust-web/commit/8a2d5469ca0a48d642df319dcba0f8ad24b7aa85#diff-065b9b3ff30f31c3541bda1c34141908R16) and [line 13 until 31 in genesis_bargraph.php](https://github.com/sbruemmer/faust-web/commit/8a2d5469ca0a48d642df319dcba0f8ad24b7aa85#diff-33b9faca373ffae7725d446c7ecad202R13) have to be uncomment.

**Comment by gerritbruening** [comment]
There is a consensus that < and > buttons enlarge the customised line ranges to beginning / end of the previous / next scene.
