### ISSUE TITLE
Improve text view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#113]
Mail from 18.04.2016:

> 160127-Ansichten-Lesetext-01.png
> Ja, in der rechten Navigationsspalte soll der Pfeil nach oben mit "Faust II" entfallen.
> Ja, der Link "auf einer Seite" soll ausgegraut werden.
> Ja, bitte die ersten beiden Überschriften den allgemeinen Schriftgrößen für Überschriften anpassen.
> Außerdem haben wir uns dafür entschieden, dass die Überschriften im Inhaltsverzeichnis generell fett und grau erscheinen sollen.
> 
> 160127-Ansichten-Lesetext-02.png
> Die Seiten dieses Typs sollen entfallen (nur ein Inhaltsverzeichnis).
> Zur Größe der Unterlegung: Die großflächigen Unterlegungen würden wir gern beibehalten, sonst weiße Lücken in der Unterlegung stehen, die generell für etwas anderes stehen: keine Varianten.
> 
> 160127-Ansichten-Lesetext-03.png
>     Der rechte Rand erhält bei Handschriften mit Inhaltsverzeichnis folgende Links:
>         Inhaltsverzeichnis (danach Abstand)
>         ⟨vorherige Szene⟩ (wenn vorhanden)
>         ⟨nächste Szene⟩ (wenn vorhanden)
>         auf einer Seite / nach Szenen unterteilt (davor Abstand) 
>     all diese Links werden wie in 160127-Ansichten-Lesetext-01.png gesetzt, grau halbfett linksbündig untereinander mit Icon
> 
> 160127-Ansichten-Lesetext-04.png
> Finden wir gut so, wir würden Sie bitten, dies umzusetzen.
> Bei der Farbe am linken Rand noch zwei Überlegungen:
> -        Eventuell könnte es hier in Frage kommen, zwei Farben für die Abstufung zu nutzen, siehe https://thorstenvitt.de/~tv/witcount/witcount-twocolor.html#l29 (gelb und grau)
> -        Außerdem haben wir überlegt, hier eine logarithmische oder andere nicht-lineare Skalierung zu verwenden. Grundgedanke: Unterschied zwischen zwei und drei existierenden Fassungen eines Verses soll sichtbarer sein als der Unterschied zwischen 12 und 13 Fassungen.
> 
> Kopfzeile:
> Den letzten Teil der Breadcrumbs würden wir nicht fett gestalten.
> Weiterhin haben wir mit dem Gedanken gespielt, die Schriften in der Kopfzeile insgesamt grau zu machen.
> Die Kopfzeile hat durch die funktional motivierten Ergänzungen eine ganze Reihe unterschiedlicher Schriftgrößen erhalten. Aber das lässt sich wohl nicht ohne weiteres „heilen“.

> Die Fußzeile soll im Textbereich entfallen.

**Comment by thvitt** [comment]
Navigation in the right margin will become much simpler: Cf. https://github.com/faustedition/faust-gen-html/issues/56

**Comment by sbruemmer** [comment]
160127-Ansichten-Lesetext-01.png

![160127-ansichten-lesetext-04](https://cloud.githubusercontent.com/assets/13978063/16145161/a3a00f46-3477-11e6-9623-e7840c95b8ad.png)

160127-Ansichten-Lesetext-02.png

![160127-ansichten-lesetext-01](https://cloud.githubusercontent.com/assets/13978063/16145162/a3a64910-3477-11e6-9ff1-e96788facd53.png)

160127-Ansichten-Lesetext-03.png

![160127-ansichten-lesetext-02](https://cloud.githubusercontent.com/assets/13978063/16145163/a3a67c5a-3477-11e6-899f-e138b9f1b5a8.png)

160127-Ansichten-Lesetext-04.png

![160127-ansichten-lesetext-03](https://cloud.githubusercontent.com/assets/13978063/16145164/a3ae7ea0-3477-11e6-9d03-9706fc406cbb.png)

**Comment by sbruemmer** [comment]
thvitt https://github.com/faustedition/faust-web/issues/113#issuecomment-211330999:
> Navigation in the right margin will become much simpler: Cf. faustedition/faust-gen-html#56

I'm going to wait until issue is closed, so i can do stylings on the new right column.

**Comment by sbruemmer** [comment]
gerritbruening https://github.com/faustedition/faust-web/issues/113#issue-149112241:

> >  160127-Ansichten-Lesetext-01.png
Ja, bitte die ersten beiden Überschriften den allgemeinen Schriftgrößen für Überschriften anpassen.
Außerdem haben wir uns dafür entschieden, dass die Überschriften im Inhaltsverzeichnis generell fett und grau erscheinen sollen.

> > [...]

> > 160127-Ansichten-Lesetext-04.png
Finden wir gut so, wir würden Sie bitten, dies umzusetzen.

> > [...]

> > Die Fußzeile soll im Textbereich entfallen.

I'm going to workl on these tasks.

**Comment by sbruemmer** [comment]
gerritbruening https://github.com/faustedition/faust-web/issues/113#issue-149112241:
> > Kopfzeile: [...] Weiterhin haben wir mit dem Gedanken gespielt, die Schriften in der Kopfzeile insgesamt grau zu machen.

I won't recommend. Actually the logo and the current page (breadcrumb) are displayed black. This focuses the primary items regarding user orientation.

> > Die Kopfzeile hat durch die funktional motivierten Ergänzungen eine ganze Reihe unterschiedlicher Schriftgrößen erhalten. Aber das lässt sich wohl nicht ohne weiteres „heilen“.

I won't recommend. As well due to user orientation. For example using same font-size on current page (breadcrump) and main navigation items, will affect in lower user orientation. See attachement:

![breadcrump](https://cloud.githubusercontent.com/assets/13978063/16162551/7a332abe-34d4-11e6-9366-23bc65643df2.PNG)

**Comment by sbruemmer** [comment]
See also https://github.com/faustedition/faust-gen-html/issues/61

**Comment by sbruemmer** [comment]
Will continue working on open tasks after https://github.com/faustedition/faust-gen-html/issues/56 is done.

**Comment by gerritbruening** [comment]
Hm, I must say that I like your [breadcrumb draft](https://cloud.githubusercontent.com/assets/13978063/16162551/7a332abe-34d4-11e6-9366-23bc65643df2.PNG) ... @thvitt , what do you think? Can I see an example with longer and twofold breadrumbs, e.g. http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/bb_cologny/G-30_02.xml&page=2&view=facsimile?

**Comment by gerritbruening** [comment]
Clearly preferable from my point of view.
The only thing I am not sure about is the interruption of the side bar after line 4620 (… Unglücksmann). @thvitt , what do you think?

**Comment by thvitt** [comment]
I don't like that the site logo is the most prominent item in the header, although it is the least interesting/useful.

**Comment by gerritbruening** [comment]
@ https://github.com/faustedition/faust-web/issues/113#issuecomment-227473646: We indeed once had the idea to shrink the logo when browsing to any subpage of the edition.

**Comment by sbruemmer** [comment]
Shrinking the logo will harmonize everything.

![small-logo](https://cloud.githubusercontent.com/assets/13978063/16257771/b1a18bba-385a-11e6-9e25-dd7cbb1e45cd.png)

**But** the you should think about using headlines again, to ensure the user directly understands the topic of the page. A small "Aufbewahrungsorte" (see [archive locations](http://beta.faustedition.net/archive_locations)) in the breadcrumb maybe wont be enough. But with a corresponding headline the topic is clear ([archive location detail](http://beta.faustedition.net/archive_locations_detail?id=agad_warszawa)).

![headline](https://cloud.githubusercontent.com/assets/13978063/16257834/1e69c316-385b-11e6-923f-bf68bb8b7308.png)

**Comment by gerritbruening** [comment]
I see that it would be more consistent to have headlines in archive_locations. But pages like http://beta.faustedition.net/archive_locations_detail?id=agad_warszawa seem redundant to me.
Wouldn’t it be better to remove the headline and the “Archivalien” subheadline?

**Comment by sbruemmer** [comment]
Subdivided open issues (see above references)
