### ISSUE TITLE
Two many variants before l. 354

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#114]
See stage "In einem hochgewölbten ..." before http://dev.faustedition.net/print/faust1.5#l354.

**Comment by thvitt** [comment]
A8:
```xml
                            <stage n="before_354_c" rend="firstLineIndented small">In einem
                                hochgewölbten, engen, gothiſchen Zimmer <hi rend="big letter-spaced"
                                    >Fauſt</hi><lb/>unruhig auf ſeinem Seſſel am Pulte.</stage>
```
B9:
```xml
                            <stage n="before_354_c" rend="firstLineIndented small">In einem
                                hochgewölbten, engen, gothiſchen Zimmer <hi
                                    rend="normal letter-spaced">Fauſt</hi>
                                <lb/>unruhig auf ſeinem Seſſel am Pulte.</stage>
```
Difference is probably due to different values for `hi/@rend`

**Comment by thvitt** [comment]
normalize-space(.) →
```
A: In einem hochgewölbten, engen, gothischen Zimmer Faustunruhig auf seinem Sessel am Pulte.
B: In einem hochgewölbten, engen, gothischen ZimmerFaust unruhig auf seinem Sessel am Pulte.
```

Corresponding excerpts from variants.xml, i.e. the source stage the variant collation directly works on:

A:
```xml
In einem
                                hochgewölbten, engen, gothischen Zimmer <hi rend="big letter-spaced">Faust</hi>
      <lb/>unruhig auf seinem Sessel am Pulte.
```
B:
```xml
In einem
                                hochgewölbten, engen, gothischen Zimmer<lb/>
      <hi rend="normal letter-spaced">Faust</hi> unruhig auf seinem Sessel
                                am Pulte.
```
So the problem is that the whitespace between `<lb/>` and its preceding/following sibling is lost (whitespace-only text node).

**Comment by gerritbruening** [comment]
See http://wiki.tei-c.org/index.php/XML_Whitespace#Mixed-Content_Elements

**Comment by thvitt** [comment]
There's still a problem with C.3 12: `<hi rend="normal letter-spaced">Fauſt</hi> unruhig<lb/>auf ſeinem`, so we need to generate artificial whitespace for `<lb/>`

**Comment by gerritbruening** [comment]
Yes, sure!

**Comment by thvitt** [comment]
This is closed now, the three variants are really different:
> In einem hochgewölbten, engen, gothischen Zimmer Faust unruhig auf seinem Sessel am Pulte.
> In einem hochgewölbten, engen, gothischen Zimmer, Faust unruhig auf seinem Sessel am Pulte.
> In einem hochgewölbten engen gothischen Zimmer Faust unruhig auf seinem Sessel am Pulten.

**Comment by gerritbruening** [comment]
Agree!
