### ISSUE TITLE
Visual indication of the drop-down feature in the text view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#115]
It was reported from student users that the drop-down feature to access the variants is not self-evident.

**Comment by sbruemmer** [comment]
First i suggest to set the cursor as pointer while hovering over the variants. This indicates to the user that there is an interaction. Second we can place an (+) icon that signalizes there is more information. Accordingly there should be an (-) icon to signalize the additional information can be hidden again.

![160620-ansichten-lesetext-03](https://cloud.githubusercontent.com/assets/13978063/16190530/059e36c2-36e0-11e6-92a8-ce95788552fd.png)

**Comment by gerritbruening** [comment]
Good!

**Comment by sbruemmer** [comment]
@gerritbruening: Please remove label **[question]** if this feature should be realized.
