### ISSUE TITLE
Improve tooltip in bar diagram

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#117]
Until now, only two numbers appear, e.g.
> [[8489,8505]](http://beta.faustedition.net/genesis_bargraph?rangeStart=8488&rangeEnd=9126)
depending on which verses appear on the page that is linked to from a specific range of a bar.

What we need is something like this: 
* "handschriftliche Fassung von v. 8489–8505"
* respectively, "gedruckte Fassung von ..."
* respectively, Paralipomenon zu v. ...
* plus, the witness' sigil
* plus, the page nr (because the interval changes depending on the page to which the range links to)

That way, the different colours would be explained.

**Comment by gerritbruening** [comment]
Really great!

Could "Paralipomenon von" be changed into "Paralipomenon **zu**"? This would be more appropriate.

**Comment by gerritbruening** [comment]
Thanks!
Seems that printed versions have problems when it comes to page and verses:
http://dev.faustedition.net/genesis_bargraph?rangeStart=2605&rangeEnd=2677
(all tooltips refer to "S. 1")
I presume this is due to general problems with the printed versions?

**Comment by thvitt** [comment]
I guess this is due to #101, the tooltip uses the same data.

OTOH, the printed versions currently aren't organized by page … Maybe ditch the page ref for prints.

**Comment by gerritbruening** [comment]
And is this also the reason why B.a 9 is said to have smaller verse range?

**Comment by thvitt** [comment]
Here's _B.a_'s verse metadata:
```json
{
      "print" : true,
      "intervals" : [
         {
            "type" : "verseLine",
            "page" : 1,
            "end" : 2148,
            "start" : 1
         },
         {
            "start" : 2150,
            "page" : 1,
            "end" : 4334,
            "type" : "verseLine"
         },
         {
            "type" : "verseLine",
            "end" : 4612,
            "page" : 1,
            "start" : 4343
         }
      ],
      "sigil" : "B.a",
      "source" : "faust://xml/document/print/B(a)9.xml"
   }
```
Something wrong with that except for the page mapping (which is due to the page metadata generally missing for prints)?

**Comment by gerritbruening** [comment]
1. Sorry for the alarm because of B.a! Line 2149 was erroneously omitted in B.a, this is why there are more separate intervals in this text than in the other prints.
2. The page mapping is not really missing, it's in the `pb/@n`.

**Comment by thvitt** [comment]
ad 2) for manuscripts, the label in `pb/@n` is mapped to corresponding `<page>` elements in the metadata files, and the `<page>`'s position in constitutes the “canonical” page number that is used throughout the edition. Prints don't have those `<page>` elements, but as long as we don't include their facsimiles we don't need the pages for addressing anyway, so I'd probably just postpone the issue of how we deal with those page numbers.
