### ISSUE TITLE
Enable search for verses (attr n)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#119]

**Comment by gerritbruening** [comment]
Die Suche nach einer Versnummer führt zum Vers im konstituierten Text.
Wenn man sich im Document-Viewer befindet und dort nach einem Vers sucht, führt dies ebenfalls zum konstituierten Text, nicht zur entsprechenden Stelle in diesem Zeugen.

**Comment by thvitt** [comment]
es werden nur Versnummern unterstützt, keine before_/after_-Geschichten oder so.

**Comment by gerritbruening** [comment]
Ja, gut, die `before_...` kennt außer uns ja auch niemand.

**Comment by gerritbruening** [comment]
Herrlich!
