### ISSUE TITLE
Content of rdg appears in Einblendungsapparat tooltip

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#124]
See http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.2/gsa_391406.xml&page=2&view=text#l7094

**Comment by thvitt** [comment]
?

**Comment by gerritbruening** [comment]
Ah, sorry, forgot to mention that it is the tooltip in the line *after* 7094:
"Mit vielen Schwachen ist das Wort der Welt bekannt". "der Welt" is child of app/rdg

**Comment by gerritbruening** [comment]
Part of https://github.com/faustedition/faust-gen-html/issues/4
