### ISSUE TITLE
variants lost from line 7696 on

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#126]
http://beta.faustedition.net/print/faust2.13#l7696

**Comment by thvitt** [comment]
Could you have a look at the TEI sources? http://dev.faustedition.net/print/391247-emended.xml looks like the `<delSpan>` script has eaten a whole lot of lines between ll. 7248 and 8032, that's typically an indicator of a broken spanTo relation

**Comment by gerritbruening** [comment]
I should have known before. The `delSpan/@spanTo` does actually match an `xml:id`, but one that is supplied to a `<space>` element. Illegal, right? Have introduced an `<anchor>` element.

**Comment by thvitt** [comment]
Hasn't helped. Probably need to debug text-emend.xsl against a simplified version of 391247.xml

**Comment by gerritbruening** [comment]
Hm, the lines do not get lost in my fork's apply-edits.xpl.

**Comment by thvitt** [comment]
Running the complete 391247.xml through text-emend.xsl from your fork's master branch does strip the text nodes from `#space23` up to `n="p150a_4"`, inclusive.

**Comment by gerritbruening** [comment]
Ah, I did not know that there's another `delSpan` which points to a `space` and not to an `anchor`. Fixed. Is there a way to query `delSpan`s which points to other than `anchor` elements?

**Comment by thvitt** [comment]
Watch out for WARNINGs (“YOU LOOSE TEXT!”) [in the build console log](http://dev.digital-humanities.de/ci/job/faust-gen/lastBuild/consoleFull).

**Comment by gerritbruening** [comment]
Good to have that, thanks!
No "YOU LOOSE TEXT!" found at the moment.
