### ISSUE TITLE
Integrate list of testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#129]
Current version of the excel-table: https://faustedition.uni-wuerzburg.de/wiki/index.php/Datei:Dokumente_zur_Entstehungsgeschichte.xls

For the details of the import consult the [section of the wiki page](https://faustedition.uni-wuerzburg.de/wiki/index.php/Dokumente_zur_Entstehungsgeschichte#Metadatenexport_XLS_.3E_XML).

Should appear as part of "Archiv" (ABR and SH on 20.05.2016).

@thvitt , would it help to have a simple mapping table here?

**Comment by thvitt** [comment]
Please specify the columns that should be shown in the table

**Comment by gerritbruening** [comment]
| Column in the source | Column heading in the result|
|---|---|
| D | Gräf-Nr. |

**Comment by thvitt** [comment]
The list of testimonies is there, and with #155 we have (sort of) sensible sorting for all columns. Some issues remain:

* the default sort order is that of the original Excel table. This sort order isn't represented by any of the chosen columns, though, so after the user clicked one of the table headers to sort by a specific column, there is no way back.
* Some fields have representations that cannot be matched by the current sort functions, e.g., verbal descriptions or multiple values. These fields will be sorted to the end (unless there is a partial match).
