### ISSUE TITLE
Rework genesis entry

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#130]
Page: http://dev.faustedition.net/genesis

Current status: no real overall entry, because page genesis is already two-part (Faust I, Faust II)

Proposed remedy (ABR and SH, 21.05.2016):
- integrated overall diagram for Faust I and Faust II (same syntax as current)
- link to a visualization of published versions, including the Urfaust, J.1, and C&nbsp;41 (same syntax as genesis_faust_i and genesis_faust_ii, but some scenes would have to split for genetic reasons)
- link to a future timeline (not yet existant)

**Comment by gerritbruening** [comment]
![genesis](https://cloud.githubusercontent.com/assets/10358005/16485843/4150c598-3ec1-11e6-942a-a8b05d7c8abf.jpg)

**Comment by gerritbruening** [comment]
Nach call mit TV:
* Timeline mit Daten von links nach rechts
* erste vertikale Hälfte des Bildschirms (obere oder untere): Grobgliederung wie http://dev.faustedition.net/genesis, auf der y-Achse von oben nach unten
* zweite vertikale Hälfte des Bildschirms (o./u.): Punkte für Zeugen, die für entstehungsgeschichtliche Stationen stehen, und zwar:
   * Urfaust
   * Seckendorff

**Comment by gerritbruening** [comment]
See also http://sauer-seuffert.onb.ac.at/themen

**Comment by gerritbruening** [comment]
Weitere Punkte nach https://faustedition.uni-wuerzburg.de/wiki/index.php/Feedback_zur_Beta_1#Seminar_Goethes_Faust:_Entstehung_und_Edition:
* Sollte sichtbare Einteilung in Zeiträume bieten (anders als jetziger Einstieg)
* Syntagmatische Achse soll erkennbar sein  (Urfaust / Faust. Ein Fragment / Faust I)
* Tagebucheinträge und sonstige Belege für die Beschäftigung Goethes mit Faust:  möglichst Visualisierung der unterschiedlichen Belegdichte in verschiedenen Zeiträumen, um intensive Arbeitsphasen auf einen Blick sichtbar zu machen

**Comment by gerritbruening** [comment]
> konkrete Umsetzungen:
http://www.deutschestextarchiv.de/list/timeline
http://www.sozialdemokratie-rlp.de/dokumente.html
https://www.briefedition.alfred-escher.ch/kontexte/chronologie/ansicht-jahre/
https://dp.la/timeline
http://burckhardtsource.org/browse/ (Uhr-Icon aktiviert die vertikale chronologische Ansicht)
Technisches:
http://bashooka.com/coding/javascript-timeline-libraries/ 
http://visjs.org/docs/timeline/
https://codyhouse.co/gem/vertical-timeline/
https://timeline.knightlab.com/

**Comment by sbruemmer** [comment]
Commit 769b786
