### ISSUE TITLE
Reorder rows in archive_prints

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#131]
Lines should be chronologically ordered as follows:

J.1  (Seckendorff)
S.o 7 (Göschen)
A 8
J.2 (Morgenblatt)
D.1
B 9
D.2
B.a 9
J.3-1 (Revisionsbogen…)
J.3-2 (Über Kunst und Althertum)
C.1 4
C.2α 4
C.3 4
1 H.1 (Korrekturexemplar…)
C.1 12
C.3 12

**Comment by thvitt** [comment]
Is there some metadata field we can use for ordering?

**Comment by gerritbruening** [comment]
The year given in the `<bibl>` element gives a clue but does not perfectly match the chronological order which is recorded in the `macrogenesis`.

**Comment by thvitt** [comment]
The new implementation sorts by the order in `print-labels.xml` (in the data) now, and it links this sort order to sorting by _Kurzbeschreibung_ (since that contains the prints' publication year).
