### ISSUE TITLE
Line synopsis for paralipomena, U etc.

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#135]
- [ ] discuss, specify and encode a line numbering
- [ ] Generate a line synopsis analogous to the one in the text view.

**Comment by gerritbruening** [comment]
Could you help me with a list of the paralipomenas that appear twice or more? (note that these `<milestone>` elements must not be referenced by a @ next.

**Comment by thvitt** [comment]
[multiple_paralipomena.txt](https://github.com/faustedition/faust-web/files/381427/multiple_paralipomena.txt)

**Comment by gerritbruening** [comment]
Great, thanks. Is it possible to query if all of them already have `l/@n="p...` or `milestone[@unit="refline"]/@n` numberings? (Except for P123 which does not allow for a line by line matching anyway).

**Comment by gerritbruening** [comment]
See also https://faustedition.uni-wuerzburg.de/wiki/index.php/2._November_2015#Verschiedenes_f.C3.BCr_1.0
> Variantenanzeige auch für Verse, die nicht von der Schröerschen Zählung erfasst sind (Urfaust, mehrfach überlieferte Paralipomena, Zwei Teufelchen etc.),

**Comment by gerritbruening** [comment]
Aktuell gewünschte Fälle:
* H P6 und 1 H.5 (Land Strase)
* H P97 und H P98 und  2 V H.2

**Comment by thvitt** [comment]
was war f:nx nochmal?

**Comment by thvitt** [comment]
That is online now. There are a bunch of elements with both @n and @f:nx, though ([search for f:nx in the build log](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/1265/consoleFull)), we’re ignoring the f:nx value in this case.

**Comment by gerritbruening** [comment]
Im Fall von `n="todo" f:nx="…"` würde ich `n="todo"` ignorieren.

**Comment by thvitt** [comment]
ja, das passiert jetzt auch.

**Comment by gerritbruening** [comment]
![grafik](https://user-images.githubusercontent.com/10358005/46607455-579b4700-cb01-11e8-90a3-e25447eed22e.png)

Heißt, hier stimmt die Kodierung noch nicht, oder ist der build noch nicht durch?

**Comment by thvitt** [comment]
nein, ich bin heute besonders blød.

**Comment by thvitt** [comment]
jetzt aber.

**Comment by thvitt** [comment]
Beim Zeileneinsammeln sieht das so aus. Offenbar wird der Milestone mit Sigle etc. annotiert und da kommt das dann her. Regression wohl

```xml
   <stage n="before_u_453_b"
          f:nx="before_u_453_b"
          f:sigil_t="H_P6"
          f:sigil="H P6"
          f:page-n="2"
          f:page="1"
          f:type="archivalDocument"
          f:section=""
          f:headNote="Einzelblatt. - Zu ‚Faust‘ (frühe Fassung) und Versentwürfe zu ‚Faust I‘.">Ein Kreuz <del f:revType="instant">
         <unclear cert="low">d</unclear>
      </del> am Weege, rech<add f:revType="soon">t</add>s auf dem Hügel ein altes Schloſſ, <milestone unit="refline"
                 n="p21_3"
                 f:sigil_t="H_P6"
                 f:sigil="H P6"
                 f:page-n="2"
                 f:page="1"
                 f:type="archivalDocument"
                 f:section=""
                 f:headNote="Einzelblatt. - Zu ‚Faust‘ (frühe Fassung) und Versentwürfe zu ‚Faust I‘."/>in der Ferne ein Bauerhüttgen.</stage>
```

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/commit/b0136bd112dffddcf8a67b3e82528b76454d69a3

Ist da auf phil-seite nix mehr zu tun? Dann mach ich mal zu

**Comment by gerritbruening** [comment]
Ja, Rest ist separates Issue -- großen Dank!
