### ISSUE TITLE
fixed table header

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#137]
As there are sometimes long content tables like in [Archive locations](http://beta.faustedition.net/archive_locations) a fixed table header would be a good pattern to improve user experience.

Some pure CSS examples to demonstrate this functionality: https://jsfiddle.net/dPixie/byB9d/3/ and https://codepen.io/tjvantoll/pen/JEKIu

**Comment by gerritbruening** [comment]
Yes, go ahead!

**Comment by sbruemmer** [comment]
https://codepen.io/jgx/pen/wiIGc

**Comment by sbruemmer** [comment]
@thvitt: The initiation within `/archive_prints` and `/archive_testimonies` has to be done. Please add following code to the end of the page:
```
<script type="text/javascript" src="js/jquery.min.js"></script> 
<script type="text/javascript" src="js/jquery.table.js"></script> 
<script type="text/javascript">$("table[data-sortable]").fixedtableheader();</script>
```
Please note the linked commit.
We should also discuss #139 beforehand.
