### ISSUE TITLE
Remove footer from genetic pages

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#140]
Remove footer from genetic pages [/genesis_faust_i](http://beta.faustedition.net/genesis_faust_i) and [/genesis_faust_ii](http://beta.faustedition.net/genesis_faust_ii).

As within archive the footer is removed on the secon sublevel, e.g. [/archive_locations](http://beta.faustedition.net/archive_locations)

**Comment by gerritbruening** [comment]
Yes, this is what I would think.
