### ISSUE TITLE
Harmonize usage of breadcrumb

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#144]
Please discuss the harmonization in the usage of the breadcrumb.

There are "second level" pages like [Text](http://beta.faustedition.net/print/text), [Ausgabe](http://beta.faustedition.net/intro) or [Kontakt](http://beta.faustedition.net/contact) where there is no breadcrumb and on the other hand there are some with a breadcrumb like  [Archiv](http://beta.faustedition.net/archive) or [Projekt](http://beta.faustedition.net/project).

If we do use headlines again - see https://github.com/faustedition/faust-web/issues/113#issuecomment-227664431 - i recommend to start using the breadcrumb from the "third level" pages on. "Third level" means pages that are reachable after the second click, like [Aufbewahrungsorte](http://beta.faustedition.net/archive_locations) or [Faust I](http://beta.faustedition.net/genesis_faust_i).

**Comment by gerritbruening** [comment]
Thank you for pointing me to this inconsistency.
IMHO, we should have 

1. a “Lesetext” breadcrumb on page `/text`: 
2. a “Ausgabe” breadcrumb on page `/intro`
3. a “Kontakt” breadcrumb on page `/contact` (plus, remove the headline)

**Comment by sbruemmer** [comment]
There are some other pages wihtout breadcrumb like [Bibliography](http://beta.faustedition.net/bibliography), [Imprint](http://beta.faustedition.net/imprint) and some [pages not directly accesible](http://beta.faustedition.net/geneticBarGraphInfo.php).

I will work on all available pages and add a breadcrumb if neccessary.

**Comment by gerritbruening** [comment]
* ad [Bibliography](http://beta.faustedition.net/bibliography): breadcrumb instead of heading
* [Imprint](http://beta.faustedition.net/imprint) breadcrumb **and** (?) heading

**Comment by sbruemmer** [comment]
Remove content headlines on every page (except homepage) and add corresponding breandcrumb title

**Comment by sbruemmer** [comment]
@gerritbruening: please watch https://github.com/faustedition/faust-gen-html/issues/63 as well.
