### ISSUE TITLE
Improve right colum in text view

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#145]
This issue is an extract of https://github.com/faustedition/faust-web/issues/113 with open tasks. It is **pending** due to https://github.com/faustedition/faust-gen-html/issues/56

### Lesetext 01
![160127-ansichten-lesetext-01](https://cloud.githubusercontent.com/assets/13978063/16145162/a3a64910-3477-11e6-9ff1-e96788facd53.png)

Mail from 18.04.2016:
> Ja, in der rechten Navigationsspalte soll der Pfeil nach oben mit "Faust II" entfallen.
> Ja, der Link "auf einer Seite" soll ausgegraut werden.
> Ja, bitte die ersten beiden Überschriften den allgemeinen Schriftgrößen für Überschriften anpassen.
> [...]

### Lesetext 03
![160127-ansichten-lesetext-03](https://cloud.githubusercontent.com/assets/13978063/16145164/a3ae7ea0-3477-11e6-9d03-9706fc406cbb.png)

Mail from 18.04.2016:
> Der rechte Rand erhält bei Handschriften mit Inhaltsverzeichnis folgende Links:
> Inhaltsverzeichnis (danach Abstand)
> ⟨vorherige Szene⟩ (wenn vorhanden)
> ⟨nächste Szene⟩ (wenn vorhanden)
> auf einer Seite / nach Szenen unterteilt (davor Abstand) 
> all diese Links werden wie in 160127-Ansichten-Lesetext-01.png gesetzt, grau halbfett linksbündig untereinander mit Icon

**Comment by sbruemmer** [comment]
See also the issue about navigational icons in https://github.com/faustedition/faust-web/issues/150

**Comment by thvitt** [comment]
ach, inhaltsverzeichnis fehlt noch
