### ISSUE TITLE
Page number shouldn't be underlined in the text views

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#148]
In the [text view](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/0/gsa_390028.xml&page=46&view=print&section=390028.7#l2844), the page numbers are underlined, and the line is much too long:

![Page no screenshot](https://cloud.githubusercontent.com/assets/1906208/16378970/3d85c994-3c6f-11e6-8cb6-6091c3d8f881.png)

IMO this shouldn't be underlined at all (as are the line numbers). Especially since the page numbers are _at the beginning_ of the page's content …

**Comment by sbruemmer** [comment]
OK. Further the hover (+) and (-) icon (see https://github.com/faustedition/faust-web/issues/115) is now indented to the left if there is a page number
