### ISSUE TITLE
Duplicates in overview table for paralipomena

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#156]
For example, "Disputation. / Disputation."

For an older discussion of this phaenomenon, see https://github.com/faustedition/faust-web/issues/134#issuecomment-232040896.

**Comment by thvitt** [comment]
[This text file](https://thorstenvitt.de/~tv/paralipomena-debug.txt) contains the XML fragments for each paralipomenon from which the incipit fragments are extracted.

**Comment by gerritbruening** [comment]
Thank you for the text file. Something has gone wrong here:

    <head xmlns="http://www.tei-c.org/ns/1.0"
      xmlns:f="http://www.faustedition.net/ns"
      xmlns:ge="http://www.tei-c.org/ns/geneticEditions"
      xmlns:svg="http://www.w3.org/2000/svg">Disputation.</head>Disputation.

Where is the last "Disputation." from? Seems like a transformation error to me.

**Comment by thvitt** [comment]
I believe we've got them all now.
