### ISSUE TITLE
Generate list of watermarks

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#163]
| Hauptzeichen | Gegenzeichen | Zeugen (Haupt- und Gegenzeichen) | Zeugen (nur Hauptzeichen) | Zeugen (nur Gegenzeichen) | Abbildungen |
| --- | --- | --- | --- | --- | --- |

**Comment by thvitt** [comment]
soll ich das eigentlich mal machen?

**Comment by gerritbruening** [comment]
Ja, das wäre toll!

**Comment by thvitt** [comment]
[watermarks.xlsx](https://github.com/faustedition/faust-web/files/1143348/watermarks.xlsx)

**Comment by gerritbruening** [comment]
Danke!

Ideal wäre jetzt, noch 
https://github.com/faustedition/faust-gen-html/blob/master/xslt/watermark-labels.xml
zu berücksichtigen, um Inkonsistenzen der Bezeichnung auszugleichen.
Und dann könnten wir das als html im Archiv einbinden, fragt sich nur, wo genau.

**Comment by thvitt** [comment]
ach so war das gedacht? Na sag das doch gleich …

Ich denke, wo ist erstmal wurscht, aber es scheint mir dann sinnvoll zu sein, die Metadateneinträge entsprechend querzuverlinken, odr?

**Comment by gerritbruening** [comment]
Mir war die Alternative Excel nicht eingefallen ... Und warum nicht gleich ein Feature draus machen?

**Comment by gerritbruening** [comment]
Das ist großartig, danke!

Für komische Phänomene in der Tabelle eigene Issues, richtig?

**Comment by thvitt** [comment]
ja
