### ISSUE TITLE
Consider XML or generated text when merging variants

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#164]
http://dev.faustedition.net/print/faust1.5#l988

Brackets in the Lesetext are OK, but not in other Versions except A8.

**Comment by thvitt** [comment]
In the variant apparatus, two lines are considered identical iff the whitespace-normalized text content in the source document is identical. The [ ] are generated text that isn't in the source → ignored.

Possible solutions:

* Think again about this when we have the inline apparatus in the sources
* Render stuff first before comparing – ugh! That stylesheet already is too complex …
* …

**Comment by thvitt** [comment]
Should have obsoleted itself with faustedition/faust-web#217
