### ISSUE TITLE
Document viewer broken by double slashes

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#165]
See http://dev.faustedition.net//documentViewer?faustUri=faust://xml/document/faust/0/gsa_391373.xml&page=1&view=facsimile

*change of view doesn't work (sometimes)
*breadcrumbs are missing (sometimes)

Reason is `dev.faustedition.net//` instead of `dev.faustedition.net/` (cannot reproduce where this link comes from).

**Comment by thvitt** [comment]
There is no `//documentViewer` in the sources or generated html, so this is probably from some link that gets assembled via JS?

Still, the actual function should be robust enough to handle this. @gerritbruening, when you see the broken document viewer the next time, could you please press Ctrl+Shift+J to display the browser console and copy/paste the exact error message incl. source position (on the right of the view)?
