### ISSUE TITLE
Skipping empty pages shouldn't skip to first/last page if they are empty

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#167]
Slightly irritating here:

http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/sb_berlin/Nachl_Herder_XXXII-9.xml&page=2&view=facsimile_document

**Comment by thvitt** [comment]
The nextPage() mplementation for #8 skips up to the next page with a document transcript / facsimile. If it doesn't find one, it will skip to the last page, even if that doesn't have a transcript, so it might still end up at an empty page.
