### ISSUE TITLE
Tweak link on imprint

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#171]
As planned on July 29.

**Comment by thvitt** [comment]
Erinnere mich nicht. Was ist da zu tun?

**Comment by gerritbruening** [comment]
Das war nur eine ganz kurze mündliche Andeutung: Du würdest da mal etwas umsetzen und uns dann zeigen. Muss irgendetwas mit der einheitlicheren Gestaltung der Kopfzeile zu tun gehabt haben.

**Comment by thvitt** [comment]
Kann höchstens angleichung der größe gewesen sein; die anderen Sachen hatte ich im Zug ausprobiert, sehen aber doof aus.

![Impressum nicht `<small>`](https://cloud.githubusercontent.com/assets/1906208/17890842/a98754dc-6938-11e6-9643-64775ef61246.png)

**Comment by gerritbruening** [comment]
Angleichung der Größe, das kann sein.

**Comment by thvitt** [comment]
überholt
