### ISSUE TITLE
Odd URL for Text / Trüber Tag. Feld

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#173]
http://dev.faustedition.net/print/faust1.26#d5311e23008

**Comment by thvitt** [comment]
When trying to map `<div>`s to scenes (from `scenes.xml`), add-metadata.xsl generates XML IDs for the divs. They usually follow the scheme `scene`_id_, with _id_ being the scene ID from scenes.xml, but if no mapping has been found an opaque ID is auto-generated. 

The solution is the same as for faustedition/faust-gen-html#66: We need to modify `scenes.xml` to account for all corner cases of identifyable scenes/acts, and link divs to scenes using matching `n` attributes.
