### ISSUE TITLE
Wrong ToC heading for "Nacht, offen Feld"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#174]
http://dev.faustedition.net/print/faust1

See the second last heading "Trüber Tag. Feld" that should be "Nacht, offen Feld" (according to https://github.com/faustedition/faust-web/blob/c384f8968978b26d093df73f75beadab9801946e/data/scene_line_mapping.js#L161)

**Comment by thvitt** [comment]
Tracked by faustedition/faust-gen-html#66
