### ISSUE TITLE
C&P quotation reference

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#178]
Add a quotation reference for each page that is copied to the clipboard when clicked.

**Comment by thvitt** [comment]
Für jede Seite der Edition soll es möglich sein, eine Zitierempfehlung entsprechend der aktuellen Ansicht zu erzeugen, die die Benutzer einfach per Copy&Paste übernehmen können. Die Zitierempfehlung soll enthalten:
* Allgemeine Angaben zur Edition (statisch)
* Sigle des aktuellen Dokuments
* Seitenzahl
* Ansicht
* URL (oder irgendwann mal PID?)

(Den genauen Text müsste bitte @gerritbruening nochmal liefern, steht nicht im [Protokoll der entsprechenden Sitzung](https://faustedition.uni-wuerzburg.de/wiki/index.php/11._Dezember_2015#Zitierweise))

Zum Ort: Es wurde beschlossen, die Seitenzahl nochmal in Klammern hinter die Sigle im Breadcrumb zu schreiben; die Zitierempfehlung soll aufklappen, wenn man mit der Maus über den Breadcrumbbereich hovert.

**Comment by gerritbruening** [comment]
> steht nicht im Protokoll der entsprechenden Sitzung)

Die Zitierempfehlung wurde später unter dem Betreff "Info-Mailing" per Mailaustausch festgelegt. Darauf beruht https://github.com/faustedition/faust-web/blob/826a0ee770cbae9899ddacab1b2200d3d25c274b/intro.php#L244.

Ändern würde ich daran "Jannidis. Unter" in "Jannidis unter". Punkt und Großschreibung scheint mir ein Irrläufer zu sein.

> Seitenzahl nochmal in Klammern hinter die Sigle im Breadcrumb

Erinnere mich. Würde ich gern mal sehen. Wir haben halt schon so viel in der Kopfzeile...

**Comment by sbruemmer** [comment]
Bitte noch eine Zitierempfehlung für **Lesetext** und **Inhalte** (z.B. [Handschriften](http://beta.faustedition.net/archive_manuscripts) oder [Transkriptionsprinzipien](http://beta.faustedition.net/transcription_guidelines#dok_Transkr_Hss)) vorgeben.

**Comment by gerritbruening** [comment]
Zitationsempfehlung für den **Lesetext**:
Historisch-kritische Faustedition. Herausgegeben von Anne Bohnenkamp, Silke Henke und Fotis Jannidis. Unter Mitarbeit von Gerrit Brüning, Katrin Henzel, Christoph Leijser, Gregor Middell, Dietmar Pravida, Thorsten Vitt und Moritz Wissenbach. Version 1. Frankfurt am Main / Weimar / Würzburg 2016, Lesetext, Faust I, Vers ###, URL: {URL}, abgerufen am {Abrufdatum}.

... für **Inhaltsseiten**:
Historisch-kritische Faustedition. Herausgegeben von Anne Bohnenkamp, Silke Henke und Fotis Jannidis. Unter Mitarbeit von Gerrit Brüning, Katrin Henzel, Christoph Leijser, Gregor Middell, Dietmar Pravida, Thorsten Vitt und Moritz Wissenbach. Version 1. Frankfurt am Main / Weimar / Würzburg 2016, {Seitentitel wie im Breadcrumb}, URL: {URL}, abgerufen am {Abrufdatum}.

**Comment by gerritbruening** [comment]
Evtl. Blatt mit Eselsohr.

**Comment by sbruemmer** [comment]
Als Icon evtl. auch Kette oder Anführungszeichen

**Comment by sbruemmer** [comment]
Vorschläge: Darstellung als Dropdown, Overlay und Sprungmarke zum Seitenende

**Comment by gerritbruening** [comment]
> Sprungmarke zum [Seitenende](https://github.com/faustedition/faust-web/issues/178#issuecomment-286070630)

Denken Sie sich das so, dass am Seitenende dann die Zitierempfehlung stünde? Im Arbeitsbereich ist allerdings die Fußzeile das Seitenende, darunter gibt es im Moment nichts.

**Comment by thvitt** [comment]
ggf. ist es auch sinnvoll, zur Unterstützung von Tools die Zitierempfehlung zusätzlich mascihnenlesbar abzulegen, z.B. als [COinS](https://web.archive.org/web/20170424223448/http://www.ocoins.info/) oder DC-Header oder so.

**Comment by sbruemmer** [comment]
I have added a quotation reference including a copy-button within the new overlay functionality.

Unlike stated in the "[Zitationsempfehlung](https://github.com/faustedition/faust-web/issues/178#issuecomment-243760248)" the quotation reference only shows the breadcrumb titles.
For example "Text > Faust I > Nacht" and not "Lesetext > Faust I > Vers 354". I guess this is more self explanatory and was realized without create impact on the code.

@thvitt : Regarding processable meta references, i did reassing this ticket.

**Comment by thvitt** [comment]
ja, das Issue ist ja auch noch offen

**Comment by thvitt** [comment]
@gerritbruening 

1. Für den __Text__: Der Vers kann ja natürgemäß in der Zitationsempfehlung idR nicht angezeigt werden. Bleibt die Frage, ob (a) der Szenentitel angezeigt werden soll (bis auf die Dateiebene zerlegt eben) und (b) ob die Breadcrumbs reinsollen, also _Text / Der Tragödie zweiter Teil / Fünfter Akt
Offene Gegend_ oder nur _Offene Gegend_.

2. Für __Inhaltsseiten__: Breadcrumbs oder nur Seitentitel? Also _Ausgabe / Transkriptionsprinzipien_ oder nur _Transkriptionsprinzipien_?

**Comment by gerritbruening** [comment]
Ad 1 würde ich sagen, es sollte vor allem "Faust. Eine Tragödie. Konstituierter Text" rein, Szene finde ich unüblich; Zitation nach Vers sollte angeregt werden durch "Vers(e) ...", was der Nutzer dann halt anpassen soll, je nachdem welche Verse sie oder er im Auge hat.
Ad 2: Fände einfache Titel ohne Breadcrumbs besser, da einfacher.

**Comment by gerritbruening** [comment]
Text: Bearbeiter in die Zitierempfehlung (#178) aufnehmen.
