### ISSUE TITLE
Misbehavior of Firefox 42.0 under Windows 10: Unresponsive Script Warning

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#18]
![warning](https://cloud.githubusercontent.com/assets/10358005/10965983/c8fb7690-83b0-11e5-8c36-483bd05ac7a8.PNG)

This warning regularly appears when
- when sorting on page http://beta.faustedition.net/archives.php?view=manuscript-concordance
- when accessing larger witnesses such as http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2.3/gsa_391473.xml&page=1&view=structure

**Comment by thvitt** [comment]
Could you please try to reproduce this problem using a new / empty firefox profile on that machine? I do not have Windows 10 at hand, and the end of the URL with the non-responsiveness error suggests its none of the Faust scripts but rather part of some Firefox extension.

See the [Firefox KB](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager): Quit Firefox, start firefox with `firefox -P` to launch profile manager, create a new profile, try to reproduce. To go back to your old profile, again quit firefox, start it with `firefox -P` and select the old profile.

**Comment by gerritbruening** [comment]
Yes, this works! The error does not appear again in the new profile.

**Comment by thvitt** [comment]
Relieving. Then this is not a bug in faust-web.

**Comment by gerritbruening** [comment]
Kommt offenbar öfters vor, z.B. DP klagt darüber. Auch Frau Rapp scheint betroffen gewesen zu sein. Kann man da gar nichts tun?

**Comment by thvitt** [comment]
Nicht mit einer so unspezifischen Fehlermeldung.

Die Meldung exakt so wie sie bei dir steht weist auf eine Firefox-Extension hin, aber auch das Dialogfenster bietet nicht genügend Informationen. Da ich selbst das Problem noch nie bei der Faustedition beobachten konnte (und Firefox ist mein Hauptbrowser) bleibt mir nur, betroffenen Anwendern zu raten, ein neues Profil zu versuchen (s.o.), oder aber mehr Informationen beizubringen, die auf eine konkrete Stelle in den zahlreichen Skripten Faustedition verweisen. Dazu bräuchte es:

1. eine präzise Klick-by-klick-Beschreibung, die mich das Problem reproduzieren lässt. Falls es sich bei mir reproduzieren lässt.
2. z.B. einen Stack Trace & Logausschnitt (über die _Skript Debuggen_-Option aus dem o.g. Dialog), der auf eine konkrete Stelle in den zahlreichen Skripten der Faustedition verweist.

Es gibt sonst einfach keinen Ansatz um das Problem zu analysieren

**Comment by gerritbruening** [comment]
OK, ich habe DP bescheidgegegeben! Vielleicht liefert er etwas, und dann können wir evtl. weitersehen.
