### ISSUE TITLE
Unify and style tooltips

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#182]
Im Augenblick gibt es zwei Sorten Tooltips:
1. gewöhnliche Browsertooltips für das Title-Attribut
2. HTML-Tooltips, die über [Faust.tooltip](https://github.com/faustedition/faust-web/blob/master/js/faust_common.js#L774) erzeugt werden.

(1) verwenden naturgemäß den Browserstil, (2) verwenden einen Stil, der nicht zum Gesamtdesign passt. 

(1) kommt u.a. vor:
- Im [Einblendungsapparat](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/paralipomena/gsa_390882.xml&page=1&view=text#x), und auch im Variantenapparat (Lesetext, Print, …) zur Erläuterung der editorischen Zeichen wie ⟨erg⟩, {{…}} etc. (HTML wäre eine Verbesserung)
- Siglensystem für _Weitere Siglen_ in der [Handschriftenübersicht](http://dev.faustedition.net/archive_manuscripts)

(2) kommt u.a. vor:
- im Variantenapparat für die Einblendung _n Varianten in k Zeugen_
- im diplomatischen Transkript und Manuscript-Overlay für die Angabe von Schreiber und Material (HTML nötig)

Schön wäre eine Vereinheitlichung, die zum Design passt (und möglichst ohne allzuviel Ummzugsaufwand realisierbar ist …). Wichtig wäre, dass:

a) es ineinander geschachteltes gibt (z.B. editorische Markierungen im Variantenapparat – siehe [die eckigen Klammern in Vers 8719 hier](http://dev.faustedition.net/print/C%281%294_IIIB24#l8719), da sollte dann wohl beim Hovern außerhalb der eckigen Klammern »4 Varianten in 11 Textzeugen« und innerhalb »editorisch ergänzt« stehen
b) es teils anderes JavaScript gibt, das mouseover benutzt, z.B. das gleichzeitige Highlighting der diversen Einblendungen (⟨⟩), [ein schönes Beispiel ist hier](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/paralipomena/gsa_390882.xml&page=1&view=text#x), das muss natürlich weiterhin funktionieren.

**Comment by sbruemmer** [comment]
We can use a pure CSS solution like https://github.com/kazzkiq/balloon.css

**Comment by thvitt** [comment]
E.g., in the tooltip for the top right _{aus N 18}_ in [H P96](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/paralipomena/gsa_390050.xml&page=1&view=facsimile_document), there are four different bits of information that need to be presented there (hand, material, script, and _Rasur_ as mode of deletion). We'll probably need some kind of styling (as now) and line breaks in there.

(BTW these tooltips are [generated from information in the SVG](https://github.com/faustedition/faust-web/blob/master/js/faust_viewer.js#L976) when the SVG is loaded)

**Comment by sbruemmer** [comment]
There are several ways to init tooltips.
1) generally like in [genesis.php#L19](https://github.com/sbruemmer/faust-web/blob/master/genesis.php#L19) or [archive_manuscripts.php#L17](https://github.com/sbruemmer/faust-web/blob/master/archive_manuscripts.php#L17)
2) only for certain elements like in [faust_print_interaction.js#L134](https://github.com/sbruemmer/faust-web/blob/master/js/faust_print_interaction.js#L134) or [faust_viewer.js#L197](https://github.com/sbruemmer/faust-web/blob/master/js/faust_viewer.js#L197)

Thus, tooltips must be initiated manually and some may be missing.

Maybe in future releases we can use a [jquery plugin](http://iamceege.github.io/tooltipster/) and generally [enabling tooltips](http://iamceege.github.io/tooltipster/#getting-started) via classname. Also custom (html) content used in [transscript tooltips](https://github.com/faustedition/faust-web/blob/master/js/faust_viewer.js#L976) can be passed as [option](http://iamceege.github.io/tooltipster/#options).

@thvitt can open a new issue on that.
