### ISSUE TITLE
Double klick on image in structure view broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#183]
In beta, a double click links on the facsimile view.

**Comment by thvitt** [comment]
Still does this in the dev version for me.

Please provide more details (URL and target page number of a page that shows the problem, ideally copy-paste a stack trace from the browser log (ctrl+shift+j) after the failed attempt)

**Comment by gerritbruening** [comment]
Hm, cannot reproduce this now, either. Will reopen the issue when I see it again. Sorry for the alarm.
