### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#186]
> Absatz zum Beta-Release überarbeiten / Ergänzen [gb, dp]
...
* Externe Links markiert
* Genese-Balkendiagramm:
   * neues Design
   * Links auch der Drucke funktionieren ordentlich
   * (undokumentiert) durch Anpassen der URL kann ein beliebiges Versintervall visualisiert werden, GUI dazu folgt in der nächsten Version
* Textuelles Transkript / Lesetext:
   * Paralipomena-Übersicht (Text / Paralipomena) und Markierung im Textuellen Transkript
   * Neuaufteilung langer Texte
   * Konsistentere Navigation
   * Konsistente Seitenzahlen
   * neues Design
   * diverse typographische Anpassung zur Erhöhung der Lesbarkeit
   * Variantenapparat: Tooltiptext verbessert
* Variantenapparat:
   * Unterstützung für Varianz in der Versaufteilung (z.B. 3356/3357 http://dev.faustedition.net/print/faust1.17#l3355 )
   * Trüber Tag. Feld. im Urfaust
   * Design / Usability verbessert
   * Headnote in den Siglentooltips
* Archiv
   * alle Tabellen sind nun nach allen Spalten sortierbar
   * chronologische Sortierung der Drucke
   * Tabelle Zeugnisse zur Entstehungsgeschichte (XXX soll die so bleiben?)
* Handschriftenansicht
   * leere Seiten werden in der seitenweisen Navigation übersprungen
   * Metadaten: Wasserzeichen
   * Metadaten: Diverse Verbesserungen bei einzelnen Feldern
* Bibliographiesortierung verbessert
* Suche:
   * Neuimplementierung, schneller v.a. bei großen Ergebnismengen
   * Sortierung der Ergebnisse nach Relevanz / Sigle / Vers
   * alle Suchergebnisse auf einer Seite zur Erhöhung der Übersichtlichkeit
   * Siglensuche:
        - Eingabe einer vollständigen Faustedition-Sigle ins Suchfeld führt direkt zum Zeugen
        - Teilstrings werden auch in Siglen / Archivsignaturen gesucht
* Breadcrumbs vereinheitlicht
* diverse Bugs behoben
* diverse Detailverbesserungen

**Comment by gerritbruening** [comment]
@thvitt, would you please have a look on `intro`?

**Comment by gerritbruening** [comment]
sorry, meinte natürlich beta-release

**Comment by thvitt** [comment]
Habichjetzt. Soll das so detailliert bleiben? Dann bleibt nur noch

* [ ] korrektes Datum einsetzen

oder?

**Comment by gerritbruening** [comment]
Danke!
Du hattest halt relativ viele Punkte genannt (s.o.), und ich fand fast alle erwähnenswert. Du kannst ja Kürzungen vornehmen, aber sonst würde ich sagen, du setzt das Datum der voraussichtlichen Release ein und wir geben den Text in die Runde.
