### ISSUE TITLE
Structure View: Clicking the thumbnail does not properly change the view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#19]
When changing from document-view to structure-view by clicking on a priview image, the facsimile appears, but the view does not change accordingly. See the address line and the button taken from http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=97&view=structure
![issue19](https://cloud.githubusercontent.com/assets/10358005/10966376/7e5a7278-83b3-11e5-9465-8326527b362c.png)

**Comment by thvitt** [comment]
not system specific

**Comment by thvitt** [comment]
I was able to reproduce this once, but not afterwards.

**Comment by gerritbruening** [comment]
Same with me.

**Comment by gerritbruening** [comment]
Yes I am able to reproduce it in Firefox: when I open a new tab.
Does seem to apply only to bigger manuscripts.

**Comment by thvitt** [comment]
Could you provide step-by-step instructions to reproduce?

**Comment by thvitt** [comment]
Error log says

    TypeError: metadata is null. faust_image_overlay.js:421:34

**Comment by thvitt** [comment]
Should be fixed by c4c5b28de692b563904d85cf1ab24bb827109578
