### ISSUE TITLE
Display pb/@n in prints

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#190]
While page breaks are visible in the mss document viewer, they have disappeared in the display of printed text.

**Comment by thvitt** [comment]
I guess they go amiss when there is no @f:docTranscriptNo

**Comment by gerritbruening** [comment]
There is no @f:docTranscriptNo when there is no documentary transcript, right?

**Comment by thvitt** [comment]
yes.

They're still there, they're just empty:
```html
<a class="pb n-1 generated-text pageno doclink" id="dt" href="#dt" title="1"></a>
```
So this is probably a side effect of #169

**Comment by gerritbruening** [comment]
As I head already guessed.

**Comment by gerritbruening** [comment]
Great!
