### ISSUE TITLE
Display of sigil hits in search

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#195]
See, for example, http://dev.faustedition.net/search?q=v+h.2.
Two things that seem strange to me:
* colour highlighting of only one blank
* premature end of underlining

**Comment by thvitt** [comment]
Looks like eXist's `util:expand` is slightly off in combination with the ngram index.

For the following query:
```xquery
for $idno in //*:idno[ngram:contains(., 'v h.2')] return util:expand($idno)
```
we get results like:
```xml
    <idno xmlns="http://www.tei-c.org/ns/1.0">
        <exist:match>V H.2</exist:match>4</idno>
    <idno xmlns="http://www.tei-c.org/ns/1.0" type="faustedition" xml:id="sigil">2 <exist:match>V H.2</exist:match>4</idno>
    <idno xmlns="http://www.tei-c.org/ns/1.0" type="wa_faust">2 <exist:match>V H.2</exist:match>4</idno>
    <idno xmlns="http://www.tei-c.org/ns/1.0">
        <exist:match>V H.2</exist:match>8</idno>
```

Since signatures are short, anyway, I think it's best to just turn off highlighting for them (and craft a minimal example to report the issue to eXist).

**Comment by thvitt** [comment]
what have I seen? The `<exist:match>` highlights seem to be actually correct in this example. So is it a bug on the XSLT end?
