### ISSUE TITLE
Integrate notes by J. Schillemeit

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#197]
- [x] find proper name (see mails under "todo Faust 1.0")
- [ ] integrate in sitemap ([4th column](#198))
- [x] special section with introductory remarks in `intro`
- [x] <s>convert word-doc files into TEI / HTML</s>

**Comment by gerritbruening** [comment]
For "define place", see the following wiki pages:
* https://faustedition.uni-wuerzburg.de/wiki/index.php/22._September_2014#Seite:_Zusatzmaterial
* https://faustedition.uni-wuerzburg.de/wiki/index.php/9._Oktober_2014#Zusatzmaterial
* no further information on https://faustedition.uni-wuerzburg.de/wiki/index.php/Sitemap

**Comment by gerritbruening** [comment]
In der Ausgabe lediglich
* Hinweis auf das Material
* Aufsatz von R. Schillemeit im JFDH
* Kontakt (E-Mail Adresse im Hochstift), über den man den Zugang zu den Notizen bekommen kann

**Comment by gerritbruening** [comment]
> [Kurztitel] J. Schillemeit, Faust-Aufzeichnungen 

> [Seitentitel] Jost Schillemeit, Aufzeichnungen zur "Entstehungs- und Konzeptionsgeschichte von Goethes 'Faust'“ 

Anders https://github.com/faustedition/faust-web/issues/228#issuecomment-426226306

Nach Rücksprache mit den maßgeblichen Beteiligten anzupassen.

**Comment by gerritbruening** [comment]
Siehe jetzt
https://github.com/faustedition/faust-web/commit/54ad726ebe82d8bac56bc3812bac4d8826a337c6
und Weg dahin durch
https://github.com/faustedition/faust-web/commit/95c0b4a0ff1a51e0375d911af95376a70366f57d

**Comment by gerritbruening** [comment]
Was wir noch brauchten, wäre
- [ ] pdf des Beitrags
- [ ] [hier](https://github.com/faustedition/faust-web/blob/54ad726ebe82d8bac56bc3812bac4d8826a337c6/content/schillemeit.html#L11) einen funktionierenden Link darauf

@dietmarpravida, kannst du das pdf besorgen und dann @thvitt assignen?

**Comment by gerritbruening** [comment]
@thvitt, zum hier verfolgten Zweck habe ich [etwas Vandalismus](https://github.com/faustedition/faust-web/issues/197#issuecomment-427506400) betrieben. Könntest du mal schauen und das schlimmste verhindern?

**Comment by thvitt** [comment]
der Zeilenumbruch im String ist das Problem, aber ich mach die breadcrumbs eh neu wg. zitationshinweis etc.

**Comment by gerritbruening** [comment]
http://dev.faustedition.net/archive_schillemeit ist immer noch 

>  404: Not Found - Die angeforderte Ressource wurde nicht gefunden.

**Comment by thvitt** [comment]
> Was wir noch brauchten, wäre
> 
>     * [x]  pdf des Beitrags
>     * [ ]  [hier](https://github.com/faustedition/faust-web/blob/54ad726ebe82d8bac56bc3812bac4d8826a337c6/content/schillemeit.html#L11) einen funktionierenden Link darauf

und das darf nun so ohne Passwortschutz veröffentlicht werden?

**Comment by thvitt** [comment]
> @thvitt, zum hier verfolgten Zweck habe ich [etwas Vandalismus](https://github.com/faustedition/faust-web/issues/197#issuecomment-427506400) betrieben. Könntest du mal schauen und das schlimmste verhindern?

@gerritbruening ich habe jetzt im Zuge von #178 und #214 auch den Breadcrumb-/Titelmechanismus überarbeitet. Es ist jetzt möglich, die Breadcrumbs durch Attribute an einem Element (z.B. der `<section>`) zu setzen:
* `data-title` enthält den Titel, also das groß gedruckte
* `data-breadcrumbs` enthält die sonstigen Breadcrumbs, durch `|` getrennt, jeden Breadcrumb in der Form `Titel@link`. Also z.B. `<section class="…" data-title="Archive" data-breadcrumbs="Projekt@project|Danksagung@credits">`. Der `<script>`-Teil kann dann entfallen. Habe das in den ex. content-Inhalten umgesetzt.

**Comment by gerritbruening** [comment]
> den Breadcrumb-/Titelmechanismus überarbeitet

sieht sehr praktisch aus, danke!

**Comment by gerritbruening** [comment]
> und das darf nun so ohne Passwortschutz veröffentlicht werden?

würde ich meinen, immer online damit

**Comment by gerritbruening** [comment]
- [ ] Seitentitel ändern in "Schillemeit, Faust-Aufzeichnungen"
- [ ] Button-Titel entsprechend ändern

**Comment by dietmarpravida** [comment]
wir brauchen jetzt nur noch einen Satz zu den Materialien im intro
