### ISSUE TITLE
 4th column in sitemap for explanatory texts

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#198]
Or reopen #189 ?

**Comment by thvitt** [comment]
Don't reopen.

But it we should check whether we add a 4th item for all of the meta texts besides Archiv / Genese / Text (and maybe integrate the imprint, depending on the results of #187)?

**Comment by gerritbruening** [comment]
Yes,even the imprint may be interesting for users who work on similar projects. However, the imprint is explicitly linked on every page anyway.

**Comment by thvitt** [comment]
Die Frage ist ob das Impressum auf jeder Seite stehen muss, oder ob ein Link 'Über' oder so reicht, der dann auf die inhaltlichen Seiten wie das Impressum verweist. Ich dachte das zu prüfen sei u.a. Gegennstand von #187

**Comment by gerritbruening** [comment]
Ich dachte erst nur an den Inhalt, hab die Link-Frage ergänzt.

**Comment by gerritbruening** [comment]
4. Spalte (Metatexte) in anderer Farbe

**Comment by thvitt** [comment]
Die folgende Aufstellung enthält die vorhandenen Beschreibungstextseiten. In Klammern stehen Informationen, wie die entsprechende Seite bislang verlinkt ist, sofern sie nicht entweder direkt aus Kopf- oder Fußleiste oder über ein Menü prominent in der übergeordneten Seite verlinkt ist. 

Entschieden werden muss:

* Was kommt wie in die Sitemap?
* Brauchen wir weitere Navigationselemente?

----

* [Ausgabe](http://dev.faustedition.net/intro)
    * [Beta-Version](http://dev.faustedition.net/beta-release) (Link in Abschnitt in _Ausgabe_)
        * [Beta-Version 1](http://dev.faustedition.net/beta-release1) (Link am Ende von _Beta-Version_)
    * [Transkriptionsrichtlinien](http://dev.faustedition.net/transcription_guidelines) (zwei Links im Volltext in _Ausgabe_) :warning: 
    * Technische Untersuchungsverfahren  (Abschnitt in _Ausgabe_ mit Bulletpoints) :warning: 
        * [Röntgenfluoreszenzspektrometrie (Tintenanalyse)](http://dev.faustedition.net/x-ray_spectrometry) :warning:
        * [Multispektrale Bildverarbeitung](http://dev.faustedition.net/multispectral_imaging)              :warning:
        * [Wasserzeichenreproduktion](http://dev.faustedition.net/watermarks)                               :warning:
    * [Bibliographie](http://dev.faustedition.net/bibliography) (Abschnitt in _Ausgabe_, außerdem Links von jedem Literaturverweis) :warning:
*  [Projekt](http://dev.faustedition.net/project.php) (Fußleiste, Startseite)
    * [Danksagung](http://dev.faustedition.net/credits.php)
        * [Finanzielle Förderung](http://dev.faustedition.net/credits_finance.php)
        * [Kooperationspartner](http://dev.faustedition.net/credits_coop.php)
        * [Fachlicher Rat, Hilfestellungen, Austausch](http://dev.faustedition.net/credits_advice.php)
        * [Archive, Bibliotheken, private Besitzer von Handschriften](http://dev.faustedition.net/credits_archives.php)
* [Kontakt](http://dev.faustedition.net/contact.php)  (Fußleiste)
* [Impressum](http://dev.faustedition.net/imprint.php) (Fußleiste)

----

* Unbenutzt (ich glaube, in Texte unter _Ausgabe_ eingearbeitet)
    * [intro_genesis_bargraph](http://dev.faustedition.net/intro_genesis_bargraph.php)  Unbenutzt
    * [intro_text](http://dev.faustedition.net/intro_text.php)                  Unbenutzt

**Comment by gerritbruening** [comment]
DP und GB überlegen, wie die 4. Spalte heißen soll, und welche 4 Punkte darunter stehen sollen.

**Comment by thvitt** [comment]
Ggf. müssen es auch nicht unbedingt genau 4 sein. Allerdings sollten ① die jeweiligen Knopfbeschriftungen kurz sein und ② ggf. irgendwo (z.B. für die technischen Verfahren) vernünftige Untermenüs definiert sein.

**Comment by dietmarpravida** [comment]
[Titel:] Info [nicht optimal]
Suche 
Siglen
Zitierweise
Sonstiges
- Handschriftenanalyse
- Bibliographie

**Comment by thvitt** [comment]
Unterpunkte gibt's nicht. Wohin sollte _Sonstiges_ zeigen? Sonst können einfach stattdessen _Handschriftenanalyse_ und _Bibliographie_ anzeigen, sinds halt 5 Punkte.

**Comment by dietmarpravida** [comment]
Aber eins drüber sprichst du ja selbst von Untermenüs?

**Comment by thvitt** [comment]
betonung auf irgendwo, z.B. für die Technischen Untersuchungsverfahren die Liste unter eben dieser Überschrift

**Comment by dietmarpravida** [comment]
machen wir fünf Punkte, das ist dann ziemich komplett (mir fällt zumindest kein fehlender Punkt ein); "Zitierweise" dann vielleicht als letzter Punkt?

**Comment by thvitt** [comment]
ich guck mal wie's aussieht

**Comment by thvitt** [comment]
OK?

![screenshot_100](https://user-images.githubusercontent.com/1906208/29724187-cbe465f0-89c7-11e7-9b43-f5bfbd7d1be9.png)

**Comment by dietmarpravida** [comment]
scheint mir okay

**Comment by gerritbruening** [comment]
Gut so.
Es wäre noch schön gewesen, hier einen direkten Link auf die Transkriptionsprinzipien zu haben.
Denn die sind jetzt außer über das Fragezeichen im document viewer nur schwer zu finden.
Neues Issue dafür?

**Comment by thvitt** [comment]
ich bin bei längerem nachdenken ohnehin nicht so sicher, die meisten Links führen nur auf die /intro-Seite. Wenn Du einen konkreten Verbesserungsvorschlag hast, kann das noch in die beta, sonst sollten wir vllt. irgendwann mal gucken, ob man die infotexte nicht insgesamt übersichtlicher organisieren kann.

**Comment by gerritbruening** [comment]
Ja.
Handschriftenanalyse finde ich übergewichtet.
Stattdessen Link "Transkription"?
