### ISSUE TITLE
add tab icon

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#20]
Should we use a "compressed" version of the Faustedition wordmark?

**Comment by sbruemmer** [comment]
We don't have much space within 16x16 pixels (tab icon dimensions) so we should concentrate on key elements of the logo. Further the icon should work on active and inactive tabs. Here are two suggestions. The yellow arrow icon is not clearly visible on inactive tabs:
![favicon](https://cloud.githubusercontent.com/assets/13978063/11251195/83fdb618-8e30-11e5-8da0-426d2abb43ec.gif)

**Comment by gerritbruening** [comment]
I like both ideas, and I also think we should use the E as you suggest.

**Comment by sbruemmer** [comment]
Adding different formats to site, see: [stackoverflow.com](http://stackoverflow.com/questions/2268204/favicon-dimensions).

Changeset: sbruemmer/faust-web@f5a82e0da1da35b7d7268335e2292e1924133b88
