### ISSUE TITLE
Explain note on Levenshtein distance in search

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#200]
"0.5" ist wohl die ratio?

**Comment by thvitt** [comment]
>a value between 0 and 1 to set the required similarity between the query term and the matching terms. For example, for a minimumSimilarity of 0.5 a term of the same length as the query term is considered similar to the query term if the edit distance between both terms is less than `length(term)*0.5`
> — [Lucene 2.9.4 Docs](https://lucene.apache.org/core/2_9_4/api/core/org/apache/lucene/search/FuzzyQuery.html#FuzzyQuery(org.apache.lucene.index.Term,%20float,%20int))
