### ISSUE TITLE
Sort option in testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#202]
Cannot sort in http://dev.faustedition.net/archive_testimonies until now. Bug or not yet implemented?

**Comment by thvitt** [comment]
I can sort there. Just tried it. Might take a short while though

(I. E. need better bug report ...)

**Comment by gerritbruening** [comment]
Hm. I clicked on the table headers in Firefox (49.0.1) and Chrome (Version 53.0.2785.143 m), but did not see any effect. FF did not even crash ...

**Comment by thvitt** [comment]
interesting.

For me it works fine in firefox, but it doesn't work in chrome. Looks like the sort script doesn't properly initialize depending on sth like weather condition.
