### ISSUE TITLE
Firefox crashes when OK is pressed in print dialog

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#206]
I need to print out pages for proofreading.
Chrome is no alternative because it does not permit scaling the page to fit.
Firefox says: Dieser Tab ist abgestürzt.

**Comment by thvitt** [comment]
Kann ich nicht reproduzieren (Firefox 50.0.2/Linux/diverse Seiten probiert). Bitte URL liefern …

Firefox-Crashes sind meist kein Problem der Seite, sondern eins von Firefox oder einem Addon; d.h. mal [mit einem neuen, leeren Profil probieren](https://support.mozilla.org/de/kb/firefox-profile-erstellen-und-loeschen).

**Comment by gerritbruening** [comment]
URL ist http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.3/gsa_391474.xml&page=2&view=document

Systeme: Windows 8, Windows 10

Firefox: 50.0.2

**Comment by gerritbruening** [comment]
Auch mit einem neuen Profil passiert es.

**Comment by gerritbruening** [comment]
Passiert nicht auf anderen Seiten, insofern doch nicht so wild.

**Comment by thvitt** [comment]
Auf Firefox 49, Windows 7, kann ich das auch nicht reproduzieren. M.E. Firefox-Bug, sehe da erstmal keine Handlungsmöglichkeit unsererseits.
