### ISSUE TITLE
Restore monospaced font

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#208]
See http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.2/gsa_390452.xml&page=1&view=document for the current layout.

For the original layout, see https://faustedition.uni-wuerzburg.de/new/document/faust/2.2/gsa_390452.xml.

("II 2 H4")

**Comment by thvitt** [comment]
That's _monospace italic_, probably missing from the webfonts
