### ISSUE TITLE
Column "Klassifikation" in archive_manuscripts

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#210]
>  Sortierungsmöglichkeit der Handschriften nach Klassifikation wird gewünscht 
https://faustedition.uni-wuerzburg.de/wiki/index.php/Feedback_zur_Beta_1#Seminar_Goethes_Faust:_Entstehung_und_Edition

**Comment by thvitt** [comment]
* Soll die Klassifikation eine zusätzliche Spalte werden oder eine aktuelle Spalte (zB Headnote) ersetzen?
* Was soll mit Zeugen geschehen, die als Klassifikation `n.s.` eingetragen haben?

**Comment by thvitt** [comment]
Now we have quite a few columns. 

Does the 'Archivsignatur' column make any sense on the global list of manuscripts (provided it stays present on the individual repo detail pages)
