### ISSUE TITLE
Access to XML sources

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#214]
> do you plan to give access to downloading the XML-TEI source of the text with an open license (eg CC by-nc-sa)?

https://faustedition.uni-wuerzburg.de/wiki/index.php/Feedback_zur_Beta_1#Nach_der_Bekanntmachung

See also https://faustedition.uni-wuerzburg.de/wiki/index.php/31._M%C3%A4rz_2016#Ver.C3.B6ffentlichung_der_XML-Daten

**Comment by gerritbruening** [comment]
Preferably, download of XML files should be made possible by early 2018 (https://faustedition.uni-wuerzburg.de/wiki/index.php/30.%E2%80%9331._M%C3%A4rz_2017#Downloads_2).

**Comment by gerritbruening** [comment]
Depends on https://github.com/faustedition/faust-web/issues/214.

**Comment by thvitt** [comment]
In #53, you indicate there's a difference between what we offer for download vs. our original source data. I strongly prefer to not differentiate this, but instead to offer the original source data, from a git repository (plus, maybe, some generated stuff, e.g., emended version). This would not only make the edition more transparent and document changes, but also ease collaboration

**Comment by thvitt** [comment]
### Plan

To a point in time to be decided yet, we freeze the current xml folder and extract the following parts for publication:

* [X] `archives.xml`
* [ ] `attic/`
* [X] `document/`
* [ ] `edition/`
* [ ] `egXML/`
* [ ] `event/`
* [X] `image-text-links/`
* [X] `macrogenesis/`
* [X] `print/`
* [X] `print-labels.xml`
* [ ] `readings/`
* [ ] `schema/`
* [ ] `structure/`
* [ ] `template/`
* [X] `testimony/`
* [ ] `testimony-sources/`
* [ ] `text/`
* [ ] `text-sources/`
* [X] `transcript/`
* [ ] `xquery/`
* [ ] `xslt/`

These folders are marked read-only in the old XML structure so we don’t accidently create diverging information. The extracted contents needs to be commit-squashed so we don’t release confidential or copyrighted information from older releases. The extracted contents will then be pushed to faustedition/xml, and all further work with these sources needs to happen there.

The whole history, and the other folders, will be archived locally for reference purposes.

Additionally, we can generate zipped folders of generated contents from the builds:
- emended transcripts
- reading text as TEI
- split testimonies
