### ISSUE TITLE
Order bar diagram chronologically

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#221]
See https://faustedition.uni-wuerzburg.de/wiki/index.php/2._November_2015#Verschiedenes_f.C3.BCr_1.0.

**Comment by thvitt** [comment]
Ach, fehlte noch einmal pushen im anderen Projekt. Hab noch 10 Minuten Geduld :)

Es wird jetzt nach der [Reihenfolge](http://dev.faustedition.net/macrogenesis/refs) sortiert, die aus den Makrogenesesachen rausfällt, genauso wie beim Variantenapparat. Deren Qualität kann ich nicht beurteilen; sie wird hoffentlich nochmal besser, wenn Sandra Krause die Siglen aufgelöst hat

**Comment by gerritbruening** [comment]
Jetzt sehe ich es.
Das Bild ist da, wo ich gerade bin, tatsächlich noch etwas chaotisch.
In die Makrogenese-Sachen habe ich reingeschaut, aber noch nicht tief genug. Was ich dort gesehen habe, schein gut zu sein.
