### ISSUE TITLE
Integrate images of watermarks

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#223]
See http://dev.faustedition.net/watermarks.

**Comment by gerritbruening** [comment]
> * Is this an additional layer for some transcripts (#204)?

not exactly for transcripts, because the watermark is a feature of the leaf (with typically two pages)
> * Does this need specific UI?

I think this depends on the answer to:
> * Where should these images be linked from?

1. List of watermarks 
2. where the watermark info is given in the structure view (link behind the watermark's name). It should be indicated wether the link points to a image that was taken directly from this leaf or to an image of this watermark taken from another leaf

**Comment by thvitt** [comment]
how large are these images? do we need zooming & panning or will they fit on the screen?

**Comment by gerritbruening** [comment]
Original images are large but I think that we could display downscaled images for which we do not need any zooming function.

**Comment by thvitt** [comment]
in this case, we could probably use chocolat as in the info texts (otherwise, we'd probably need an adapted version of the document viewer …)

**Comment by thvitt** [comment]
request (ABR on 2018-04-16) is:
* if we have an image of the watermark of a specific witness, show the watermark image in witness view
* show watermark images by type from watermark table

JPEG image filenames are like

```
GSA_25-W_1360_wm_all_100.jpg JPEG 471x853 471x853+0+0 8-bit Gray 256c 194789B 0.000u 0:00.000
GSA_25-W_1360_wm_detail_100.jpg JPEG 471x512 471x512+0+0 8-bit Gray 256c 123654B 0.000u 0:00.000
GSA_25-W_1360_wm_hand_drawn_150.jpg JPEG 706x768 706x768+0+0 8-bit sRGB 97651B 0.000u 0:00.000
GSA_25-W_1361_wm_detail_100.jpg JPEG 787x945 787x945+0+0 8-bit sRGB 268393B 0.000u 0:00.000
GSA_25-W_1361_wm_hand_drawn_100.jpg JPEG 787x945 787x945+0+0 8-bit sRGB 121023B 0.000u 0:00.000
GSA_25-W_1362_wm_all_100.jpg JPEG 1039x1693 1039x1693+0+0 8-bit Gray 256c 463148B 0.000u 0:00.000
GSA_25-W_1362_wm_detail_100.jpg JPEG 709x827 709x827+0+0 8-bit Gray 256c 209375B 0.000u 0:00.000
GSA_25-W_1362_wm_hand_drawn_150.jpg JPEG 945x1063 945x1063+0+0 8-bit sRGB 141932B 0.010u 0:00.010
GSA_25-W_1371_wm_all_100.jpg JPEG 1643x1088 1643x1088+0+0 8-bit Gray 256c 462497B 0.000u 0:00.000
GSA_25-W_1371_wm_detail_100.jpg JPEG 630x728 630x728+0+0 8-bit Gray 256c 150166B 0.000u 0:00.000
…
```
there are also TIFFs with
```
TIFF/GSA_25-W_1360_wm_all.tif TIFF 1412x2560 1412x2560+0+0 8-bit Grayscale Gray 3.47856MiB 0.000u 0:00.000
TIFF/GSA_25-W_1360_wm_detail.tif TIFF 1412x1535 1412x1535+0+0 8-bit Grayscale Gray 2.10065MiB 0.000u 0:00.000
TIFF/GSA_25-W_1360_wm_hand_drawn.tif TIFF 1412x1535 1412x1535+0+0 8-bit sRGB 6.21297MiB 0.000u 0:00.000
TIFF/GSA_25-W_1361_wm_detail.tif TIFF 2362x2835 2362x2835+0+0 8-bit sRGB 4.5481MiB 0.000u 0:00.000
TIFF/GSA_25-W_1361_wm_hand_drawn.tif TIFF 2362x2835 2362x2835+0+0 8-bit sRGB 458760B 0.000u 0:00.000
TIFF/GSA_25-W_1362_wm_all.tif TIFF 3116x5079 3116x5079+0+0 8-bit Grayscale Gray 15.1228MiB 0.000u 0:00.000
TIFF/GSA_25-W_1362_wm_detail.tif TIFF 2126x2480 2126x2480+0+0 8-bit Grayscale Gray 5305420B 0.000u 0:00.000
TIFF/GSA_25-W_1362_wm_hand_drawn.tif TIFF 1890x2126 1890x2126+0+0 8-bit sRGB 11.5124MiB 0.000u 0:00.000
TIFF/GSA_25-W_1371_wm_all.tif TIFF 4928x3264 4928x3264+0+0 8-bit Grayscale Gray 15.3715MiB 0.000u 0:00.010
TIFF/GSA_25-W_1371_wm_detail.tif TIFF 1890x2185 1890x2185+0+0 8-bit Grayscale Gray 4161440B 0.000u 0:00.000
```
seem to be based on GSA shelfmarks

**Comment by gerritbruening** [comment]
Great, how can I find these images?

**Comment by thvitt** [comment]
[Archiv → Material → Wasserzeichen](http://dev.faustedition.net/archive_watermarks). Images are zoomable. The corresponding table rows are linked from matching entries in the [table of watermarks](http://dev.faustedition.net/watermark-table#Teil_eines_Buchstabens__Fragment_) and in the [metadata view](http://dev.faustedition.net/document?sigil=1_H.3&page=1&view=structure) using an image icon.

**Comment by gerritbruening** [comment]
Now I see, thanks!
