### ISSUE TITLE
Enhance search

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#225]
* ~fuzzy search~ (if not yet enabled) use `something~` to search for something like “something”. Use `something~0.8` (values in (0,1)) to define degree of similarity
* restrictions ❓ 

See https://faustedition.uni-wuerzburg.de/wiki/index.php/3._Februar_2016#Suche.

**Comment by thvitt** [comment]
'Restrictions' needs to be specified.

**Comment by gerritbruening** [comment]
The search may be restricted to spoken text or non-paratext (head, speaker, stage etc.). I have no clear intuition on that question. Needs discussion on one of the next meetings.

**Comment by gerritbruening** [comment]
See https://faustedition.uni-wuerzburg.de/wiki/index.php/10._Juli_2017#Suche.

Default search should not be on testimonies.

**Comment by gerritbruening** [comment]
Die Bereiche, aus der die Suchergebnisse kommen, sollen als Tabs unterhalb der Kopfzeile sichtbar gemacht werden.
