### ISSUE TITLE
URLs of images in //img/@src

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#23]

**Comment by thvitt** [comment]
?

**Comment by sbruemmer** [comment]
Changeset: sbruemmer/faust-web@15d2018849db05924323ca75b618d63fce9fd451

Please proof integration:
- ```transcription_guidelines.php```: transcription_guidelines-image1.png renamed to transcription_guidelines-image8.png
- ```multispectral_imaging.php```: be aware of text deletion to shorten image caption (maybe a link to the document is better to show transiption text), hyperspectral_imaging/media/image4.png and hyperspectral_imaging/media/image5.png missing

Images can float beside text. Just place classes "pure-pull-left" or "pure-pull-right" to the ```<figure>```-Element: e.g. ```<figure class="pure-pull-left">```

**Comment by sbruemmer** [comment]
please note #27

**Comment by gerritbruening** [comment]
OK, good! No objections.

**Comment by gerritbruening** [comment]
Tooltip for image capture.

**Comment by sbruemmer** [comment]
see https://github.com/sbruemmer/faust-web/commit/f246bd4d010b457e74ec70a65ec9b77e2fc744a0

wrap element with a HTML-tag like ```<u class="pure-tooltip" data-content="Text of Tooltip">Element</u>``` to make use of tooltips.

The tooltip can be aligned center (default), left (```<u class="pure-tooltip pure-tooltip-left">```) or right (```<u class="pure-tooltip pure-tooltip-right">```)

**Comment by gerritbruening** [comment]
Thanks for the good explanation!
