### ISSUE TITLE
Integrate complete genetic graph

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#234]
To be accessed from the entry page (19.9.2016).

**Comment by thvitt** [comment]
meinst du einen Link hierauf: https://dev.faustedition.net/genesis_bargraph?rangeStart=1&rangeEnd=12111 ?

**Comment by gerritbruening** [comment]
https://faustedition.uni-wuerzburg.de/wiki/index.php/19._September_2016#Anstelle_eines_Protokolls sagt leider auch nur 

> * Genetischer Gesamtgraph: https://github.com/faustedition/faust-web/issues/234

Ich vermute, dass der grotesk große `subgraph` gemeint ist, der vom oben verlinkten `bargraph` verlinkt ist. Kann man nicht wirklich wollen, glaube ich, und es hat später niemand mehr danach verlangt.

**Comment by thvitt** [comment]
(ohne konfliktkanten) ist der drin

**Comment by gerritbruening** [comment]
Wo verlinkt?

**Comment by gerritbruening** [comment]
Ups, ja richtig. Danke
