### ISSUE TITLE
Display transcripts for T 6 H.1 and T 6 H.2

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#236]
It now says that "Kein Textuelles Transkript vorhanden" but there is one, while there are not images and no documentary transcripts.

**Comment by thvitt** [comment]
Without `page/docTranscript/@uri` in the metadata, the textual transcripts' `pb`s only get an empty `@f:docTranscriptNo` each, and thus `pages.json` doesn't get entries that map page numbers to textual transcripts → textual transcript not found.

**Comment by gerritbruening** [comment]
OK. Any workaround, for example, would-be documentary transcriptions?

**Comment by thvitt** [comment]
We need a fallback somewhere. I need to think about where it has the least side-effects.
