### ISSUE TITLE
Make buttons (more) quadratic

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#24]

**Comment by sbruemmer** [comment]
Fixed with https://github.com/sbruemmer/faust-web/commit/914d72e0c34d7e796332acfdc41a561386ea4495

**Comment by gerritbruening** [comment]
By "buttons" I meant the buttons by which you change the view (facsimile, transcript, text etc.). But it is OK to close this issue since we have discussed these buttons via phone.
