### ISSUE TITLE
"Fehler bei der Volltextsuche"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#243]
See http://dev.faustedition.net/search?q=30%2F319

**Comment by thvitt** [comment]
Das Ziel wurde ja trotzdem erreicht :-)

Die Meldung erscheint immer dann, wenn etwas im Suchfeld eingegeben wurde, was nicht der Lucene-Syntax entspricht. Die Siglensuche funktioniert dennoch.

Muss mal gucken, ob wir irgendeine Fallback-Lösung hinbekommen …

**Comment by gerritbruening** [comment]
Finde es auch nicht schlimm, dachte nur, es sei evtl. nicht im Sinne des "Erfinders".
