### ISSUE TITLE
Include Identnummern in search

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#245]
They are not displayed publicly, but it often happens that we know the Identnummer but nothing else, especially when using https://faustedition.uni-wuerzburg.de/new/xml-query/.

**Comment by thvitt** [comment]
Cf. faustedition/faust-gen-html#36

**Comment by gerritbruening** [comment]
http://dev.faustedition.net/search?q=391098
not found anymore

**Comment by thvitt** [comment]
I’ll include the 'sigil search' in the metadata part.

**Comment by thvitt** [comment]
284b5d2ac857e82174de2f0a75c02bdac0756c40
