### ISSUE TITLE
Some Ident numbers not found

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#246]
Cf. https://github.com/faustedition/faust-web/issues/245.

Result for [349271](http://dev.faustedition.net/search?q=349271) is as expected.
Result for [391098](http://dev.faustedition.net/search?q=391098) seems to be the filename, not the `<idno>`.
I get no result for [312226](http://dev.faustedition.net/search?q=312226) which appears as `<idno>` in `xml/document/archival/gsa/GSA_13-33-5_St_22.xml`.

**Comment by thvitt** [comment]
> Result for [391098](http://dev.faustedition.net/search?q=391098) seems to be the filename, not the `<idno>`.

To avoid redundant matches, the sigil search only returns one sigil per matching document. Looks like the URI comes first.

> I get no result for [312226](http://dev.faustedition.net/search?q=312226) which appears as `<idno>` in `xml/document/archival/gsa/GSA_13-33-5_St_22.xml`.

search content needs to be updated manually by now due to security setup. Document probably didn't have the ident number when I last ran the conversion.

**Comment by gerritbruening** [comment]
> Looks like the URI comes first.
Why is the URI involved here?

**Comment by thvitt** [comment]
Because its in `sigil-labels.xml`. You never want to search for the URI?

**Comment by gerritbruening** [comment]
Well, I could sourch for the file URL, so if this is implemented, there is no need to change. But I think I always looked for the Identnummer part of the URL.
