### ISSUE TITLE
Integrate text snippets in table of testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#250]
It would be great to give some brief impression of each testimony's text. For this purpose we markup the key phrase which makes a testimony relevant for Faust with the `<rs>` element:

    ...
    <milestone unit="testimony" spanTo="#graef_1901_end_b" xml:id="graef_1901_b"/>Das
    <rs>Hauptgeschäft</rs> durch alles
    dieses nicht unterbrochen.<anchor xml:id="graef_1901_end_b"/>
    ...

At first we did only intend theses phrases to be highlighted when the complete text is rendered. But now I think that we could include these phrases, surrounded, e.g., by dots, in the last column of the table. @thvitt , do you think this could be feasible?

**Comment by gerritbruening** [comment]
Depends on https://github.com/faustedition/xml/issues/15.

**Comment by thvitt** [comment]
yes, would be feasable when we do the linking

**Comment by thvitt** [comment]
Snippets are there when they're there (first `<rs>` after `<milesone unit="testimony">`)
