### ISSUE TITLE
Remove column "Druckort"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#251]
Probably replace by https://github.com/faustedition/faust-web/issues/250.

**Comment by thvitt** [comment]
We might also consider replacing the column's contents with the standard citation once every testimony has a bibliography entry.

**Comment by gerritbruening** [comment]
Needs discussion because many of our sources are second-rate. DP wishes to add standard editions for the texts so that they may be displayed in the column. But users may find it confusing to click on a bibliographic entry that links to a text from another source.

**Comment by gerritbruening** [comment]
Was in Druckort steht, ist eigentlich die Textvorlage, und das ist hier eine sekundäre Information. Die zum jetzigen Zeitpunkt maßgebliche Ausgabe haben wir noch nicht durchgängig angegeben, oder, @dietmarpravida?

**Comment by dietmarpravida** [comment]
Die Angabe der aktuellen Ausgaben schaffen wir nicht mehr für Beta3.

**Comment by thvitt** [comment]
Entscheidung: 
* Druckortspalte raus, info steht auf nachgeordneter Seie
* aktuelle Ausgaben → neues Issue
