### ISSUE TITLE
Harmonize act labels

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#252]
In http://dev.faustedition.net/genesis, "Akt I" etc. should be replaced by "I. Akt" etc.

In http://dev.faustedition.net/genesis_faust_ii it should be made clear that I, II, ... V are acts. "I. Akt", "II. Akt" etc.  seems preferable, according to http://dev.faustedition.net/genesis.

This was mentioned on [February 23, 2017](https://faustedition.uni-wuerzburg.de/wiki/index.php/23._Februar_2017).

**Comment by thvitt** [comment]
Really roman numerals? http://dev.faustedition.net/print/faust2 has _5. Akt_ etc.

**Comment by gerritbruening** [comment]
Right! Then "1. Akt", etc.!

**Comment by gerritbruening** [comment]
Typische Szenenbezeichnung: II,2 (Akt 2, Szene 2).

**Comment by thvitt** [comment]
III. Akt

* [ ] SVGs
* [ ] Inhaltsverzeichnis Texte
* [ ] Breadcrumbs, #256

**Comment by gerritbruening** [comment]
Agree on roman numerals for act labels.
