### ISSUE TITLE
Make help button more prominent

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#253]
This was mentioned on [February 23, 2017](https://faustedition.uni-wuerzburg.de/wiki/index.php/23._Februar_2017) as a reported user feedback.

In the meeting, the help button was mentioned as being too small.

**Comment by gerritbruening** [comment]
Seems ad hoc to me. Better fix https://github.com/faustedition/faust-web/issues/25.

**Comment by sbruemmer** [comment]
Regarding the new, icon-based, header menu this issue maybe can be closed.
