### ISSUE TITLE
Act level in breadcrumbs

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#256]
@sbruemmer, @thvitt, did we ever discuss if the act level could be introduced in the breadcrumbs?

In the following user feedback, only the bar diagram is mentioned:
> Breadcrumps im Ganttchart: Es wäre hilfreich, wenn hier auch zu erkennen wäre, in welchem Akt man sich befindet.

**Comment by thvitt** [comment]
Aber wohin soll's zeigen?

* Gantt Chart, Ansicht für den ganzen Akt

**Comment by thvitt** [comment]
As a closing remark:

### How the genesis breadcrumbs work

The mapping from Schroer numbers to scenes is manually maintained in [scenes.xml](https://github.com/faustedition/faust-gen-html/blob/master/xslt/scenes.xml). This file is augmented by act entries for Faust II aggregated from scenes with id _2.n.x_ and then translated to JSON (`data/scene_line_mapping.js`).

When a verse range in the bar diagram is selected, the breadcrumb is formed of _Genesis_ plus all enclosing scenes / acts from that json file. If the innermost interval doesn't match exactly the displayed verse range, the actual line range is appended. The last entry of the breadcrumbs bar is the heading, everything else is a clickable breadcrumb.

**Comment by gerritbruening** [comment]
> If the innermost interval doesn't match exactly the displayed verse range, the actual line range is appended.

Can I see an example for this?

**Comment by thvitt** [comment]
* [within II. Akt](http://dev.faustedition.net/genesis_bargraph?rangeStart=8000&rangeEnd=8400)
* [within a scene](http://dev.faustedition.net/genesis_bargraph?rangeStart=8100&rangeEnd=8200)

See also #112
