### ISSUE TITLE
Ignore leading zeros in testimony id

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#258]
> kein XML für »graef_850«

The corresponding milestone is `<milestone unit="testimony" xml:id="graef_0850" spanTo="#graef_0850_end"/>` in `xml/testimony/wa_IV/wa_IV_2.xml`.
Problem of leading zeros is [mentioned briefly in the original issue](https://github.com/faustedition/faust-web/issues/237#issue-196967863).

**Comment by thvitt** [comment]
Needs to be handled in the …:

1. html transformation
2. testimony index

→ 'real' HTML ids will be different from 'source' xml:ids. Hope we don't have links to this somewhere else
