### ISSUE TITLE
Make the "Text" button a direct link to a scene

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#270]
depending on where you are in "Genese" or the document viewer. Link could depend on the last part breadcrumb.

**Comment by gerritbruening** [comment]
This would be inconsistent, admittedly, since "Archiv" cannot be turned into a direct link.

**Comment by thvitt** [comment]
* the other links in the header line point to entry pages
* the entry pages wouldn't be directly accessible
