### ISSUE TITLE
Add scene level to breadcrumb again

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#271]
The scene level has disappeared from breadcrumb. Is that intended?

See https://github.com/faustedition/faust-web/issues/256.

**Comment by thvitt** [comment]
Where?

**Comment by gerritbruening** [comment]
In the archive, where we now have
> Genese > Faust II > I. Akt

**Comment by thvitt** [comment]
Where exactly? Link pls. I see the expected breadcrumbs everywhere I checked, [e.g. 2 I H.31](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.1/gsa_390894.xml&page=1&view=structure). You might need to [refresh your cache](http://refreshyourcache.com/en/cache/).

**Comment by gerritbruening** [comment]
Now I have them without doing something special.
