### ISSUE TITLE
Info about testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#272]

**Comment by gerritbruening** [comment]
Vgl. den Passus im GJb:

> Eine Ergänzung  des Archivs bieten die „Dokumente zur Entstehungsgeschichte des Faust“, wie sie sich in Briefen, Tagebuch- und Gesprächsaufzeichnungen und anderen schriftlich überlieferten Dokumenten erhalten haben. Sie wurden tabellarisch erfasst und in das Archiv der Edition integriert.
[Fußnote:] Die Entstehungszeugnisse in den maßgeblichen Sammlungen von Hans Gerhard Gräf und Otto Pniower wurden vollständig erfasst und mit einem Verweissystem versehen, das es in der Version 1.0 erlauben wird, von hier aus auf verfügbare Digitalisierungen zuzugreifen.

**Comment by dietmarpravida** [comment]
Dokumente zur Entstehungsgeschichte 
Die Dokumente zur Entstehung des ‚Faust‘ versammeln alle bislang bekanntgewordenen Äußerungen Goethes und anderer Zeitgenossen, die sich auf den ‚Faust‘ beziehen lassen, in Briefen, Tagebuch- und Gesprächsaufzeichnungen und weiteren schriftlich überlieferten Dokumenten. Der Bestand der mehr als 1500 Zeugnisse integriert die früheren Sammlungen von Otto Pniower (1899) und Hans-Gerhard Gräf (1904) und ergänzt sie um erst seither publizierte Dokumente. Die Dokumente sind nach Möglichkeit als vollständige Texte verfügbar, die jeweils ‚Faust‘ betreffende Passage wird auszugsweise in der Tabelle der Zeugnisse angezeigt, die zugleich die wichtigsten Angaben wie Datum, Verfasser, Adressat, Verweis-Nummern enthält.
