### ISSUE TITLE
patchInteraction broken

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#276]
eg. the patch in

- [H S. 358](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=358&view=document)
- [III H.2:1, S. 5](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.3/gsa_391473.xml&page=5&view=document)

**Comment by thvitt** [comment]
It's not a regression: The patch interaction in [2 H, 61](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=61&view=facsimile_document) works fine. So what is different for the other one?

@gerritbruening, this is also a case for the Testhandschrift

**Comment by gerritbruening** [comment]
If you switch to `facsimile_document`, patch interaction works, doesn't it?

**Comment by thvitt** [comment]
strange.

**Comment by thvitt** [comment]
Ah, patch interaction generally only works in `facsimile_document`, never in plain `document`
