### ISSUE TITLE
Make accesses Archiv, Genese, Text more prominent

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#279]
See https://faustedition.uni-wuerzburg.de/wiki/index.php/30.%E2%80%9331._M%C3%A4rz_2017#Design_2.

As first step we have highlighted the accesses in the editions's basic colours, depending on which slide appears in the slider.

There were some more ideas to reorganize the slider, e.g., moving the edition's title to the first slide and removing it from the lower part of the index page.

**Comment by sbruemmer** [comment]
Regarding the new, full size slideshow with all access points linked as buttons this issue maybe can be closed.

**Comment by gerritbruening** [comment]
Yes!
