### ISSUE TITLE
Combined line synopsis and inline apparatus

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#283]
__[Für ein Mockup des aktuellen Planungsstands siehe diesen Kommentar](https://github.com/faustedition/faust-web/issues/283#issuecomment-292175292)__

According to the latest meeting, the now integrated variants are to appear smaller or less prominent.

**Comment by thvitt** [comment]
Ein hübsches Beispiel ist Vers 8490 aus der Perspektive von 2 H.

Potentielle Probleme:

1. unterschiedliche Apparatdarstellungen → gleiche Endstufe. Hier: Endstufe/Lesetext »Gewoges regsamem«, 2 III H.3, 2 III H.3a:1 und die Drucke: »Gewoges regſamem«, 2 H: »Gewoges regsamen⟨:regſamem⟩«
2. Wohin mit den Siglen?

**Comment by thvitt** [comment]
## Mockups

### 1. Gruppierung nach Endstufe, Siglen nur im Apparat

#### 1.1 Apparat kleiner
![selection_006](https://cloud.githubusercontent.com/assets/1906208/24652054/7ed222a0-1930-11e7-9dac-b81990f9234b.png)


#### 1.2 Apparat kleiner und eingerückt
![selection_004](https://cloud.githubusercontent.com/assets/1906208/24651966/1dacbdb4-1930-11e7-9cb3-23d770b8c691.png)

##### 1.3 Apparat kleiner, eingerückt und dunkelgrau
![selection_005](https://cloud.githubusercontent.com/assets/1906208/24652018/554a7b6c-1930-11e7-9857-bfec285e5bf9.png)

**Comment by thvitt** [comment]
#### 2.1 immer Endstufe vor Apparat
![selection_007](https://cloud.githubusercontent.com/assets/1906208/24654445/ee11ce8c-1939-11e7-84cd-06e921511ea8.png)

#### 2.2 Siglen überall
![selection_008](https://cloud.githubusercontent.com/assets/1906208/24654517/3f03d13c-193a-11e7-99b8-ae6a65fdee69.png)

#### 2.3 Siglen im Apparat, groß
![selection_009](https://cloud.githubusercontent.com/assets/1906208/24654710/2c69456a-193b-11e7-8b94-3a7ef9a1ad70.png)

### 3 Apparat _über_ Endstufe
![selection_010](https://cloud.githubusercontent.com/assets/1906208/24654864/eeff6d2a-193b-11e7-93e0-9b1acaa7ff1f.png)

Diese Variante sieht in eingerückt oder mit Varianten in der Apparatzeile doof aus.

**Comment by gerritbruening** [comment]
Sehr gut, danke!
Punkt 2 sollte noch eine Überschrift haben, oder?

**Comment by gerritbruening** [comment]
Zu 1.1: Können Apparatzeilen, die mit der Endstufe identisch sind, nicht doch wegfallen?

**Comment by thvitt** [comment]
In dem Beispiel gibt es keine mit der Endstufe identischen Apparatzeilen (außer Lesetext). Und wo sollten die Siglen der weggefallenen Zeilen stehen? Wenn mal Siglen nur im Apparat und mal nur in der Endstufe stehen, ist das verwirrend.

**Comment by gerritbruening** [comment]
Ja richtig, das lange s. Aber trotzdem ist oder scheint es
> nicht klar, warum die Zeilen zum Teil dreimal vorkommen

Und:
> Wenn mal Siglen nur im Apparat und mal nur in der Endstufe stehen, ist das verwirrend.

bin ich mir nicht sicher.

**Comment by thvitt** [comment]
### 4 Einblendungsapparatzeilen nur, wenn Binnenvarianz vorhanden ist

![selection_011](https://cloud.githubusercontent.com/assets/1906208/24755827/e901bff8-1adb-11e7-916e-5401b30f8f88.png)

Diese Version orientiert sich zunächst an 1.3 oben, führt Varianz jedoch nur dort auf, wo sich zwischen Endstufe und (Apparat+Zeichennormalisierung) ein Unterschied ergibt. Die __Siglen__ stehen in der Endstufe für alle Zeugen, die sich von der Endstufe allenfalls durch Zeichennormalisierung unterscheiden, für alle anderen Zeugen in der entsprechenden Apparatzeile.

----

Diese Version wird etwas nervig zu erzeugen sein:

1. in der Vorbereitung benötigen wir für jede Zeile in jedem Zeugen die Endstufe (E), die normale angereicherte Transkriptdarstellung (T) sowie die normale angereicherte Transkriptdarstellung + Zeichennormalisierung (N)
2. Apparatdarstellung getrieben durch Endstufendarstellung.
3. Für jede Endstufengruppe G im Apparat: Finde alle Einträge aus N, die von der Endstufe abweichen (V)
4. Endstufe normal rendern mit Siglen für G-V
5. darunter für jedes v \in V v als Apparat rendern, mit Sigle

Vorsicht mit gejointen Zeilen etc. 

Ob ich die Endstufe durch apparatus.xsl jagen kann und es kommt die Endstufendarstellung raus? Müsste eigentlich?

**Comment by gerritbruening** [comment]
Der jetzige Zustand hat einen komischen Effekt:
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=1&view=print&section=391098.all#l9115

> Trippelnden Schritt_e_〈tilgt〉s am Boden hin?        2 III H.2:1, C.1 4, C.2α 4, C.3 4

Das e ist in `2 III H.2:1` getilgt, in `C.1 4, C.2α 4, C.3 4` erscheint es aber. Ist es nicht unlogisch, dass diese Zeugen in einer Zeile stehen? Ist das Teil dieses Issues oder ein Extraproblem?

**Comment by thvitt** [comment]
Die Gruppierung der zusammengehörigen Zeilen ist hier suboptimal. Die Gruppierung muss an einer Textdarstellung orientiert sein, nicht an einer XML-Darstellung; ich denke mal, dass das dadurch zusammenfällt.

Ich würde das jetzt nicht separat lösen wollen, weil für die in diesem Issue avisierte Darstellung ohnehin aufwändigeres Prozedere nötig ist mit nachdenken über Vergleiche. D.h. entweder bleibt's so fehlerhaft für beta.3, oder wir gehen auf den beta.2-Stand (mit Endstufe im Apparat) zurück.

**Comment by gerritbruening** [comment]
Einverstanden!

**Comment by thvitt** [comment]
Einverstanden mit "bleibt so" oder mit "wie beta.2"?

**Comment by gerritbruening** [comment]
Bleibt so wie jetzt dev, nicht wie beta 2.

**Comment by dietmarpravida** [comment]
Ähniche Fälle, wie die von Gerrit (am 18. Juli) bemerkten: 
1482 Sich um〈’ erg〉s Genügen 
2978 Mein wohlgemeſſ〈’ erg〉nes Theil davon.

**Comment by thvitt** [comment]
Zum Thema Pseudovarianten – es ist jetzt für den Lesetext zu so vielen Angleichungen gekommen, dass ich die grundsätzlich nicht mehr aus den Varianten herausrechnen werde – nicht nur aus technischen, sondern auch aus inhaltlichen Gründen. D.h., wenn die »Print«-Darstellung (Endstufe) des zugrundeliegenden Zeugen vom Lesetext abweicht (z.B. durch . oder () in den BA), wird's auch dafür zwei Einträge im Variantenapparat geben. Ich würde allerdings den Lesetext bei der Berechnung der Variantenzahl grundsätzlich nicht mitrechnen.

**Comment by gerritbruening** [comment]
Ja, ist vermutlich das einzig mögliche.

**Comment by thvitt** [comment]
Die saubere Variante ist wohl:
- sowohl emended-XML als auch prepared-XML kommen in die Zeilensammlung, mit differenzierendem Attribut
- eine Funktion / ein Modus berechnet zu jeder Zeile einen Gruppierungsschlüssel, der ſ/s normalisiert etc. sowie Tags ausserialisiert. Anhanddessen wird unterschieden zwischen Zeilen, die in beiden Versionen gleich sind und solchen die sich unterscheiden
- alles wird m.o.w. durch apparatus.xsl gejagt, weil die Apparatdinge schlicht nicht vorkommen für die emended-Versionen
- für die Sortierung wird ein Index nach topologischer Sortierung herangezogen

**Comment by thvitt** [comment]
@gerritbruening @dietmarpravida – um Missverständnissen vorzubeugen: die jetzt umgesetzte Implementierung des Apparats sortiert die Zeilen zunächst nach der [aus der Makrogenese berechneten Reihenfolge](http://dev.faustedition.net/macrogenesis/refs) und fasst dann nur identische _und benachbarte_ Belege zusammen. Wenn also vier Zeugen W, X, Y, Z in dieser Reihenfolge angeordnet sind und  die folgenden Varianten haben: W: bla / X: bla / Y: blubb / Z: bla dann ist der Apparat W, X: bla / Y: blubb / Z: bla

Die neue Implementierung kann natürlich neue Bugs hinzugefügt haben, ggf. bitte Issue aufmachen.

**Comment by thvitt** [comment]
Hat keiner gemacht, dann also hier: Reihenfolge Binnenvarianz, Endstufe wie bei der letzten Telko gewünscht

![screenshot-new-variant-order](https://user-images.githubusercontent.com/1906208/45699854-4e0a6900-bb6b-11e8-8eb2-5e6f43e7cd1f.png)
