### ISSUE TITLE
Facsimile downloads

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#285]
According to [30./31. März 2017](https://faustedition.uni-wuerzburg.de/wiki/index.php/30.%E2%80%9331._M%C3%A4rz_2017#Downloads_2):

The facsimiles should be downloadable
* as single page
* as complete document

as far as copyright allows.

**Comment by thvitt** [comment]
cf. #232

**Comment by gerritbruening** [comment]
> as far as copyright allows.

Welche Auflösungen beim Download (und ob dieser überhaupt erlaubt ist), erfährt man hier: https://faustedition.uni-wuerzburg.de/wiki/index.php/Handschriften_au%C3%9Ferhalb_des_GSA

**Comment by thvitt** [comment]
Decision from today’s meeting:
* download individual images by linking appropriate JPEG
* to allow downloading everything, provide a JSON with links

**Comment by thvitt** [comment]
Bin mal durch und habe ein wenig analysiert. 

Die __Regeln__ ([werden in archives.xml bearbeitet](https://github.com/faustedition/faust-xml/blob/master/xml/archives.xml)), zum einsatz gekommen sind:

|Repository        |\.downloadable |\.resolution¹ |\.max\-width|\.max\-dpi|
|------------------|---------------|-------------|------------|----------|
|agad\_warszawa    |yes            |             |            |          |
|bb\_cologny       |yes            |             |            |          |
|bb\_vicenza       |yes            |reduced      |            |          |
|bj\_krakow        |yes            |             |            |          |
|bl\_london        |               |             |            |          |
|bl\_oxford        |yes            |reduced      |            |          |
|bsb\_muenchen     |               |             |            |          |
|dla\_marbach      |yes            |             |            |          |
|fdh\_frankfurt    |yes            |             |            |          |
|gm\_duesseldorf   |yes            |             |            |          |
|gsa               |yes            |             |            |          |
|location\_unknown |yes            |             |            |          |
|mlm\_paris        |yes            |             |            |          |
|print             |yes²          |             |            |          |
|privatbesitz      |yes            |             |            |          |
|sa\_hannover      |yes            |             |            |          |
|sb\_berlin        |yes            |             |1600        |          |
|thlma\_weimar     |               |             |            |          |
|tml\_new\_york    |yes            |             |            |72        |
|ub\_basel         |yes            |             |            |          |
|ub\_bonn          |yes            |             |            |          |
|ub\_leipzig       |yes            |             |            |          |
|ul\_edinburgh     |yes            |             |            |          |
|ul\_pennstate     |yes            |             |            |          |
|ul\_yale          |yes            |             |            |          |
|veste\_coburg     |yes            |             |            |          |

¹ bei den Drucken habe ich angenommen, dass es da keine Restriktionen gibt.
² 'signifikant reduzierte Auflösung', ich habe Level 2 = 25% angenommen

Fast alle Bilder können in voller Auflösung angeboten werden:

|level  |count  |percent  |histogram                                           |
|------:|------:|--------:|----------------------------------------------------|
|0      |5364   |98\.08   |\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*|
|1      |76     |1\.39    |                                                    |
|2      |9      |0\.16    |                                                    |
|3      |8      |0\.15    |                                                    |
|n/a    |12     |0\.22    |                                                    |

Die "levels" sind Reduzierungen jeweils um 50%, dh. wenn 0 = Originalgröße = 300dpi, dann 1=150dpi, 2=75dpi etc. In dieser Form liegen die Bilder bereits für die Weboberfläche vorberechnet vor (als JPG).

Die `n/a`-Angaben beziehen sich auf zwei Gruppen. Für sechs Bilder liegt __keine Downloadgenehmigung vor__ nach den Daten:

|repo       |sigil        |base                    |page  |reason              |
|-----------|-------------|------------------------|-----:|--------------------|
|bl\_london |2\_I\_H\.0b  |bl\_london/Egerton\_2829|1     |no\-download        |
|bl\_london |2\_I\_H\.0b  |bl\_london/Egerton\_2829|2     |no\-download        |
|bl\_london |2\_I\_H\.41a |bl\_london/Zweig\_152   |1     |no\-download        |
|bl\_london |2\_I\_H\.41a |bl\_london/Zweig\_152   |2     |no\-download        |
|bl\_london |2\_III\_H\.50c|bl\_london/Add\_20723   |1     |no\-download        |
|bl\_london |2\_III\_H\.50c|bl\_london/Add\_20723   |2     |no\-download        |

Die übrigen sechs wurden __nicht gefunden__, d.h. hier sind vermutlich die XML-Daten falsch:

|repo   |sigil       |base        |page  |img                            |reason              |
|-------|------------|------------|-----:|-------------------------------|--------------------|
|gsa    |2\_III\_H\.79|gsa/390567  |1     |gsa/390567/25\_W 1665\_BL1v    |not\-found          |
|gsa    |2\_V\_H\.2  |gsa/390883  |18    |gsa/390883/GSA\-W\-1618\-a     |not\-found          |
|gsa    |2\_V\_H\.2  |gsa/390883  |18    |gsa/390883/GSA\-W\-1618\-b     |not\-found          |
|gsa    |2\_V\_H\.2  |gsa/390883  |18    |gsa/390883/GSA\-W\-1618\-c     |not\-found          |
|print  |D\.1        |\.          |109   |print/D\(1\)\_IV3\-1/1\)\_IV3\-1\_105|not\-found          |
|print  |D\.1        |\.          |109   |print/D\(1\)\_IV3\-1/D\(       |not\-found          |


[Detailübersicht über alle Digitalisate (downloads.csv)](https://github.com/faustedition/faust-web/files/8650787/downloads.csv)

**Comment by gerritbruening** [comment]
> bei den Drucken habe ich angenommen, dass es da keine Restriktionen gibt

Das ist richtig; diese Aufnahmen haben wir selbst angefertigt.
