### ISSUE TITLE
Spalten "Quellengattung", "Verfasser" und "Adressat" in ein Feld "Beschreibung" zusammenführen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#289]
Fusionierungsregeln siehe https://github.com/faustedition/faust-gen-html/blob/master/xslt/testimony-table.xsl#L56.

**Comment by gerritbruening** [comment]
@thvitt: Geht das?

@dietmarpravida: bitte die obigen Regeln ergänzen.

**Comment by thvitt** [comment]
Ist schon machbar

**Comment by thvitt** [comment]
Weitere Patterns könnt Ihr hier https://github.com/faustedition/faust-gen-html/blob/master/xslt/testimony-table.xsl#L56 selbst hinzufügen

**Comment by gerritbruening** [comment]
Danke! Mit `addressat` scheint es ein Problem zu geben, das wird bei mir nicht aufgelöst. Vielleicht ein Tippfehler statt `adressat`, @thvitt ?

**Comment by gerritbruening** [comment]
Danke! Es gibt jetzt nur noch Einzelprobleme mit Werten, v.a. in der Spalte 'Titel'. @dietmarpravida , schaust du da gelegentlich mal drüber?

**Comment by gerritbruening** [comment]
@dietmarpravida, bei den Gesprächen habe ich jetzt einfach `Gesprächsbericht von $verfasser` eingesetzt (https://github.com/faustedition/faust-gen-html/commit/d5f31406b6adbd00519b1cc81a734e14148273ea).
