### ISSUE TITLE
please proof content pages

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#29]
These pages maybe can be deleted:
- ```acknowledgement.php``` empty and not linked
- ```G_ZS_Visualisierung.php``` not linked
- ```T_ZS_Text.php``` not linked
- ```onepage.php``` not linked, holds duplicate content of other ressources

The following pages should be link and thus available for the public:
- ```x-ray_spectrometry.php``` only linked in onepage.php which is not reachable
- ```watermarks.php``` only linked in onepage.php which is not reachable
- ```multispectral_imaging.php``` only linked in onepage.php which is not reachable

**Comment by thvitt** [comment]
`onepage.php` shouldn't be deleted. It dynamically aggregates all the pages containing texts about the edition on one page to make it easy to produce printouts etc. for proofreading.

**Comment by gerritbruening** [comment]
acknowledgement.php will have content in the future (1.0)
T_ZS_Text.php is not used now and will maybe never be used but has text content that is worth to be saved.
Closed by https://github.com/faustedition/faust-web/commit/2c2ddcef07d660cb1f978a2cc83c923bdc677952 and https://github.com/faustedition/faust-web/commit/b1301259e6e341ee021c6d14ca38014fd7497cb2
