### ISSUE TITLE
ſ missing in Ubuntu Mono

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#290]
For an examples (upright and italics), see 
http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/sb_berlin/SBB-IIIA_Ms_germ_qu_527.xml&page=2&view=document

**Comment by thvitt** [comment]
It's not missing in Ubuntu Mono, just in the webfont subset that is included wit hthe page
