### ISSUE TITLE
yellow background for :target?

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#291]
I have now been clicking on the [gray bar that highlights the line from the URL fragment](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.3/gsa_390567.xml&page=2&view=text#l9964) several times because I've been confusing the inline apparatus view from the variants apparatus, mainly after a search.

I would prefer if the `:target` style highlighting the 'current' line would be in a lighter version of the edition's yellow instead, so it is visually distinct from the gray marking variants.

**Comment by gerritbruening** [comment]
Yes, that's confusing!
I am not sure about the yellow because the `add` area is also highlighted in yellow.

**Comment by thvitt** [comment]
`<add>` is only highlighted on hover.

**Comment by gerritbruening** [comment]
I know, and if you think that the contrast between the two yellows is good enough to see this second highlighting, you might implement this!

**Comment by thvitt** [comment]
Beispiel: [2 I H.15 S. 2 v.5220](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.1/gsa_391064.xml&page=2&view=print#l5220) in beiden textuellen Ansichten mit Apparat-Highlighting zum Kontrast und im Vergleich zu beta.3 angepasster Farbe der markierten Versnummer:

![faust-web_291_gradient](https://user-images.githubusercontent.com/1906208/30427707-16f0044e-9951-11e7-9e91-c0de4a275808.png)

**Comment by thvitt** [comment]
nobody complained → we'll keep it this way.
