### ISSUE TITLE
Fixed table header displaced rightwards

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#295]
http://dev.faustedition.net/archive_testimonies

![grafik](https://user-images.githubusercontent.com/10358005/27710687-dc76d098-5d20-11e7-9c77-1bada94b159a.png)

**Comment by thvitt** [comment]
Ich sehe nicht, was da im Code anders ist als bei den anderen Tabellen, wo das mit den Headern funktioniert … @sbruemmer, sehen Sie, was ich in archive_testimonies falsch mache?

**Comment by gerritbruening** [comment]
Passiert nur in Firefox.

**Comment by sbruemmer** [comment]
Der verlinkte Commit sollte das Problem lösen. Werde ich mit dem nächsten PR übergeben.

**Comment by thvitt** [comment]
Ich fürchte, das tut's nicht, das Problem tritt auch mit https://github.com/sbruemmer/faust-web/commit/c71d1d4efd7a5129de899e5ab8e76e0f87c5c89c noch auf.

Mein Eindruck ist, dass das .css() nicht effektiv wird oder noch irgendwann überschrieben. Nachdem ich resizeFixed mal ein wenig loggen ließ:

```js
         function resizeFixed() {
            $t_fixed.find("th").each(function(index) {
               var   oldWidth = $(this).css("width"),
                     newWidth = $this.find("th").eq(index).css('width');
               $(this).css("width", newWidth);
               $(this).css("color","red");
               console.log('Adjusted ', $(this).text(), ' width: ', oldWidth, ' -> ', newWidth, ' = ', $(this).css('width'));
            });
```

![screenshot_099](https://user-images.githubusercontent.com/1906208/28464564-1b1acd3e-6e26-11e7-8207-ad00251c11e3.png)

82px wäre eigentlich ja gut, aber die Spalte ist 105px breit. Nach ein wenig Fensterwechseln finde ich sogar

```
Adjusted  Gräf  width:  105px  ->  82px  =  105px
```

im Log. 	Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

Strange, aber ich hab ein déjà vu …
