### ISSUE TITLE
Aggregate scribal hand information in structure view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#297]
Immediate aim: list all scribal hands that appear in a manuscript.

**Comment by thvitt** [comment]
There’s a suggestion in the current dev version; cf. commits https://github.com/faustedition/faust-gen-html/commit/1ee2017f91e520568edfdfdddfbc0a75685f4da9, https://github.com/faustedition/faust-gen-html/commit/82185625f4da998d65c91a24cf5715a6ec907311, https://github.com/faustedition/faust-gen-html/commit/f9d0556fe5b63faf012ee71a7c6c2f8c945f2cf5

The extra section at the bottom of the witnesses might be overkill for smaller witnesses, I’ve experimented with a more compact representation in  https://github.com/faustedition/faust-gen-html/commit/82185625f4da998d65c91a24cf5715a6ec907311:
![schreiber-1](https://user-images.githubusercontent.com/1906208/86517513-c9fda000-be29-11ea-8871-a59c75734aa6.png)
However, this is not feasable for larger witnesses like 2 H:
![schreiber-1-2_H](https://user-images.githubusercontent.com/1906208/86517527-eef21300-be29-11ea-9307-ae773e1d8db6.png)

**Comment by thvitt** [comment]
Solution has been approved on 2022-06-27.

Todos:

* [ ] list (and resolve) errors
* [ ] determine (and classify) scope
* [ ] aggregate information (csv file?)

**Comment by gerritbruening** [comment]
Plus, it would be great to have a page (analogous to the one about watermarks) where all scribal hands throughout the edition are listed, with relevant witnesses in a second column.
