### ISSUE TITLE
Change buttons broken when come from scene overview

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#299]
When I get from here
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=1&view=print&section=391098
to here
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=209&view=print&section=391098.6#scene_2.3.1
I cannot change to facsimile or other view.
Can you reproduce this? Or is this a feature?

**Comment by thvitt** [comment]
```
SyntaxError: '#scene_2\.3.1' is not a valid selector  faust_viewer.js:584
	revealState http://dev.faustedition.net/js/faust_viewer.js:584:31
	createDocumentViewer/setView</< http://dev.faustedition.net/js/faust_viewer.js:1248:13
	init http://dev.faustedition.net/js/faust_viewer.js:190:13
	createDocumentViewer/< http://dev.faustedition.net/js/faust_viewer.js:1331:9
	createDocumentViewer http://dev.faustedition.net/js/faust_viewer.js:1329:15
	viewer< http://dev.faustedition.net/documentViewer.php:103:18
	<anonymous> http://dev.faustedition.net/documentViewer.php:101:17
SyntaxError: '#scene_2\.3.1' is not a valid selector faust_viewer.js:584
	revealState http://dev.faustedition.net/js/faust_viewer.js:584:31
	createDocumentViewer/loadPage</</< http://dev.faustedition.net/js/faust_viewer.js:843:17
	loadDocs/</< http://dev.faustedition.net/js/faust_viewer.js:440:21
	xhr.getResponseText/< http://dev.faustedition.net/js/faust_common.js:464:15
	xhr.getXhr/xhr.onreadystatechange http://dev.faustedition.net/js/faust_common.js:444:15
```

Probably we're missing a `\.`? […#scene_2.3\.1](http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=341&view=print&section=391098.12#scene_2.3\.1) works, and we're appearently adding the first `\` from the error messages […](https://www.youtube.com/watch?v=yzLT6_TQmq8)
