### ISSUE TITLE
please note broken image links

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#30]
The following image-links within ```multispectral_imaging.php``` are broken:
[hyperspectral_imaging/media/image4.png](/faustedition/faust-web/blob/master/multispectral_imaging.php#L66)
[hyperspectral_imaging/media/image5.png](/faustedition/faust-web/blob/master/multispectral_imaging.php#L68)

**Comment by gerritbruening** [comment]
Closed by https://github.com/faustedition/faust-web/commit/43669956928b7e46aec0ecca3dc3d1bc97d5158b
