### ISSUE TITLE
Paragraphs in testimony text view seem first-line indented

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#301]
![grafik](https://user-images.githubusercontent.com/10358005/28260209-40270c40-6ada-11e7-95f9-12716366cdf9.png)

Example from http://dev.faustedition.net/testimony/graef_850b

**Comment by thvitt** [comment]
af2a209a18348b084f1d0a2b894d2dda66513e00 `.text { text-indent: .25em; }`

**Comment by thvitt** [comment]
Lieber @sbruemmer, erinnern Sie sich noch, welche Funktion das in meinem letzten Kommentar erwähnte text-indent: .25em haben sollte?
