### ISSUE TITLE
Line synopsis broken when come from a search

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#303]
When I search for "[Lappen](http://dev.faustedition.net/search?q=Lappen)" and then navigate to ["Lappen" in 2 I H.0a](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/dla_marbach/Cotta-Archiv_Goethe_23.xml&page=30&view=text#l5220), the line synopsis is broken.
When I leave the document viewer for, e.g., genesis and enter the document viewer from there, the line synopsis behaves as expected.

**Comment by thvitt** [comment]
I cannot reproduce this.

1. Search for [Lappen](http://dev.faustedition.net/search?q=Lappen)
2. Click "Lappen" in the 2 I H.0a entry
3. Click "Variantenapparat"
4. Click any of the lines

Everything works.


Could it be that you confused the gray background marking the current verse (5220) in the [inline apparatus view that you linked](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/dla_marbach/Cotta-Archiv_Goethe_23.xml&page=30&view=text#l5220) with the gray background indicating multiple variants in the [line synopsis](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/dla_marbach/Cotta-Archiv_Goethe_23.xml&page=30&view=print#l5220)?

**Comment by thvitt** [comment]
Cf. #291

**Comment by gerritbruening** [comment]
> Click "Variantenapparat"

Ups, sorry for the alarm!
