### ISSUE TITLE
Integrate XPath query

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#304]
If possible, invent some basic combinations that may be entered in natural language and then transformed into XPath expressions, e.g. text phrase and scribal hand and writing medium.

**Comment by thvitt** [comment]
This is to vague to implement and too technical to discuss.

I will not expose a real XPath query for security reasons.

There is a likewise vague issue at #225 for search enhancements. 

I think what we should do is:

1. collect detailed specifications on what information and what combinations of aspects should be possible to be retrieved. 'For example' should be forbidden in this list 😉 
2. look at the details on how this information is available in the data, and how easy it would be to make this available (via search or other means)
3. think about a UI for each feature or combination of features (forms, query language, facets, tables, …)
4. prioritize, and create individual issues for detailed planning of the individual features


If there is no specific reason for this issue, I'd suggest closing as duplicate of #225

**Comment by gerritbruening** [comment]
> for security reasons

Hm, what does that mean?
> specifications on what information and what combinations of aspects should be possible to be retrieved

Will be quite difficult to anticipate. The most important thing would be to search for strings and @ `new` values:

> Mit einer Abfrage kann im gesamten Corpus nach Zeichen in Kombination mit Schreiberhand und Schreibmaterial gesucht werden, also etwa nach allen Anführungszeichen, die von Goethe mit Bleistift geschrieben wurden.

**Comment by thvitt** [comment]
Exposing the XPath interface means, e.g., exposing `document(uri)` which would allow our exist to be used as an open proxy.

**Comment by gerritbruening** [comment]
Instead: #405.
