### ISSUE TITLE
beta.3 release notes

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#308]
I'll list issues, someone write the text …

**Comment by gerritbruening** [comment]
Werde ich, fürchte ich, nicht schaffen, weil ich noch eine andere Frist habe.

**Comment by thvitt** [comment]
Die Issues, die mit `beta.3` markiert sind, sind [über diese Suche](https://github.com/search?q=org:faustedition+milestone:beta.3&type=Issues) im aktuellen Zustand zugänglich. [Im Wiki ist eine kategorisierte Liste auf einer Seite in der gewohnten Darstellung](https://faustedition.uni-wuerzburg.de/wiki/index.php/Beta.3-Issues).

**Comment by thvitt** [comment]
Textvorschlag [hier im Wiki](https://faustedition.uni-wuerzburg.de/wiki/index.php/Beta.3-Issues), bitte überarbeiten.

**Comment by dietmarpravida** [comment]
ich finde den Text gut, kleinere Änderungen habe ich eingetragen

**Comment by gerritbruening** [comment]
Ebenso!
