### ISSUE TITLE
image zoom in transcription guidelines

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#318]
In the [transcription guidelines](http://beta.faustedition.net/transcription_guidelines), the images are not marked up for the image zoom feature (#27), thus causing strange effects (link in caption does not work)

Do we have large versions there? Otherwise, probably look at chocolat to see how we mark those images as ignored

**Comment by sbruemmer** [comment]
We should not solve this trying to get zoomable versions of images.

It's more a question of a better implementation based on well choosen selectors like `a[data-overlay*="chocolat"]`.

I will fix that.

**Comment by sbruemmer** [comment]
As stated in 85c2890 we use the default chocolat selector, which is `class="chocolat-image"` on the anchor, to initiate the gallery view.
