### ISSUE TITLE
cookie warning

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#322]
do we need a click-away cookie warning for the site?

**Comment by gerritbruening** [comment]
Ist wohl heute Standard? Ich sehe das auf fast jeder Seite, selbst Blogs von irgendwelchen Privatleuten.

**Comment by dietmarpravida** [comment]
Ich habe für solche Zwecke eigens "I don't care about cookies" installiert, die mir das Wegklicken erspart
