### ISSUE TITLE
clicking on link symbol before 354 S, A fails to generate link

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-web#325]
Wenn ich das Link-Symbol ∞ zur ersten Bühnenanweisung im Text von S und von A (vor 354: "In einem hochgewölbten, engen, gothischen Zimmer, Faust unruhig auf seinem Sessel am Pulte. ") anklicke, dann erscheint in der Browserzeile kein  Link. 

Bei der nächsten Bühnenanweisung (vor 430: "Er schlägt das Buch auf und erblickt das Zeichen des Makrokosmus." funktioniert es aber, ebenso vor 354 in B, Ba, C1, C3, D1 und D2 (wo dann z.B. "http://dev.faustedition.net/print/B9_IIIB20-2.4#lbefore_354_c" in der Browserzeile erscheint).

**Comment by thvitt** [comment]
Habe das Problem durchaus auch in B before_354_c feststellen können.

HTML-Ausschnitt:

```html
<div data-n="before_354_c" data-varcount="10" data-variants="3" data-vargroup="35" class="stage rend-firstLineIndented rend-small n-before_354_c hasvars varcount-10 variants-3"><a id="lbefore_354_c" href="#lbefore_354_c" class="lineno invisible">∞</a>In einem
   hochgewölbten, engen, gothischen Zimmer <span class="hi rend-normal rend-letter-spaced"><a class="lineno invisible"> </a>Faust</span>
   unruhig auf seinem Sessel am Pulte.
</div>
```

Das `<a class="lineno invisible">` innerhalb des span überdeckt durch das CSS das korrekte `<a>` innerhalb des übergeordneten `<div>`. Sollte da nicht generiert werden.
