### ISSUE TITLE
show tacit corrections in synopsis of prints

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-web#328]
Ergänzungen von Zeichen in den Drucken, die aufgrund von Satzfehlern in den benutzten Exemplaren der Drucke fehlen, sollten auch im synoptischen Apparat als solche markiert werden. (Beispiel: D.1, 3159, https://github.com/faustedition/xml/issues/137); B, 3095, https://github.com/faustedition/xml/issues/138).

**Comment by gerritbruening** [comment]
http://dev.faustedition.net/print/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I.16#l3095

**Comment by thvitt** [comment]
Können wir das für den kleinen Informatiker etwas technischer & detaillierter fassen? 

Bei [der von Gerrit markierten Stelle](http://dev.faustedition.net/print/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I.16#l3095) tauchen die `[]` im Apparat nicht auf, da das gegenwärtige Verfahren zum Zusammenfassen der Belege mit gleichem Inhalt nur Änderungen im (XML-)Text berücksichtigt und nicht solche, die ausschließlich Markup betreffen (die Apparatzeile hier stammt also aus dem Lesetext, nicht aus 1 H.1). Das muss im Zuge von #283 ohnehin angegangen werden.

Wenn es um Änderungen geht, die auch in der normalen Druckansicht (ohne irgendwas aufzuklappen) noch nicht gezeigt werden, bitte Markup und gewünschte Darstellung angeben.

**Comment by gerritbruening** [comment]
Dieses Issue ist also Teil von #283 und als solcher zu closen, richtig?
Denn in der Einzelansicht ohne Ausklappen wird ja alles gezeigt, was gezeigt werden soll.

**Comment by thvitt** [comment]
[Kommas sind jetzt da](http://dev.faustedition.net/print/faust.15#l3095)

**Comment by gerritbruening** [comment]
Finde ich gut so. @dietmarpravida auch?

**Comment by dietmarpravida** [comment]
muss jetzt noch wo erklärt werden
