### ISSUE TITLE
Add an overlay containing an archive-specific note to the manuscript view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#33]
[image-captures.xlsx](https://github.com/faustedition/faust-web/files/88906/image-captures.xlsx)

**Comment by thvitt** [comment]
Kann das nicht in die `archives.xml`?

**Comment by gerritbruening** [comment]
Ja, aber wie machen wir das bei Sonder Vorschriften für einzelne Hss?

**Comment by thvitt** [comment]
Ich dachte, das wäre nur eine? Dann explizit im JS, das die Caption setzt. Sonst muss das vielleicht doch irgendwo in die Metadaten?

**Comment by gerritbruening** [comment]
Ach, es sind jetzt doch welche dazugekommen, wie aus der Tabelle zu ersehen. Mir ist alles recht, auch Metadaten.

**Comment by gerritbruening** [comment]
New version:
[image-captures.xlsx](https://github.com/faustedition/faust-web/files/88906/image-captures.xlsx)

**Comment by thvitt** [comment]
Now, there is a note at the bottom left of the facsimile view, please test.

* The strings are maintained in the json file at [data/copyright_notes.js](https://github.com/faustedition/faust-web/blob/master/data/copyright_notes.js).
* [ ] Unfortunately, this does not seem to work in the split view page, although I thought I'd use common code. So I'll need to look at this.
* [ ] Needs to be styled properly.

Please test and report any issues.

**Comment by gerritbruening** [comment]
This looks beautiful! Just a few remarks / questions:
* The message appears pretty small on my screens.
* When I zoom in it is released from the bottom margin and moves up to the middle of the screen---intended?
*

**Comment by thvitt** [comment]
The other issues had already been fixed, just not propagated to beta.faustedition.net yet.

I've just updated manually

**Comment by gerritbruening** [comment]
Great! I like it very much.
