### ISSUE TITLE
facsimile and facsimile_document view broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#339]
Look at, e.g.,
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=152&view=facsimile#scene_2.2.3.2
(tried Firefox and Chrome)

**Comment by thvitt** [comment]
works in beta.3

**Comment by thvitt** [comment]
It works when you remove the `.php` from the URL, which leads us to the questions:
1. why does it break with `.php`?
2. where does the `.php` come from?

**Comment by thvitt** [comment]
419ad203e34bc44efe6326e181e3aadab3d590bf is the first bad commit
