### ISSUE TITLE
"Kein Textuelles Transkript vorhanden"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#341]
See, for example,
http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/sb_berlin/SBB-IIIA_Ms_germ_qu_527.xml&page=1&view=print
I remember we discussed this before, see https://github.com/faustedition/faust-web/issues/236. In the above linked case you have to click several times before the textual transcript appears. In a way this is correct, since there is no textual transcript which corresponds to the first pages. It is possibly frustrating for users, though.

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/issues/144
#15

**Comment by gerritbruening** [comment]
Thanks.
So close this as duplicate? Or keep it as an example to look at when taking care of the other issues?
