### ISSUE TITLE
bar graph 10899--10916: bar for 2 IV H.22d seems too long

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#343]
See http://dev.faustedition.net/genesis_bargraph?rangeStart=10899&rangeEnd=10916.

As the tooltip says, 2 IV H.22d does not cover such a long portion of the text.

**Comment by thvitt** [comment]
```json
   {
      "source" : "faust://xml/document/archival/bb_cologny/G-30_10.xml",
      "print" : false,
      "sigil" : "2 IV H.22d",
      "intervals" : [
         {
            "start" : 10889,
            "end" : 10899,
            "type" : "verseLine",
            "page" : 1,
            "section" : "G-30_10"
         }
      ]
   }
```

so this is probably a js bug caused by the interval covering only one line.

**Comment by gerritbruening** [comment]
Is it really only one line?
10889 10899 (eight eight nine, eight nine nine)

**Comment by thvitt** [comment]
ah ok makes it more mysterious

**Comment by thvitt** [comment]
wrong ending of line occurs iff start of line is before the beginning of the display interval

**Comment by thvitt** [comment]
there is a glitch in the calculation of the bar lengths when the bar starts before the visible interval of the bar graph.
