### ISSUE TITLE
should the bar graph start/end be adjusted by –0.5 verses?

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#344]
In the current genetic bar graph visualisation, the bars start at the vertical line (if drawn) which represents the first verse and they end at the line that represents the last verse. This makes them the correct width, but it might be interpreted wrong. E.g., the last verse in this witness is actually 10899, not 10900:

![screenshot_122](https://user-images.githubusercontent.com/1906208/34259311-1e6e7dc8-e662-11e7-9ae8-1d19e71a6dd8.png)

A possible fix would be to move the bars to the left by 0.5 verse widths, so this one would end visibly before 10900. An alternative might be to render the verse labels not centered with the vertical lines, but left-aligned to the right of the vertical lines; thus representing that the vertical line does not mark verse 10900 but rather the beginning of verse 10900 (i.e. the verse follows after the line).

**Comment by gerritbruening** [comment]
> left-aligned to the right of the vertical lines; thus representing that the vertical line does not mark verse 10900 but rather the beginning of verse 10900 (i.e. the verse follows after the line)

Seems preferable to me!
