### ISSUE TITLE
bars in bargraph far too long

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#346]
For example, compare
http://beta.faustedition.net/genesis_bargraph?rangeStart=10345&rangeEnd=10782
which now looks like this:
http://dev.faustedition.net/genesis_bargraph?rangeStart=10345&rangeEnd=10782

The bar for 2 IV H.5 should be quite short.

Maybe there is a connection to https://github.com/faustedition/faust-web/issues/345?

**Comment by thvitt** [comment]
No, the regression had been introduced with the fix for #343.
