### ISSUE TITLE
Kursivausgleich?

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#352]
zB um [das _bis_](http://dev.faustedition.net/print/faust.30#l4989)

**Comment by gerritbruening** [comment]
Ja, das hatten wir doch schonmal im Zusammenhang mit Hervorhebungen oder so? IIRC hast du dann etwas geschaffen.

**Comment by thvitt** [comment]
e0df4230d3f3619f35890501bf202297e272c823, hatt ich schon wieder vergessen …
