### ISSUE TITLE
Header correction for jump targets

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#353]
currently, jump targets (from fragments) are hidden behind the fixed header.

[This Stackoverflow question](https://stackoverflow.com/questions/4086107/fixed-page-header-overlaps-in-page-anchors) discusses possible solutions.

**Comment by thvitt** [comment]
There's a group of solutions that add extra padding or height that is compensated with negative margin.
* CSS solutions that do that in the `:target`ed element look fine, but interfere with actual padding/margin settings from existing styles 
* CSS solutions that create a `:before` of the neccessary height and compensate that with a negative margin cause the background to be displaced or too large, the background may even overlap existing content.

**Comment by thvitt** [comment]
There's a group of solutions that add extra padding or height that is compensated with negative margin.
* CSS solutions that do that in the `:target`ed element look fine, but interfere with actual padding/margin settings from existing styles 
* CSS solutions that create a `:before` of the neccessary height and compensate that with a negative margin cause the background to be displaced or too large, the background may even overlap existing content.
* [Nicolas Gallagher's Method E](http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-E) interferes with the right border (which we might be able to get rid of using :after)

**Comment by gerritbruening** [comment]
Ah, herrlich!
