### ISSUE TITLE
Transkriptionseinblendung nicht als Standard?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#354]
Wird immer erst weggeklickt, um die Handschrift zu sehen.

**Comment by sandrakrause** [comment]
Dieser Punkt wurde auch im Seminar letzte Woche angesprochen.
Dort wurde auch vorgeschlagen, die Einblendung nicht sofort anzuzeigen.
Problem dabei: Um die Einblendung dann einzuschalten, muss man erst wissen, dass man diese Möglichkeit überhaupt hat (was man als Neuling vielleicht nicht sofort erkennt).

Alternativ wurde angeregt, dass man es vielleicht möglich machen könnte, die Transkription doch gleich einzublenden, aber mit einem Klick auf die Handschrift deaktivieren zu können (was wohl laut Aussage eines Teilnehmers die intuitive Handhabung wäre).
Daraus folgte die Idee, dass es schön wäre, wenn das Anzeige-Menü bei Klick auf die Handschrift dort erscheint und man dann dort zwischen den möglichen Anzeigeoptionen wählen könnte.

**Comment by thvitt** [comment]
da gips doch noch ein anderes Issue zu?

**Comment by gerritbruening** [comment]
Ja, wo ist das nochmal?
@sandrakrause, Sie haben da doch auf Englisch kommentiert? Wissen Sie, wo es ist?

**Comment by sandrakrause** [comment]
Ich kann mich leider nicht an einen derartigen Kommentar erinnern und finde auch gerade nichts in bisherigen Beiträgen.

**Comment by thvitt** [comment]
ich habe jetzt, dem Usability-Prinzip der Sichtbarkeit folgend, die beim letzten F2F-Treffen diskutierte Variante implementiert (#400) – default sichtbar, klick schaltet aus/ein. Wenn das immernoch zu Usability-Problemen führt, reopen.

**Comment by gerritbruening** [comment]
Ich denke, das ist alles, was man sich wünschen kann, danke!
