### ISSUE TITLE
Add justification of beta-version

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#359]
(Suggested by Gengnagel, paragraph 37/38)
Why is it okay to release beta-version when it’s not ready/there are things to improve

**Comment by gerritbruening** [comment]
Is this a serious question or rather a "philosophical" one?
Do you have a good quote?

**Comment by sandrakrause** [comment]
I guess it is more a general problem with beta versions, especially in academic contexts than a critisism to the faust edition.
It might be worth to add a little text about being aware of the beta-status and the consequences, though.

> Deciding to be transparent about this dynamical process is a step in the right direction – but it also raises questions of a different kind. If no digital edition is ever finished, when will it shed its beta status? If it never sheds its beta status, how can it ever be reviewed or referenced? For the declaration as a beta version implies testing phase, which in turn implies unreliability, which in turn serves as a convenient response to any and all criticism. Who judges the ‘ripeness’, as a colleague called it, of a digital edition? Only the editors themselves? [...] **Why release something at all, if it is not polished to a satisfying degree**? Making something public on the internet is a publication. Is the fast-paced publication of something that holds less quality that it is already anticipated to hold after an update not grist to the mill of all the detractors of everything digital?
[...] Relying on user feedback to constantly maintain and update a service is one thing – there is an advantage to that. It is resource-friendly. But academia, as susceptible as it might be to the everlasting need for improvement, is based around the concept of reliability when it comes to publications. [...] It is very much an issue of traceability and replicability. In the digital academic context, that need cannot be met by conventional means of page or line number – too much of the perception is tampered with by the environment in which the ‘pages’ and ‘lines’ are hosted, too much is changing, changing, always changing.
