### ISSUE TITLE
Publish XML-data and transformation process

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#361]
(Suggested by Mertens, S. 303- 304)
to make it accessible in the future and to ensure that the data will be available for future analysis methods.

**Comment by sandrakrause** [comment]
This is already planed and announced for V1.0.
(see: http://beta.faustedition.net/beta-release)

**Comment by gerritbruening** [comment]
See https://github.com/faustedition/faust-web/issues/214.
