### ISSUE TITLE
Show footer in facsimile-view and text section

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#365]
(Suggested by Gengnagel, paragraph 19)
Footer is disappearing when accessing those views

**Comment by gerritbruening** [comment]
Does that mean: when entering the Text section in the sense of the reading text?

**Comment by sandrakrause** [comment]
Yes, it means the reading text.
Her point is, that somebody who wants to revisit the editorial principles while reading the text would have easier access to it with the footer shown.

**Comment by sandrakrause** [comment]
As I see now, they can be accessed with the link to the sitemap, so I guess that's not a problem anymore.
