### ISSUE TITLE
No access with Microsoft's new browser "Edge"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#37]
After entering user and password, I got the following error message:

Unauthorized
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by thvitt** [comment]
Beta uses simple standardized HTTP Digest authentication, and I didn't find any further hints in the server logs. Currently don't have Edge at hand to test, though

**Comment by gerritbruening** [comment]
I think the issue will resolve itself since version 1.0 will not be password protected.
