### ISSUE TITLE
Linkziel unter dem header verborgen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#376]
Wenn ich z.B. http://dev.faustedition.net/search?q=kumpan suche und dann auf den Treffer klicke, lande ich hier:
http://dev.faustedition.net/print/faust2.5#l7136
Damit ich die Kumpan-Zeile sehe, muss ich aber immer etwas runterscrollen.

Dasselbe Phänomen beobachte ich beiden Apparaten. Wenn ich hierhin gehe:
http://dev.faustedition.net/print/faust.7#app.after_2048.ehrerbietig
muss ich auch erst runterscrollen, bis die Stelle erscheint.

Liegt das am Browser? (Firefox 59.0 auf Windows 10)
Aber mein Chrome verhält sich genauso.

**Comment by thvitt** [comment]
Ja, das ist #353

**Comment by gerritbruening** [comment]
Alles klar, danke!
