### ISSUE TITLE
Update of transcripts in dev 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#378]
I have changed `xml/transcript/gsa/391098/0369.xml` some days ago, but 
http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=369&view=document#scene_2.4.1
still looks unchanged.

**Comment by thvitt** [comment]
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=369&view=document#scene_2.4.1 should have been updated [21.03.2018 00:14:17](http://dev.digital-humanities.de/ci/job/faust-gen/lastStableBuild/). Your URL is from the beta which won't be updated until the next beta release

**Comment by gerritbruening** [comment]
Oh, sorry for the alarm!!

**Comment by gerritbruening** [comment]
Now I am on
http://dev.faustedition.net/document?sigil=2_H&page=71&view=document_text#l5896
not seeing the expected effect of http://dev.faustedition.net/document?sigil=2_H&page=71&view=document_text#l5896.

**Comment by thvitt** [comment]
Ah, forgot to configure the trigger for the faust-xml submodule. The build should run next time someone pushes to faust-xml.

PS: Please don’t reuse old issues. Made me investigate the thing from the description first.

**Comment by gerritbruening** [comment]
Thanks!

> Please don’t reuse old issues. Made me investigate the thing from the description first.

OK, next time I will resist!
