### ISSUE TITLE
Suppress Q in genesis and print view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#388]
We seem to have Q in the genesis view now, see
http://dev.faustedition.net/genesis_bargraph?rangeStart=8275&rangeEnd=8487
Is this intended?

**Comment by thvitt** [comment]
There are a few verses marked with `@n` in Q’s transcript, so it’s a logical consequence.

**Comment by gerritbruening** [comment]
The reason behind this is that @dietmarpravida uses Q as idno in the crit app which in turn is the reason why Q now appears in `xml/document/print`.
However, all posthumous editions are excluded from the edition's interface, irrespective of whether or not they have `@n`s.

**Comment by thvitt** [comment]
1. I don’t want to sprinkle code to special-case specific witnesses all over the various places in the source projects. This information should be encoded in the document metadata.
2. What should happen when you click the _Q_ in the apparatus entries?

**Comment by thvitt** [comment]
If _Q_ only ever occurs in the apparatus, a possible solution would be to allow bibliography keys additionally to sigils. So we remove Q’s metadata or encode it to be skipped and add an entry for Q to the bibliography.

Would involve minor work in the text specific stuff, but seems like a clean solution to me.

**Comment by gerritbruening** [comment]
Agree to mark Q's document file in an appropriate way,
agree to link on a bibliographic entry instead of a full fledged witness rendering.

**Comment by gerritbruening** [comment]
@dietmarpravida, do you agree?

**Comment by gerritbruening** [comment]
I have removed Q from `xml/document/print/`.

**Comment by gerritbruening** [comment]
IIRC, Q is also referenced in the document files at some places by means of a `document/print` or similar path. Could you verify this, @thvitt?

**Comment by thvitt** [comment]
```
xml/macrogenesis/wa/15_2/II.xml
34:        <item uri="faust://document/wa/Q"/>
264:        <item uri="faust://document/wa/Q"/>

xml/macrogenesis/wa/15_2/III.xml
133:        <item uri="faust://document/wa/Q"/>

xml/macrogenesis/wa/15_2/V.xml
9:        <item uri="faust://document/wa/Q"/>
↑ source code line numbers
```

**Comment by dietmarpravida** [comment]
agree, mark Q's document file in some appropriate way in the apparatus or skip it completely.

**Comment by gerritbruening** [comment]
`xml/document/print/Q...` is removed.

@dietmarpravida, could you supply
    * URI
    ** short title
    *** long title

on https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise?

**Comment by dietmarpravida** [comment]
So?
*faust://bibliography/Q
**Q
***Goethe, Johann Wolfgang von: Poetische und Prosaische Werke in zwei Bänden. Mit den schützenden Privilegien sämtlicher Staaten des deutschen Bundes. [Hrsg. von Johnn Peter Eckermann und Friedrich Wilhellm Riemer.] Des ersten Bandes zweite Abtheilung, Stuttgart und Tübingen 1836.

**Comment by dietmarpravida** [comment]
ich habe entsprechend auch in die Datei faust://bibliography/Q für "Q" eingetragen
