### ISSUE TITLE
Back button broken when going from bar graph to document viewer

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#389]
When I am here
http://dev.faustedition.net/genesis_bargraph?rangeStart=8275&rangeEnd=8487
and go to
http://dev.faustedition.net/documentViewer?sigil=2_II_H.64&page=1&view=facsimile

I cannot use the back button to return to the bar graph. Is this intended?

**Comment by thvitt** [comment]
There are too many (4?) calls to state.toLocation()

As a workaround, long-click the back button and select the first entry that _doesn’t_ contain a sigil.

**Comment by gerritbruening** [comment]
In Firefox, it seems I have to select the 4th entry of this list.

**Comment by gerritbruening** [comment]
Same seems to be the case when changing manuscripts in the print view.

**Comment by thvitt** [comment]
the problem will always occur when you navigate from elsewhere to the documentViewer. It’s a consequence of #321 + too many calls to the function that maintains the history/address bar.

**Comment by thvitt** [comment]
there are two calls to toLocation, so I guess the other two entries are the ones being replaced:

```
Navigated to http://localhost:81/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=204&view=facsimile

toLocation called  making history from  toLocation@http://localhost:81/js/faust_viewer.js:77:104
setPage@http://localhost:81/js/faust_viewer.js:431:11
init@http://localhost:81/js/faust_viewer.js:272:11
createDocumentViewer/<@http://localhost:81/js/faust_viewer.js:516:9
createDocumentViewer@http://localhost:81/js/faust_viewer.js:514:15
@http://localhost:81/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=204&view=facsimile:94:20

faust_viewer.js:77:15
toLocation called  making history from  toLocation@http://localhost:81/js/faust_viewer.js:77:104
setView@http://localhost:81/js/faust_viewer.js:507:11
init@http://localhost:81/js/faust_viewer.js:276:11
createDocumentViewer/<@http://localhost:81/js/faust_viewer.js:516:9
createDocumentViewer@http://localhost:81/js/faust_viewer.js:514:15
@http://localhost:81/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=204&view=facsimile:94:20
```
