### ISSUE TITLE
Shorter slider autoplay duration

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#39]
I commit https://github.com/faustedition/faust-web/commit/aa6cafe54c0a5d5ca21379f6ca0647cc313f9e37 the duration of the slider autoplay was set to 15sec. Maybe this is too long to make users aware of more than one slide wihtout interaction.

I guess 5sec could be a good duration.

Also be aware of new function which stops autoplay as a users clisk on an element wihtin the slideshow: https://github.com/sbruemmer/faust-web/commit/76057cb942da094141d7a57e7c3fd9baf315c4f8

**Comment by thvitt** [comment]
There's an face-to-face project meeting tomorrow, I guess we'll just try out the “feel” of some values then.

**Comment by thvitt** [comment]
I guess 4c72b30 sets this to an acceptable value (8s) and we can close this. Reopen if it should be changed again …
