### ISSUE TITLE
Lesetext in Anzeige / Navigation / URLs etc.

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#392]
Nun, da wir einen konstituierten Text haben …

* Sigle z.B. im Variantenapparat (ist: _Lesetext_) und der Suche
* URL-Teil (ist: `faust` (noch unter print bzw. bald `/text/faust`))
* Repräsentation im Menü, und wo sollen die entsprechenden Links hinführen

**Comment by gerritbruening** [comment]
> Sigle z.B. im Variantenapparat 

Text (nicht _Lesetext_)

Breadcrumb  auf Seite (jetzt) `print/faust`: "Faust"
