### ISSUE TITLE
Update info on reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#393]
@thvitt, I would like to update the info text on the Lesetext so that it conforms the future reading text. I would do this in the near future so that our students may read and evaluate this text.
However, just like the new reading text itself, this info should be skipped in beta 4.
Is this feasible?
Where should I place this info so that it can be skipped?

**Comment by thvitt** [comment]
The information will probably live on a page of its own, anyway? Write it into a separate HTML file, confine the commits that modify existing pages (i.e. link to the new text) to as few as possible and list them and the page to remove in #394

**Comment by gerritbruening** [comment]
Present info is on
http://dev.faustedition.net/intro#lesetext
This would have to be updated, i.e., modified.
I will try to make the edit (modification and link) in one and the same commit.

Yes, detailed info will be given on a separate page.

**Comment by gerritbruening** [comment]
Provisionally fixed in https://github.com/faustedition/faust-web/commit/9944896bf75eaa13ac1792de4a0a16768d4766aa.
