### ISSUE TITLE
beta.4 preparation

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#394]
* [ ] replace the whole reading text assembly with a simple pipeline that inserts the emended version of _H_ into the appropriate div in _A_ to form a reading text structured like in 1.0, but with the text sources as in beta.3

**Comment by gerritbruening** [comment]
Plus, mention notable changes, such as:
* index page and header
* refactoring of the document viewer
* (possibly) c&p citation
* (probably) images of printed editions

**Comment by gerritbruening** [comment]
Keep this in mind for #502.

**Comment by thvitt** [comment]
zu beta 4 ist es ja nun nie gekommen
