### ISSUE TITLE
Links from search to prints broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#395]
See
http://dev.faustedition.net/search?q=dauben
klick on a result --> 
> 404: Not Found - Die angeforderte Ressource wurde nicht gefunden.

Links to manuscripts seem to work.

**Comment by thvitt** [comment]
The section index seems to be off in the search results.

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/commit/4618b92842bc56febdf45ca8bd6e450cd6e7f9ad
