### ISSUE TITLE
new styling for transcription_guidelines.php necessary?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#4]

**Comment by sbruemmer** [comment]
I made some minor stylings. sbruemmer/faust-web@

Beside listings, using justified text soothes design (although browser justification is not that elegenat and maybe leads to ugly word spacings).

But more significant would be working on the images. This is where i need help and what has to be prepared.
-  one image size
- adding captions to be able to connect to the corresponding text passage and
- merge different views into one image.



![not merged](https://cloud.githubusercontent.com/assets/13978063/11442506/3ad3f1cc-9516-11e5-94b7-7b672bef8f9c.PNG)
