### ISSUE TITLE
facsimile overlay: left click to show and hide

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#400]
In the facsimile view, click the transcription overlay to toggle between displaying the overlay

**Comment by gerritbruening** [comment]
In the seminar of ABR and me the following UI behavior was discussed:
- hover above a line --> single line displayed
- (first) click on a line --> all lines displayed
- (second) click on a line --> overlay disappears

The button would not be used anymore and could be dropped.

**Comment by thvitt** [comment]
in the last f2f meeting, we discussed that we should start with the overlay visible since it wouldn’t be discovered otherwise (esp. true with mouseless environments like tablets …)

would also follow from the _visibility_ usability principle
