### ISSUE TITLE
footer links

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#41]
Maybe "Impressum" can be remove within the footer, because it is visible in the top menu.

Additionally i would suggest to place "Ausgabe" which is linked to ```intro.php```. Actually there is only one link on the homepage to this content.

**Comment by thvitt** [comment]
@gerritbruening, was soll denn nun links unten stehen? »Faustedition«? »Digitale Faust-Edition«? »Faust-Edition«?

**Comment by sbruemmer** [comment]
oder wie vorgeschlagen "Ausgabe"...

**Comment by gerritbruening** [comment]
Nehmen wir vorläufig "Faust-Edition", dann ist es konsistent mit dem Tabtitle.
