### ISSUE TITLE
Anzeige des falschen Textabschnitts beim Klicken auf das Fragezeichen

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#410]
Im Seminar trat das Problem auf, dass nicht auf den richtigen Textabschnitt verlinkt wurde.
Wir waren in der Genese in der Gesamtübersicht und ein Klick auf das Fragezeichen führte zu "Balkendiagramm zu einzelnen Szenen".

Ich habe versprochen, das hier anzusprechen,
allerdings konnte ich den Fehler jetzt an meinem eigenen PC nicht rekonstruieren.
Laienhafte Vermutung: Möglicherweise liegt es an der Bildschirmgröße, sodass der Zielpunkt oberhalb des Bildschirms liegt?

**Comment by thvitt** [comment]
ich verstehe die Fehlermeldung nicht.

Auf welcher Seite genau wurde auf was für ein Fragezeichen geklickt und wo ist die betreffende Person gelandet? Die Seminarteilnehmer mögen bitte nach möglichkeit die genauen Adressen aus der Adresszeile des Browser kopieren …

Geht es um das Hilfesymbol in der Titelleiste? Das springt entsprechend dieser Regeln in die Infotexte:

https://github.com/faustedition/faust-gen-html/blob/ec49a1a5c5589ddb3bdb5d4c189f74122ec91b05/xslt/text-insert-app.xsl#L32-L62

Bis #353 gelöst ist ist dabei die eigentliche Zieladresse i.A. ein bissl von der Kopfzeile verdeckt, d.h. man muss auf der Intro-Seite ggf. 1–2 Zeilen nach oben scrollen.

**Comment by sandrakrause** [comment]
Tut mir leid, dass das unklar ausgedrückt war.
Ja, es war das Hilfesymbol in der Titelleiste. Statt zu intro#genesis führte es zu intro#genesis_part.
Zumindest optisch. Gut möglich, dass es nur verdeckt war.
Da die genaue Zieladresse jetzt nicht mehr ermittelt werden kann und ich es auch nicht mehr reproduzieren kann, hat sich das hier erstmal erledigt.
