### ISSUE TITLE
display "Faust" (instead of "Zueignung") in breadcrumb for overall text view 

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-web#413]
present state looks like the following:

![gesamt](https://user-images.githubusercontent.com/26788529/40130296-e71fd144-5936-11e8-95cf-7e894a819f58.JPG)

**Comment by gerritbruening** [comment]
part of #521

**Comment by gerritbruening** [comment]
This was discussed f2f on April 16, 2018:
> -	Breadcrumbs: Zwischenebene „Faust“
> -	print/faust –> Breadcrumb „Faust“
