### ISSUE TITLE
misdirection from apparatus siglum D4 to bibliography entry D4.alpha

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-web#425]
![2385](https://user-images.githubusercontent.com/26788529/40877849-b1bae242-6687-11e8-877f-ddbd0555ac01.JPG)

Wenn man in der Textansicht bei 2385 im Apparat rechts auf "D4" klickt wird man  zu Bibliographie D4.alpha, statt zu D4 geleitet.

![d4a](https://user-images.githubusercontent.com/26788529/40877859-e0dbbe84-6687-11e8-919e-4efa3ced1bf5.JPG)

**Comment by thvitt** [comment]
Duplicate of #353 – if you scroll up a little, you’ll see that D.4 is marked, not D.4α
