### ISSUE TITLE
dev broken in Firefox?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#428]
dev does not load in Firefox.
Index page:
![grafik](https://user-images.githubusercontent.com/10358005/41089747-dd2af6ba-6a42-11e8-97fe-3d46f0550f8a.png)

**Comment by thvitt** [comment]
Cannot reproduce this. Additionally, there have been no recent changes to the title page. Could you look into the browser console (Ctrl+Shift+K) and copy any message from there?

**Comment by gerritbruening** [comment]
Problems in Chrome now, too:
![grafik](https://user-images.githubusercontent.com/10358005/41090540-cdbbde72-6a44-11e8-93e7-59782616ce5f.png)

**Comment by gerritbruening** [comment]
![grafik](https://user-images.githubusercontent.com/10358005/41090624-fbdc9986-6a44-11e8-87ee-e529aeba8f89.png)

**Comment by gerritbruening** [comment]
heißt, ich kann heute nicht vernünftig arbeiten

**Comment by thvitt** [comment]
“Service unavailable” ist eine Serverfehlermeldung (503). Da mit dem faustedition.net-Server alles OK ist, ist vermutlich euer Proxy kaputt?

Ich sehe jedenfalls keine Handlungsmöglichkeit meinerseits ☹

**Comment by gerritbruening** [comment]
Ja, ist heute denn halt Pech.

**Comment by gerritbruening** [comment]
Danke fürs Draufschauen!
