### ISSUE TITLE
"Gesamtansicht" and {next / previous scene} buttons lead to structure view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#432]
For example, if you click on "Gesamtansicht"
* http://dev.faustedition.net/document?sigil=2_I_H.0a&page=1&view=print
* or http://dev.faustedition.net/document?sigil=2_H&page=11&view=print&section=2#scene_2.1.2

Same happens if you click on next or previous scene's name.

**Comment by thvitt** [comment]
since we probably don’t want to force-jump from, e.g., facsimile_text to text view, it’s probably best to solve this in the web component and try to take the last view setting when there is no explicit view parameter in the URL.

**Comment by gerritbruening** [comment]
Good, thanks!
