### ISSUE TITLE
Link Gräf, Pniower etc. in testimony table and text view to bibliography

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#433]
Right now, it is hard to understand what "Gräf", "Pniower" etc. mean.
We could have
* a tooltip in the header of the table
* a link from these names in the testimony text view

**Comment by thvitt** [comment]
yes we should, please provide bibliography links

**Comment by gerritbruening** [comment]
- [x] Pniower = http://dev.faustedition.net/bibliography#pniower1899
- [x] Gräf = http://dev.faustedition.net/bibliography#graef1901-1914_II_2
- [ ] Biedermann³ = problematic because multi-volume. We don't have any of them in the bibliography yet.
- [ ] QuZ = multi-volume, http://dev.faustedition.net/bibliography#quz_1 ff.
- [ ] tbc

**Comment by dietmarpravida** [comment]
tbc? wtf?

**Comment by gerritbruening** [comment]
> tbc

refers to any numbering system that is referred to from the subpages. If there is no such additional numbering system, um so better.

**Comment by dietmarpravida** [comment]
Wird bei Biedermann³ zwischen Teilband 3.1 und 3.2 unterrschieden? Haben wir das in den Daten oder nicht?
