### ISSUE TITLE
Act level is missin in breadcrumbs

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#438]
![grafik](https://user-images.githubusercontent.com/10358005/41580788-66032d74-739c-11e8-9ee4-3f709744b1b4.png)
 
(http://dev.faustedition.net/document?sigil=2_H&page=201&view=facsimile_text#l8347)

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/commit/b1489618c453b0f8f6f04b22ae7f298b64b93118

**Comment by gerritbruening** [comment]
Great, thanks!
