### ISSUE TITLE
Font name confusion

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-web#439]
When web font loading is [enforced](https://github.com/faustedition/faust-gen/blob/1a0834a54060721b947c47ee9fe156aa5f09cac3/svg_rendering/page/js-gen/transcript-configuration-faust.js#L65
) in diplomatic transcript generation (faust-gen), the font loader will throw the following error

    Error: web font could not be loaded: Ubuntu n4
    Error: web font could not be loaded: Ubuntu Monospace n4
    Error: web font could not be loaded: Gentium Plus n4

This is because in [webfonts.css](https://github.com/faustedition/faust-web/blob/e7459735f07fa485d03243d42b5015c09bb085b7/css/webfonts.css#L16), the font definition for the modified Ubuntu font uses the font-family name "Ubuntu", but in the actual font files (UbuntuFaust.tff, .woff, .woff2), the font family name is "Ubuntu derivative Faust".

    @font-face {
      font-family: 'Ubuntu';
      src: url(../webfonts/UbuntuFaust.woff2) format('woff2')

This is invalid. Note that in webfonts.css, there is a second set of definitions using UbuntuFaust.woff2 with the correct font family name "Ubuntu derivative Faust" 

    @font-face {
      font-family: 'Ubuntu derivative Faust';
      src: url(../webfonts/UbuntuFaust.woff2) format('woff2'),

Maybe this was an attempt to create an alias, so that both "Ubuntu" and "Ubuntu derivative Faust" refer to the modified font. As I understand it now, it doesn't work that way. The font family name in the .woff/.ttf and the .css file have to be the same. Ideally, the .woff/.tff file name should also reflect that verbatim, because then you don't need to use a font editor to see the actual name.

We also ship the unmodified Ubuntu font. That leaves us with three possibilities:

A. Have separate font definitions for "Ubuntu" and "Ubuntu derivative Faust" and use them appropriately in the CSS. CONs: We would need to change the CSS to "Ubuntu derivative Faust" in most(?) places. 

B. Only use the modified font as "Ubuntu derivative Faust", since it is a superset of the original Ubuntu font (?). CONs: We would need to change every reference from "Ubuntu" to "Ubuntu derivative Faust".

C. Only use the modified font as "Ubuntu". PRO: We could keep our references to "Ubuntu". CON: It is not really correct to refer to that font as "Ubuntu", and someone in the future might replace it with the normal Ubuntu font without noticing, or the system might use the system-installed font, etc.

I personally think option B is the best choice. @thvitt, what are your thoughts? Am I missing something? I am not very familiar with the intricacies of web font embedding, this is just what I understand from digging a little into that error.

**Comment by wissenbach** [comment]
On second thought, I think option A is best, it can't hurt do ship the original font in case we miss some reference. It is baked into some SVGs, for example.

**Comment by thvitt** [comment]
the awkward name is a consequence of how I read the [font license](https://www.ubuntu.com/legal/terms-and-policies/font-licence).

If we ship both fonts this will further increase the download size of each page. Impact depends on whether the browsers download the fonts when they encounter the `@font-face` or only when the font is actually used

**Comment by wissenbach** [comment]
I thought it would be about legal stuff when I read the name. There must be some convention for the relationship between font-family name (with spaces) and file name (camel case), so maybe "Ubuntu Derivative Faust" and UbuntuDerivativeFaust.ttf, I'll see if I find something.

So do I have your ok to change all the names? I will try to get all the references, but if something doesn't look right, you know where it came from :)

**Comment by thvitt** [comment]
:+1:

**Comment by wissenbach** [comment]
Note: The font family definitions for "Ubuntu derivative Faust" Bold and Bold,Italic have been referencing the unmodified Ubuntu font. Not sure if this was on purpose or oversight. I'm not familiar with the state of the modified font. I'm changing it as well.

**Comment by thvitt** [comment]
oversight. There’s a script somewhere that detects all characters and lists it with the characters actually present in the various fonts, I intend to use that before the next release in order to check for any characters still missing in some of the fonts (hm, it won’t detect missing anchor pairs (as required for m̄) though)

**Comment by wissenbach** [comment]
#138 would be the relevant issue, I suppose. I'm never really sure how those fallback mechanisms work, i.e. on a per-glyph basis? Do you know if the custom glyphs are added to all the different styles (bold, italic, bold italic)?

**Comment by wissenbach** [comment]
I have changed the css font definitions and references in `faust-web`, `faust-gen`, `faust-html`

**Comment by thvitt** [comment]
The fonts are not consistent wrt. the missing glyphs, this needs to be done. I would prefer to add them en bloc some time, and I would also like to check first which of the characters is really required and whether we need them in all fonts (bold-face is rarely used …).
