### ISSUE TITLE
QuZ und Biedermann erklären

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#450]
Damit wird in den Entstehungszeugnissen operiert, aber die Kürzel werden nirgendwo erklärt oder nur indirekt, wenn man die Bibliographie findet.

**Comment by sandrakrause** [comment]
Es wäre auf jeden Fall auch sinnvoll, in den Reitern der Tabelle bei QuZ und Biedermann³ auch einen Link zur Bibliographie zu setzen, wie es bei Gräf und Pniower auch getan wurde.
Da Biedermann³ nicht in der Bibliographie verzeichnet ist, könnte es aber selbst dann noch schwierig sein, das zu verstehen (besonders weil die Verweisnummern ja auch als Biedermann/Herwig angegeben sind).
Muss man überlegen, ob im Erklärungstext dann auf Biedermann1 verlinkt werden soll oder ob man es vielleicht doch noch ergänzt (ich kenne die Gründe für das Nicht-Aufnehmen jetzt nicht).

Hier erste Entwürfe zur Erweiterung des Erklärungstextes in "Über die Ausgabe":
Bisher:
`Die Dokumente zur Entstehung des ‚Faust‘ versammeln alle bislang bekanntgewordenen Äußerungen Goethes und anderer Zeitgenossen, die sich auf den ‚Faust‘ beziehen lassen, in Briefen, Tagebuch- und Gesprächsaufzeichnungen und weiteren schriftlich überlieferten Dokumenten. Der Bestand der mehr als 1500 Zeugnisse integriert die früheren Sammlungen von [Otto Pniower (1899)](http://dev.faustedition.net/bibliography#pniower1899) und [Hans-Gerhard Gräf (1904)](http://dev.faustedition.net/bibliography#graef1901-1914_II_2) und ergänzt sie um erst seither publizierte Dokumente. Die Dokumente sind nach Möglichkeit als vollständige Texte verfügbar, die jeweils ‚Faust‘ betreffende Passage wird auszugsweise in der Tabelle der Zeugnisse angezeigt, die zugleich die wichtigsten Angaben wie Datum, Verfasser, Adressat, Verweis-Nummern enthält.`

Version 1:
[...] Der Bestand der mehr als 1500 Zeugnisse integriert die früheren Sammlungen von [Otto Pniower (1899) ](http://dev.faustedition.net/bibliography#pniower1899)und [Hans-Gerhard Gräf (1904)](http://dev.faustedition.net/bibliography#graef1901-1914_II_2). Ergänzt werden sie um die von [Woldemar Freiherr von Biedermann](http://dev.faustedition.net/bibliography#biedermann1889-1896_1) angelegte Sammlung von Gesprächsberichten, die 1965-1987 von Wolfang Herwig ergänzt und neu herausgegeben wurde (Biedermann³). Ebenfalls ergänzt wurden Dokumente und Zeugnisse aus „[Quellen und Zeugnisse zur Druckgeschichte von Goethes Werken](http://dev.faustedition.net/bibliography#quz_1)“ (QuZ). Das vierbändige Werk, das 1966-1984 herausgegeben wurde, enthält/verzeichnet weitere Entstehungszeugnisse, die in den früheren Sammlungen noch nicht bekannt waren. [...]

Version 2:
[...] Der Bestand der mehr als 1500 Zeugnisse integriert die früheren Sammlungen von [Otto Pniower (1899)](http://dev.faustedition.net/bibliography#pniower1899) und [Hans-Gerhard Gräf (1904)](http://dev.faustedition.net/bibliography#graef1901-1914_II_2). Ergänzt werden sie um die von [Woldemar Freiherr von Biedermann](http://dev.faustedition.net/bibliography#biedermann1889-1896_1) angelegte Sammlung von Gesprächsberichten, die 1965-1987 von Wolfang Herwig ergänzt und neu herausgegeben wurde (Biedermann³). Ebenfalls ergänzt wurden später publizierte Dokumente und Zeugnisse, die im vierbändigen Werk „[Quellen und Zeugnisse zur Druckgeschichte von Goethes Werken](http://dev.faustedition.net/bibliography#quz_1)“ (QuZ) verzeichnet sind. [...]


Version 3:
[...] Der Bestand der mehr als 1500 Zeugnisse integriert die früheren Sammlungen von [Otto Pniower (1899)](http://dev.faustedition.net/bibliography#pniower1899) und [Hans-Gerhard Gräf (1904)](http://dev.faustedition.net/bibliography#graef1901-1914_II_2). Ergänzt werden sie um die von [Woldemar Freiherr von Biedermann](http://dev.faustedition.net/bibliography#biedermann1889-1896_1) angelegte Sammlung von Gesprächsberichten, die 1965-1987 von Wolfang Herwig ergänzt und neu herausgegeben wurde (Biedermann³). Ebenfalls ergänzt wurden später publizierte Dokumente aus „[Quellen und Zeugnisse zur Druckgeschichte von Goethes Werken](http://dev.faustedition.net/bibliography#quz_1)“ (QuZ). Das vierbändige Werk, das 1966-1984 herausgegeben wurde, enthält weitere Entstehungszeugnisse, die in den früheren Sammlungen noch nicht bekannt waren. [...]

**Comment by thvitt** [comment]
heißt der Herwig echt Wolfang ohne g nach dem f?

**Comment by sandrakrause** [comment]
@gerritbruening
Kann ich gerne machen. Welche Datei ist das genau und wo finde ich sie?
@thvitt
Danke für den Hinweis. Er heißt natürlich Wolfgang, da hat sich ein copy&paste-Fehler eingeschlichen

**Comment by gerritbruening** [comment]
Die Datei liegt in faust-web und heißt genauso wie die Seite, also der Teil nach dem Slash.

**Comment by sandrakrause** [comment]
Habe den Abschnitt mit Links ergänzt.

**Comment by dietmarpravida** [comment]
ich sehe da leider keine Links

**Comment by dietmarpravida** [comment]
cf #446

**Comment by gerritbruening** [comment]
> ich sehe da leider keine Links 

http://dev.faustedition.net/intro#testimony
(war das die Frage, wo das steht?)

**Comment by dietmarpravida** [comment]
(hier http://dev.faustedition.net/archive_testimonies, meine ich)

**Comment by gerritbruening** [comment]
OK, aber ist das hier:
http://dev.faustedition.net/intro#testimony
so OK?

**Comment by thvitt** [comment]
* der Link auf Biedermannallerley ist noch kaputt
* ist faust://bibliography/biedermann1965-1987_1 das richtige, wo’s doch Biedermann³ heißt?

**Comment by dietmarpravida** [comment]
äh, da brauchten wir wohl auch einen Obertitel, biedermann1965-1987_1 wäre nur der erste Band (von Biedermann3)

**Comment by sandrakrause** [comment]
> ist faust://bibliography/biedermann1965-1987_1 das richtige, wo’s doch Biedermann³ heißt?
Ja, Biedermann1965-1987 ist Biedermann³. Da es keinen "allgemeinen" Link gibt, wollte ich auf den ersten Band verlinken.

**Comment by gerritbruening** [comment]
> "und anderer Zeitgenossen" würde ich weglassen, da sind wir nicht besonders komplett

nur

    alle
    bislang bekanntgewordenen Äußerungen Goethes

finde ich aber zu einschränkend

**Comment by gerritbruening** [comment]
> der Link auf Biedermannallerley ist noch kaputt

Habe ich repariert, BTW finde ich aber
https://github.com/faustedition/faust-web/commit/5c866d9b6826d550d7e45be066a6dae5ca4a5a1d#diff-9ba6cf478ec657197790d4b98683eb6cR105
immer noch doppelt gemoppelt.
Brauchen wir `data-bib-uri` neben `href`?

**Comment by dietmarpravida** [comment]
"alle bislang bekanntgewordenen Äußerungen Goethes sowie die wichtigsten für die Entstehungsgeschichte einschlägigen Zeugnisse anderer Zeitgenossen"?

**Comment by gerritbruening** [comment]
> Da es keinen "allgemeinen" Link gibt, wollte ich auf den ersten Band verlinken.

Wollten wir nicht eine URI für den Obertitel anlegen?

**Comment by thvitt** [comment]
@sandrakrause ich find erster band ok, war nur verwirrt
@gerritbruening data-bib-uri kann von einem skript ausgelesen werden, da nur zitierte quellen in die bibliographie aufgenommen werden (war mal featurewunsch)

**Comment by gerritbruening** [comment]
> "alle bislang bekanntgewordenen Äußerungen Goethes sowie die wichtigsten für die Entstehungsgeschichte einschlägigen Zeugnisse anderer Zeitgenossen"?

ist eingesetzt

**Comment by dietmarpravida** [comment]
bitte "von Zeitgenossen", "anderer" ist schräg

**Comment by gerritbruening** [comment]
>  @gerritbruening data-bib-uri kann von einem skript ausgelesen werden, da nur zitierte quellen in die bibliographie aufgenommen werden (war mal featurewunsch)

D.h.,  `href="bibliography#xyz` sorgt noch nicht dafür, dass xyz in `bibliography` auftaucht?

**Comment by thvitt** [comment]
ja, warum jab ich das damals eigentlich nicht so gebaut?
