### ISSUE TITLE
Makrogenese-Lab inkl. chronologische Sortierung beschreiben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#452]
> die Siglen der Zeugen in chronologischer Folge von unten nach oben. Explizit macht das Diagramm nur Angaben zur chronologischen Ordnung von Fassungen, die gemeinsamen Text aufweisen.

Das steht seit längerem so da, stimmt aber erst jetzt und nur zum Teil.
Erklärt werden muss das Verfahren, durch das die Makrogen-Ansichten und die Sortierung von Balken und Varianten zustandekommen.
Inhaltlicher Vorlauf
- [x] welche Forschung berücksichtigt? (warum?)
- [x] wie wurde damit umgegangen? (u.a. Interpretation und Normalisierung in Richtung eindeutig definierter Zeitintervalle
Maschinelle Verarbeitung:
- [x] Ziel: Bildung einer "transitiven Hülle" oder dergleichen (?)
- [x] Gewichtung der Forschungsposition (inkl. Addition bei identischen Aussagen)
- [x] graphische Repräsentation

**Comment by dietmarpravida** [comment]
wo steht das?

**Comment by gerritbruening** [comment]
Könnten wir das heute (Freitag) zusammenschreiben? Der Text muss ja ohnehin sehr kurz sein, und es wäre gut, wir könnten ihn mit `hrsg` abstimmen. Interessiert sie.

**Comment by gerritbruening** [comment]
Danke!
Ich habe jetzt die `intro`-Seite aufgebohrt und auf `intro_macrogenesis` verlinkt.

**Comment by gerritbruening** [comment]
Ich habe meine Bearbeitung jetzt abgeschlossen bitte v.a. @thvitt um einen prüfenden Blick.
