### ISSUE TITLE
pb in testimony-Ansicht

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#454]
Z.B. „Frei 64heitsgesangs“ in http://dev.faustedition.net/testimony/pniower_26.
Es sollte vmt. ein | oder so stehen.

**Comment by thvitt** [comment]
So besser?

**Comment by gerritbruening** [comment]
> So

= Frei&nbsp;heitsgesangs?

**Comment by thvitt** [comment]
wo das leerzeichen nun wieder herkommt … 
pniower_26.xml hat
```xml
                    Exemplar meines Frei<pb n="64" facs="janssen1877_1_0064-0065.jpg"/>heitsgesangs
```

**Comment by thvitt** [comment]
hm, can I actually _not_ insert a space char on page breaks? shouldn’t this be a `<pb break="no"/>`?

**Comment by gerritbruening** [comment]
Yes!

**Comment by thvitt** [comment]
I vaguely remember we discussed that …

Anyway, I’ve prepared for the upcoming break='no', assign me again when there’s something I need to do here.

**Comment by sandrakrause** [comment]
I added the "break=no" in pniower_26.

I think the break=no problem was discussed here: https://github.com/faustedition/xml/issues/40

**Comment by thvitt** [comment]
naja, dann muss wohl mal das andere Issue beheben …
