### ISSUE TITLE
Remove 1st and 3rd column in archives_print

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#46]

**Comment by thvitt** [comment]
Gerrit,

* http://GSA_32_1420 (J) appears to be missing a _faustedition_ sigil
* Would it be possible to copy/move the prints' descriptions into their
respective `<headNote>`?

  -tv

**Comment by gerritbruening** [comment]
* Have added J.1 in xml/document/print/seckendorff1782.xml which contains http://GSA_32_1420's metadata.
* The descriptions already seem to be there as &lt;headNote>s, except for the full stop.
