### ISSUE TITLE
1 H.1 S. 219 @facs korrigieren

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#461]
https://github.com/faustedition/faust-gen-html/issues/561#issuecomment-409962141

http://dev.faustedition.net/document?sigil=1_H.1&page=219&view=facsimile

> Fehler beim Laden der Facsimile-Metadaten Error: Failed to load transcript/facsimile/metadata/print/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I/D20121107-217.json, error: Not Found

Die meisten anderen Seiten von 1 H.1 gehen

**Comment by thvitt** [comment]
das Problem ist, dass im Transkript das Facsimile als `D2012-1107-217.tif` codiert ist, die beiden vorliegenden Bilder jedoch …-217[a](http://dev.faustedition.net/transcript/facsimile/jpg/print/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I/D20121107-217a_1.jpg) und …-217[b](http://dev.faustedition.net/transcript/facsimile/jpg/print/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I/D20121107-217b_1.jpg) heißen (mit Aufklebung hoch/runtergeklappt)

**Comment by gerritbruening** [comment]
Danke!
Habe jetzt
`<pb facs="D20121107-217a.tif D20121107-217b.tif" n="217"/>` reingeschrieben.

**Comment by gerritbruening** [comment]
Läuft!
