### ISSUE TITLE
annotate absolute datings in the genetic bargraph

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#475]

**Comment by gerritbruening** [comment]
Great to see datings!
But are these datings really real?:
http://dev.faustedition.net/genesis_bargraph?rangeStart=1&rangeEnd=32
It seems as if these absolute datings are inferred from relative ones, but it is confusing.

**Comment by gerritbruening** [comment]
Yes, but 
![grafik](https://user-images.githubusercontent.com/10358005/45258667-c890f700-b3bb-11e8-8dd8-b63947e9daaf.png)
is confusing.
General editors might infer that there are blatantly false explicit datings in our data. What do you thin, @dietmarpravida ?

**Comment by thvitt** [comment]
Isn’t the problem that we don’t have absolute datings for the prints in our data yet? Which we decided to fix?

**Comment by thvitt** [comment]
we could also think of marking inferred data (e.g., in parentheses), although this information isn’t in place yet.

**Comment by gerritbruening** [comment]
> Isn’t the problem that we don’t have absolute datings for the prints in our data yet? Which we decided to fix?

Yes, see https://github.com/faustedition/xml/issues/605 now.

**Comment by thvitt** [comment]
ok, wenn das geändert werden soll, neues issue
