### ISSUE TITLE
Fehlerhafte Darstellung Sonderzeichen im Intro-Text

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#480]
Ist wohl irgendwas schief gelaufen bei/nach diesem Commit:
https://github.com/faustedition/faust-web/blob/9d801e05a71bff067406dad69c897fe4a0f2999f/intro.php

**Comment by thvitt** [comment]
ja supi, jetzt haben wir die feinste Mojibake in der Datei und sogar im Patch. @gerritbruening , bitte unbedingt beim Bearbeiten aufs Encoding achten. Alle unsere Dateien sind UTF-8 und nicht irgendein Windows-Codepagezeugs; du musst doch gesehen haben, dass vor und nach deiner Einfügung Zeichensalat in der Datei steht … Im Oxygen unter Encoding UTF-8 überall einstellen. Dieser Kram ist echt nervig zu reparieren.

**Comment by thvitt** [comment]
argl da ist noch mehr müll drin in der datei

**Comment by gerritbruening** [comment]
Korrekt, ich schreibe in Word und füge dann in Oxygen ein.
Aber beim Commit sah alles OK aus:
![grafik](https://user-images.githubusercontent.com/10358005/45823156-5ee2e800-bced-11e8-903f-8d3e6a56403b.png)

**Comment by gerritbruening** [comment]
Es stimmt schon,
> vor und nach deiner Einfügung Zeichensalat in der Datei 

Aber die Zeichendarstellung in GitGui sieht immer komisch aus, das war nichts neues.

**Comment by thvitt** [comment]
du musst in Oxygen auf das Encoding achten. Word hat damit ausnahmsweise nichts zu tun

**Comment by thvitt** [comment]
ja genau, da wo du in der obersten Zeile Cp1252 stehen hast muss UTF-8 hin

Cp1252 is böse

**Comment by gerritbruening** [comment]
Ach, das wusste ich nicht. Danke fürs auf den rechten Weg bringen. Sorry für die entstandenen Unannehmlichkeiten.

**Comment by gerritbruening** [comment]
OK, danke, habe ich gemacht. Komisch, dass das erst jetzt solche unangenehmen Folgen hatte.
