### ISSUE TITLE
Reconsider "Aufbewahrungsorte"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#484]
Im Seminar ABR-GB wurde diskutiert, dass sie als Kategorie neben den Objekttypen als Kategorie seltsam wirken.
Ist es berechtigt, die Drucke bei den Aufbewahrungsorten zu ignorieren? Wahrscheinlich schon.

**Comment by thvitt** [comment]
wenn sie mit dazu dürften, wäre auch 1 H.1 mit dabei 😁
