### ISSUE TITLE
archive_locations: Deal with repositories that have no manuscripts

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#487]
BSB is present since they have a print, but their manuscript & page count shows as 'undefined' now. Either consider prints there (#484), or remove archive locations w/o manuscripts from the list.

**Comment by gerritbruening** [comment]
At least, archives that appear because of `furtherCopy` only should be ignored.

**Comment by thvitt** [comment]
currently, archives appear since they are in archives.xml …
