### ISSUE TITLE
Rename "archives" to "archive"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#49]
Applies to
* http://beta.faustedition.net/archives.php
* http://beta.faustedition.net/archives_locations.php
* http://beta.faustedition.net/archives_print.php
There are "archives" in the sense of specific locations (Goethe- and Schiller-Archiv etc.), but in the Faustedition, it is all *one* virtual archive.

**Comment by sbruemmer** [comment]
Applies also to
 * http://beta.faustedition.net/archive_locations_detail.php
 * http://beta.faustedition.net/archives_manuscripts.php

Renamed <code>archives_print.php</code> to <code>archive_prints.php</code>. The plural for "prints" matches the pattern of the other archive pages..

See

**Comment by sbruemmer** [comment]
Please adapt to /print
