### ISSUE TITLE
Title for watermark-table

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#492]
Until now the header of the page is blank:
![grafik](https://user-images.githubusercontent.com/10358005/46134817-132bc380-c244-11e8-81f5-1664dc007df3.png)

**Comment by thvitt** [comment]
What should be the breadcrumb content?

**Comment by gerritbruening** [comment]
Do we need one?
We don't have breadcrumb on parallel pages `x-ray_spectrometry` and `multispectral_imaging`.

**Comment by thvitt** [comment]
we should. they are linked from somewhere, aren’t they?

**Comment by gerritbruening** [comment]
Agree, then "Ausgabe" like in
![grafik](https://user-images.githubusercontent.com/10358005/46149314-500ab100-c26a-11e8-81a4-67327fec8a79.png)
