### ISSUE TITLE
Avoid links on help

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#494]
IIRC @thvitt was optimistic about some form of help overlay (#25). But is this still feasible? A good provisional solution would be to make all pages' question mark button lead to some info text. For example, the one on `watermark-table` could link to http://dev.faustedition.net/watermarks.

**Comment by gerritbruening** [comment]
Wenn ich http://dev.faustedition.net/text bin, wieso zeigt Fragezeichen nicht `intro#text`?

**Comment by thvitt** [comment]
ergänzich grad

**Comment by thvitt** [comment]
was ist gegenstand dieses issues? :confused:

**Comment by gerritbruening** [comment]
Könnte sich erledigt haben, da `/help` auf `/intro` weiterleitet.
Es ging um Seiten, deren Fragezeichen auf die construction site Seite verlinkt statt auf Info-Texte. Kann sein, dass es solche Seiten jetzt nicht mehr gibt. Dann gern closen.
