### ISSUE TITLE
Correct link within document metadata

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#50]
Change from <code>archiveDetail.php?archiveId=</code> to <code>archives_locations_detail.php?id=</code>

Example: [2 H](http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=5&view=structure)

**Comment by gerritbruening** [comment]
I would prefere <code>location_detail.php</code>

The pages contain details for only one location.

**Comment by sbruemmer** [comment]
The naming of the files is oriented on the navigational structure. Thus it shows a kind of hierarchiy:
 1. Archive: <code>archive.php</code>
 2. Archive > Locations: <code>archive_locations.php</code>
 3. Archive > Locations > Detail: <code>archive_locations_details.php</code>

**Comment by gerritbruening** [comment]
OK, agree!

**Comment by thvitt** [comment]
fixed in https://github.com/faustedition/faust-gen-html/commit/7c87745f11950b71e3fb7aa668c68d501398ae7c
