### ISSUE TITLE
Make line reference in app entries grey and maybe smaller

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#500]
![grafik](https://user-images.githubusercontent.com/10358005/46408802-a74dcd00-c713-11e8-9b40-670b8eebbc62.png)

What I bother about is the difference between verse lines on the left margin and the ones in app entries. They should look similar.
Maybe the line reference in app entries should even appear in italics, as they do in the printed volume and just like the other editorial text does.
What do you both think?

**Comment by thvitt** [comment]
das sah doch schonmal gut aus

**Comment by gerritbruening** [comment]
Ja, sehr gut, danke!
