### ISSUE TITLE
ToC for intro_text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#509]
@thvitt, hast du eine Meinung, wie das aussehen sollte? Zur Not einfach `ul` mit `li`? Ich mag nur die vielen bullet points nicht so sehr. Aber wenn es einen halbwegs einfachen und optisch passablen Weg gibt, kann ich mich gern daran versuchen.

**Comment by thvitt** [comment]
Ich würde vorschlagen einfach mit ul und li und dann ein `<nav class="toc">` drumherum. Dann können wir das beliebig per CSS stylen und auch die Bulletpoints entfernen (oder durch etwas fancy ☛ ersetzen). 

Soll ich irgendwas liefern?

**Comment by thvitt** [comment]
mach ich dann

**Comment by thvitt** [comment]
muss da noch was geschehen? (im telefonat meinte ich allerdings nicht intro_text, sondern das ganze; aber das haben wir im grunde verworfen; ich bin glaub ich mit der sitemap einfach unzufrieden.)

**Comment by gerritbruening** [comment]
Nein, ist erstmal OK so, ich muss am Ende evtl. Überschriften rausschmeißen.
