### ISSUE TITLE
Remove document headline from metadata

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#51]
Remove <code>&lt;h2&gt;1 H.6&lt;/h2&gt;</code> in the right column. This is shown in the breadcrumb.

Example: [1 H.6](http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/archival/gsa/GSA_24-15-1.xml&page=52&view=structure)

**Comment by gerritbruening** [comment]
We have discussed this and resolved that the sigil is a kind of heading to the following text and should remain. This is not the case for "Archiv" and so on in http://beta.faustedition.net/archives.php and so on.
