### ISSUE TITLE
resolve link leading to B in archive_manuscripts

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-web#510]
![manusc](https://user-images.githubusercontent.com/26788529/46573368-6b756a80-c994-11e8-95b9-0cd267efc558.JPG)

**Comment by dietmarpravida** [comment]
viel hilft viel (fällt mir aber zum erstenmal auf)

**Comment by thvitt** [comment]
steter tropfen höhlt den informatiker? dann aber nicht 1.0 assignen ist inkonsequent :-)

**Comment by dietmarpravida** [comment]
gutta cavat computarium
