### ISSUE TITLE
Adjust height of "Entstehungszeugnisse" within genesis entry

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#514]
With the new genesis entry (see 769b786) there is now a bargraph of "Entstehungszeugnisse" added. Each year will show the amount of certain documents.

![entstehungszeugnisse](https://user-images.githubusercontent.com/13978063/46600132-87d6eb80-cae9-11e8-8395-736aa75df64d.jpg)

To adjust the height every single element can be targeted via an **id-attribute**: See [genesis_entry.svg](https://github.com/faustedition/faust-web/blob/769b786da33e7670387cf57f74dbe70202ad9c6d/img/genesis_entry.svg?short_path=7f888cc#L216)

**Comment by thvitt** [comment]
die Breite der Zeugen-Kästchen het keine Bedeutung, oder? ach nee, ist immer gleich, gut
