### ISSUE TITLE
Titel / preface of intro_text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#520]
- [x] Seitentitel kürzen
* <s>ausführlichen Titel als `h2`</s>
* <s>Autorschaft und Drucknachweis als ungezählte Fußnote, an `h2` anhängend.</s>

**Comment by gerritbruening** [comment]
So OK, @dietmarpravida?
Dann closen.

**Comment by dietmarpravida** [comment]
Die Vorbemerkung bitte zumindest in kleinerer Schrift, wenn ihr Inhalt schon nicht an den Rand gerückt wird. Aber den Literaturverweis könnte man doch nach rechts stellen? Dann kann auch der eine Satz normalgroß bleiben.
