### ISSUE TITLE
Tweak text entry

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#521]
-	Link auf editorischen Bericht (prominenter als das Fragezeichen)
-	Namen der Bearbeiter
- [ ] Button "Faust" --> "Konstituierter Text" (wegen Parallelität zu "Apparat")
- [ ] Auf Seite http://dev.faustedition.net/print/faust Hinweis auf responsibilities, z.B. am Rand, in der Form: Textkonstitution: ...

**Comment by gerritbruening** [comment]
` Faust | Apparat | Paralipomena` ist tatsächlich sehrt komisch.
Es hängt aber davon ab, was auf der Folgeseite http://dev.faustedition.net/print/faust im Breadcrumb stehen wird, und damit von #413 und damit von @thvitt.

**Comment by thvitt** [comment]
ja macht mal, ist in den php files im stammordner

am ende müssen wir dann noch das overlay-menü anpassen

**Comment by gerritbruening** [comment]
Finde ich sehr gut. Kleinen Link in die Runde?

**Comment by thvitt** [comment]
whatever

**Comment by gerritbruening** [comment]
> grundsätzlich in Ordnung
