### ISSUE TITLE
Eliminate "Lesetext"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#522]
- [x] irgendwo noch "Lesetext" in faust-web?

It appears, for example, in  search.

**Comment by gerritbruening** [comment]
I have removed "lesetext" from `faust-web`, but I am not sure about https://github.com/faustedition/faust-gen-html/search?p=2&q=lesetext&unscoped_q=lesetext. Most of the hits won't be visible, but some will.

**Comment by thvitt** [comment]
was soll’s sein? 'Text' überall?

**Comment by gerritbruening** [comment]
Text wär nicht falsch. Wo man unbedingt was längeres haben will, würde "Konstituierter Text" passen.

**Comment by thvitt** [comment]
suche muss noch hochgeladen werden, sonst sollte’s jetzt weg sein
