### ISSUE TITLE
Character entity reference for nbsp in info texts

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#532]
* `&nbsp;` seems to be canonic, but doesn't validate
* `&#160;` seems to be canonic, too, but was removed in https://github.com/faustedition/faust-web/commit/edb47080a268be4f2e9be28d2db58045a6ade3ba#diff-9ba6cf478ec657197790d4b98683eb6cL202

Instead, there is a ` ` there, but I can't tell whether this is a normal whitespace or not.

**Comment by thvitt** [comment]
- these are essentially XML files, and there are only 5 named entity references in XML files for `<>"'&`. 
- a non breaking space is a regular unicode character, so automatic processing that saves to utf-8 will usually rewrite `&#160;` to the corresponding ` `
- oxygen shows the codepoint for the character under cursor in its footer line (U+00A0 = non-breaking space), and it can also display space markers (search for space in the options dialog)
