### ISSUE TITLE
Idnos in line synopsis lead to scene beginning

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#540]
I go to
http://dev.faustedition.net/print/faust.30#l5000
and from there to
http://dev.faustedition.net/document?sigil=2_H&page=11&view=structure&section=2#l5000
But this is not where line 5000 is.
When I change view I am here:
http://dev.faustedition.net/document?sigil=2_H&page=11&view=document_text&section=2#l5000
But both views do no correspond to each other.
Is this an unintended side effect of something?

**Comment by thvitt** [comment]
jemand sollte wegen dem anderen problem (land straſe im urfaust) mal ’n issue aufmachen

**Comment by gerritbruening** [comment]
> jemand sollte wegen dem anderen problem (land straſe im urfaust) mal ’n issue aufmachen

https://github.com/faustedition/faust-gen-html/issues/620
