### ISSUE TITLE
intro_macrogenesis broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#541]

**Comment by thvitt** [comment]
was ist da broken?

**Comment by gerritbruening** [comment]
FF und Chrome zeigen mir keinen Seiteninhalt, nur den header.

**Comment by thvitt** [comment]
hier? http://faustedition.net/intro_macrogenesis sieht bei mir ein beiden Browsern gut aus.

**Comment by gerritbruening** [comment]
Bei mir jetzt auch, keine Ahnung was das war.

**Comment by gerritbruening** [comment]
Ah: `http://faustedition.net/intro_macrogenesis/` ist ein slash zu viel.
