### ISSUE TITLE
faustedition.de should redirect to faustedition.net

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#542]
When I enter `www.faustedition.de`, Firefox brings me to `http://beta.faustedition.net/`.
In other versions of Firefox `www.faustedition.de` redirects to `https://faustedition.uni-wuerzburg.de/`.
In any case, IE and Edge redirect to `https://faustedition.uni-wuerzburg.de/`, too.
Which brings up the following warning: 
![grafik](https://user-images.githubusercontent.com/10358005/46945561-6475e880-d075-11e8-823e-f85252d19475.png)

Not that `.de` is sometimes accidentally used, even in press material.

**Comment by thvitt** [comment]
Der Redirect http-Redirect von uni-wuerzburg sollte jetzt zu faustedition.net laufen, um faustedition.de bitte ich fotis.

**Comment by gerritbruening** [comment]
Sehr gut, funktioniert bei mir, danke!
