### ISSUE TITLE
Cookies ablehnen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#549]
Es wird, wenn ich das richtig verstehe, beklagt, dass man den Cookies nur zustimmen kann:
![grafik](https://user-images.githubusercontent.com/10358005/48965364-087b7980-efbc-11e8-8eee-bb7938975bc2.png)
Ist die Cookie Warnung auch ablehnbar zu gestalten? (https://www.cookiebot.com/de/cookie-hinweis/)

**Comment by gerritbruening** [comment]
Ach ne, ich kann ja [hier](http://faustedition.net/imprint#privacy) ablehnen. Also ist das zu closen, oder?
Oder kann man statt "weitere Informationen" etwas in den Link schreiben, was auf eine solche Option hinweist?

**Comment by thvitt** [comment]
Auf der Impressumseite kann man die Webanalyse ausstellen. Der Link 'Erfahren Sie mehr' im Cookiehinweis zeigt bereits dahin.

Cookies und ähnliche Daten (session storage) werden neben der Webanalyse potentiell noch von der Suchseite zum Caching der Einstellungen, vom DocumentViewer zum Caching der letzten besuchten Ansicht und künftig ggf. noch von der Suche zum Merken von Zwischenergebnissen benutzt; außerdem zum Merken, ob der Cookiehinweis schon akzeptiert wurde. Wenn der Benutzer das nicht will, möge er seinen Browser entsprechend konfigurieren. Eine Ablehnung müsste ja irgendwo gespeichert werden (in einem Cookie etwa).

Implementierbarer Featurewunsch ggf. dass bei deaktivierten Cookies der Hinweis nicht angezeigt wird.

Im Übrigen sind unsere Cookies soweit durchgebacken, dass sie nicht schleimen.

**Comment by gerritbruening** [comment]
OK, 
> Webanalyse ausstellen

heißt also nicht, dass keine Cookies gespeichert werden?
Fragen wir halt Herrn Stadelmaier, wie er es haben möchte.

**Comment by thvitt** [comment]
Das bezieht sich nur auf die Erfassung der Daten für unsere Webstatistik, ja. IIRC wird ein Cookie gespeichert, dass nicht getrackt werden soll. Prinzipbedingt muss ja irgendwas im Benutzerbrowser gespeichert werden, wenn die Seite sich irgendwas über mehrere Seitenaufrufe hin merken soll, ob nun Cookie oder Local Storage oder URL-Fragment. 

Die Webstatistik berücksichtigt allerdings ohnehin die entsprechenden Browsereinstellungen zum Tracking, und das wird auf der Impressumseite auch so angezeigt (besuche z.B. http://faustedition.net/imprint#privacy im privaten Modus von Firefox). 

Letztlich ist’s einfach: Wir schalten in der nächsten Version die Meldung nur auf, wenn jemand Cookies aktiviert hat, man kann ja ggf. noch einen Link zu einem Hinweis aufs Browserkonfigurieren unterbringen.

**Comment by thvitt** [comment]
Die Lösung sieht jetzt so aus, dass Benutzer, die Cookies in ihrem Browser ausgeschaltet haben, auch keinen Cookiehinweis bekommen, und alle anderen einen [etwas überarbeiteten](https://github.com/faustedition/faust-web/commit/a8581f272d7dd1852ac06e8aa16079f368af34c2). Wer die ausprobieren möchte, öffne http://dev.faustedition.net/ im Privaten Modus seines Browsers.

**Comment by gerritbruening** [comment]
Scheint mir grundsätzlich gut so.
Was man noch überlegen könnte, wäre #554.
