### ISSUE TITLE
release notes 1.1

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#550]
- [x] Bezug auf 2. Aufl.
- [x] Textverbesserungen
- [x] Transkriptionskorrekturen
- [x] Drucke Bilder
- [x] cookies
- [x] weitere fixes

[alle Änderungen](https://github.com/issues?q=is%3Aissue+org%3Afaustedition+sort%3Aupdated-desc+milestone%3A1.1+is%3Aissue&utf8=%E2%9C%93)

**Comment by thvitt** [comment]
@fotisj schlägt vor, dass bei jedem künftigen Release die Verantwortlichen i.S.v. derjenigen Personen, die etwas zu den Änderungen in diesem Release beigesteuert haben, genannt werden.

**Comment by gerritbruening** [comment]
Die aus meiner Sicht wichtigen Punkte stehen demnächst
http://dev.faustedition.net/1-1-release

**Comment by gerritbruening** [comment]
> Personen, die etwas zu den Änderungen in diesem Release beigesteuert haben, genannt

Dagegen habe ich nichts.
