### ISSUE TITLE
Integrate "Vergleich mit anderen Editionen"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#553]
part of #505

**Comment by gerritbruening** [comment]
I think I have provided all the links I could. Still, the apparatus-like content does not yet look apparatus-like (no grey etc.). @thvitt, can you give me any guidance how to style this stuff?

**Comment by thvitt** [comment]
probably also requires css modifications on my side …

**Comment by gerritbruening** [comment]
Danke!
![grafik](https://user-images.githubusercontent.com/10358005/49658117-9128f980-fa41-11e8-8add-b673f06bad2b.png)

Gut wäre jetzt noch 
- Klammer grau
- `em` / `span ... italics` wie `note`-Text im Apparat (grau; kleiner? Die Versnummern sind kleiner; oder die Versnummern hier nicht kleiner?)

**Comment by thvitt** [comment]
Ein paar automatisierbare Punkte habe ich nachgetragen, bitte korrigieren und ggf. manuell ergänzen

* Apparateintrag grundsätzlich: `<· class="type-textcrit">…</·>` (z.B. `<p>`)
* Lemmaklammern etc.: `<span class="generated-text">]</span>`
* grau/kursiv, d.h. `<note>` im Apparat: `<span class="note">`

**Comment by gerritbruening** [comment]
Sehr gut, vielen Dank!
Ich habe jetzt alle Änderungen vorgenommen, die ich konnte. Was ich noch schön fände, wären zwei oder drei geschützte Leerzeichen vor den Lesarten, so wie das [andernorts](http://dev.faustedition.net/print/app) auch ist. Dort sehe ich mit `strg `+`u` jedoch mehrere spaces innerhalb und außerhalb unterschiedlicher `span`s. Deswegen weiß ich nicht, ob ich das so übertragen kann oder soll.

**Comment by thvitt** [comment]
andernorts entsteht der whitespace, indem die Lesarten jeweils mit `<span class="rdg">` umschlossen sind. Eine CSS-Regel fuͤgt dann ein ` ` (= U+2003 EM SPACE) vor jedem solchen rdg ein. Das koͤnnte man jetzt hier angleichen, oder eben manuell einen EM SPACE einfügen.

**Comment by gerritbruening** [comment]
OK, dank, ich habe die em spaces eingefügt, jetzt sollte es passen.
