### ISSUE TITLE
Provide page number for Mainpost report

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#556]
from #342.
@thvitt  or @fotisj, can you add a page number here:
https://github.com/faustedition/faust-web/blob/cd5ba4a71334426fd71b44a9507d609fb774f3bc/content/intro.html#L349

**Comment by thvitt** [comment]
[Einen Link](https://www.mainpost.de/ueberregional/kulturwelt/dpakultur/Der-ganze-Faust-komplett-im-Netz;art584,10109550) hätte ich, gedrucktes Exemplar nicht zur Hand, müsste man vmtl. mal in der Bibliothek suchen

**Comment by gerritbruening** [comment]
Habe noch die online-Version verlinkt.
