### ISSUE TITLE
url for v1.1rc

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#557]
http://v1-1.faustedition.net/ ?

**Comment by gerritbruening** [comment]
Warum nicht nur `faustedition.net`? Ich dachte, nur die älteren bekommen den Speziallink.

**Comment by thvitt** [comment]
faustedition.net ist immer die neueste, v1.faustedition.net ist das, was in die Zitierempfehlung steht, damit’s eine stabile Zitierurl hat

**Comment by gerritbruening** [comment]
Ach so, ja, dann natürlich `v1-1`. Oder gibt es eine Alternative?
