### ISSUE TITLE
Missing facsimiles for C3 12

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#560]
See also #442. 

Suggested workflow: CR2 via Gigamove to me, I’ll try to rotate and convert; not for long term archiving but only for web though

**Comment by gerritbruening** [comment]
@dietmarpravida since I have moved away from Frankfurt I have lost direct access to these images. Can you have look and help?

**Comment by dietmarpravida** [comment]
will give it a try, no idea where to look, though

**Comment by dietmarpravida** [comment]
@gerritbruening any idea where i can find them?

**Comment by thvitt** [comment]
jftr when we last looked there were no TIFFs but .CR2 images (see #442)

**Comment by dietmarpravida** [comment]
no idea about cr2

**Comment by dietmarpravida** [comment]
jpeg is all i have, nothing else

**Comment by gerritbruening** [comment]
@dietmarpravida the people of the Bildarchiv should be able to find the images. I  remember that there is a faustedition folder.

**Comment by dietmarpravida** [comment]
still working on it. don't expect results any time soon

**Comment by gerritbruening** [comment]
Any news about this, @dietmarpravida ?

**Comment by dietmarpravida** [comment]
ist das nicht längst erledigt?


Am Dienstag, Juli 13, 2021 11:02 CEST, schrieb Gerrit Brüning ***@***.***>:
 
 
Any news about this, @dietmarpravida ?

**Comment by thvitt** [comment]
Das noch ausstehende Problem ist, dass einige der Verweise auf `-2` enden, während die Dateien das nicht tun (oder umgekehrt). Ich kümmer mich bei gelegenheit drum, irgendwo fliegt noch ein Skript dazu rum

**Comment by thvitt** [comment]
habe die digitalisate jetzt passend zu den transcripten umbenannt, sodass die nun nicht mehr fehlenden digitalisate auch in den veröffentlichten Versionen der Ausgabe erscheinen.
