### ISSUE TITLE
Check link on nachtkritik.de

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#562]
It is invalid, presumably because of the `&` in the link.

**Comment by thvitt** [comment]
`&amp;`

**Comment by gerritbruening** [comment]
Thanks. Have added the `&amp;`, but editor still says 
> The reference to entity "view" must end with the ';' delimiter.

**Comment by gerritbruening** [comment]
Bummer!, I looked out for other & but didn't spot them.
