### ISSUE TITLE
Line numbers disappeared in view=text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#566]
We once had them, IIRC?

**Comment by thvitt** [comment]
* Present in 1.0, missing in 1.1
* They are still in the HTML. it seems that `position: absolute` in the CSS moves them out of sight, but they are there in the print view, so there’s something different in the HTML, I guess

**Comment by thvitt** [comment]
as expected, the problematic commit is this one:

> commit 2b2d53fcf5b6e64c7f48ce44da9b76eb49377eed
> Author: Thorsten Vitt <thorsten.vitt@uni-wuerzburg.de>
> Date:   Sun Dec 16 19:20:16 2018 +0100
>
>    Line numbers should not float.
>    
>    Fixes #351
>    Fixes #498
>    Fixes faustedition/faust-gen-html#635

Need to check, but I guess we’ll have to adjust the text view html to be somewhat like the print view html: removing `position: absolute` from the css moves the linenumbers immediately to the front of the lines, adding it seems to move them off screen

**Comment by gerritbruening** [comment]
Hm, still don't see them?

**Comment by thvitt** [comment]
Where? here: http://dev.faustedition.net/document?sigil=2_H&page=342&view=text they are:
![correct line numbers](https://user-images.githubusercontent.com/1906208/56569373-2116ac80-65b9-11e9-93ba-1e381f1443e0.png)

**Comment by thvitt** [comment]
(Maybe invalidate cache – Ctrl+F5)

**Comment by gerritbruening** [comment]
So sorry; always look at the adress bar first!
