### ISSUE TITLE
Some app verse lines aren't indented, but should be

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#567]
For examples, look at
http://faustedition.net/print/app#type_2b
or
http://faustedition.net/print/app#type_6

Note that the verse line number is usually covered by text.

But some are properly indented, for example in [3*](http://faustedition.net/print/app#type_3*).

**Comment by gerritbruening** [comment]
Can't manage to see the effect, though I pressed `ctrl`+`f5`.

**Comment by thvitt** [comment]
look at [dev.faustedition.net](http://dev.faustedition.net/print/app#type_2b), it’s not in the released version

**Comment by gerritbruening** [comment]
So sorry; always look at the adress bar first!
