### ISSUE TITLE
Scrolling in text and print views broken

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#57]
Merging #55 causes the scroll bar in the print / text views to disappear and scrolling to be no longer possible.

Unfortunately just seen that _after_ pushing the merge …

**Comment by thvitt** [comment]
This commit introduces the bug: a6dacc032b27fc99684663894c3d255d7c7af2c8

**Comment by gerritbruening** [comment]
This also applies to the search results.

**Comment by sbruemmer** [comment]
Please wrap the ```<div id="main" class="print"></div>``` with another layer that it becomes:
```html
<div style="display: block;" class="print-content view-content" id="print-content">
   <div id="main" class="print">

   </div>
</div>
```
Regarding the search results i'd like to prefer own id and classes. Leave class ```print``` on the subordinated element.

```html
<div style="display: block;" class="search-content view-content" id="search-content">
   <div id="main" class="print">

   </div>
</div>
```
