### ISSUE TITLE
Some arbitrary tooltip appears wherever I hover

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#573]
![grafik](https://user-images.githubusercontent.com/10358005/62623430-17734380-b921-11e9-82b7-272a62ba880f.png)

![grafik](https://user-images.githubusercontent.com/10358005/62623554-6ae59180-b921-11e9-8243-683ae8bf9ec8.png)

**Comment by gerritbruening** [comment]
Tritt auch in 1.2 auf.

**Comment by thvitt** [comment]
Kann ich nicht reproduzieren. Welche Schritte genau führen zu dem Verhalten?

**Comment by gerritbruening** [comment]
War bei uns (SH und ich) erst auch so, aber jetzt wissen wir, wann es entsteht:

1. Konvolutansicht
2. auf Thumbnail image klicken, auf der viel steht, denn:
3. wenn schon durch die Position des Mauszeigers ein Tooltip erscheint, weil man zufällig auf einem Kasten landet, dann bleibt genau dieser Tooltip

Wenn man zufällig an einer Stelle ohne Tooltip landet, oder wenn man per Schaltfläche zum Faksimile wechselt, tritt das Phänomen tatsächlich nicht auf.

**Comment by thvitt** [comment]
Ah, es scheint folgendes vorzugehen:
1. Thumbnailklick blättert auf Facsimileansicht mit _alter_ Seite, an der an Mauszeigerstelle Text¹ ist
2. Tooltip¹ wird dort angezeigt
3. neue Seite fertiggeladen → Text¹ ist ausgeblendet, Tooltip¹ noch sichtbar
4. Maus über Text² bewegen → Tooltip² erscheint, Tooltip¹ verschwindet
5. Maus aus Text² rausbewegen → Tooltip² verschwindet, Tooltip¹ erscheint wieder

muss man mal in den Tooltipcode gucken …
Nun wird auch nachdem ein vorherig
