### ISSUE TITLE
Small errors in "Legende" in doc transcript pdf

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#579]
1. There is no blue ink in our corpus, is there?
2. The red colour for ruddle should be different from the one which appears for red ink, shouldn’t it?
3. “grau” appears to me black, doesn’t it?

**Comment by thvitt** [comment]
>     1. There is no blue ink in our corpus, is there?

I mixed that up with 'Blauer Bleistift'

>     2. The red colour for ruddle should be different from the one which appears for red ink, shouldn’t it?

They are both assigned the same color 
https://github.com/faustedition/faust-web/blob/02e65ebb6c7c5a0329c08f14ac90a23bc46e10ef/css/document-transcript.css#L86-L94

>     3. “grau” appears to me black, doesn’t it?

need to look into this, it should use the same color code as in the actual transcript

**Comment by thvitt** [comment]
Btw. there is no special styling for _Kohlestift_, it’s the same black as black ink

**Comment by gerritbruening** [comment]
Same colour for all the black writing media is OK, I think.
Thanks for fixing this!
