### ISSUE TITLE
http://beta.faustedition.net/archive.php not found

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#58]

**Comment by thvitt** [comment]
yes, it's called archives.php now according to that other bug. Is there still a broken link somewhere?

**Comment by gerritbruening** [comment]
Now I am confused about the desired name: 
> it's called archives.php now

unlike https://github.com/faustedition/faust-gen-html/commit/7c87745f11950b71e3fb7aa668c68d501398ae7c?

**Comment by thvitt** [comment]
Ah, automatically updating the beta instance hasn't worked. Now its up to date again.
