### ISSUE TITLE
C.3 12 doesn't show

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#580]
For http://faustedition.net/document?sigil=C.3_12&page=191&view=facsimile, for example, I get the following error message:

Fehler beim Laden der Facsimile-Metadaten Error: Failed to load transcript/facsimile/metadata/print/C(3)12_IIIB27/C(3)12_IIIB27_0183.json, error: Not Found

**Comment by thvitt** [comment]
Since I don’t have the facsimiles …  Duplicate of #560
