### ISSUE TITLE
Text view: page beginning at top of screen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#587]
When I visit
http://dev.faustedition.net/document?sigil=C.1_4&page=34&view=facsimile_text
or other pages in the `facsimile_text` view the beginning of page 245 appears in the middle of the screen. I would expect it to appear right below the page header.
Is this intended, has this always been like this?

**Comment by gerritbruening** [comment]
http://v1-0.faustedition.net/document?sigil=C.1_4&page=34&view=facsimile_text
is different, page beginning is where I had expected it, i.e., at the top.

**Comment by thvitt** [comment]
'center' scrolling for fragments has been introduced by https://github.com/faustedition/faust-web/commit/24e30f4749a9088c4668378e4fa8bf7ac8115f4e , fixing multiple issues in 1.0, but we can adjust that for scrolling to a page.

Would you prefer the page mark topmost on the page:

![image](https://user-images.githubusercontent.com/1906208/126767606-075cce8f-d097-4e7e-812d-163edb20537d.png)

or rather offset by, e.g., 24px so you can see the previous line:

![image](https://user-images.githubusercontent.com/1906208/126767392-61783878-9e33-49a6-a56e-0af247e9dbcf.png)

**Comment by gerritbruening** [comment]
Thanks for these visualizations, I would prefer the page mark topmost on the page.
