### ISSUE TITLE
Button icons not showing on Firefox

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#59]
![buttonicons](https://cloud.githubusercontent.com/assets/10358005/12372787/58b4477c-bc63-11e5-9888-3ec3cb68b781.PNG)

**Comment by thvitt** [comment]
Press Ctrl+F5 or Ctrl+Shift+R to reload the page without using your browser's cache and the problem should be gone.

**Comment by gerritbruening** [comment]
Sorry, I forgot!
