### ISSUE TITLE
Improve behaviour for stopwords-only search (e.g., »habe nun«) 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#595]
https://dev.faustedition.net/search?q=habe+nun

applies to dev and non-dev, FF and Chrome

**Comment by thvitt** [comment]
Search is fine, but both 'habe' and 'nun' are stop words.

Try ["habe nun" in the _alle Wortformen_ index](https://dev.faustedition.net/search?q=%22habe+nun%22&index=text)

**Comment by gerritbruening** [comment]
> Search is fine, but both 'habe' and 'nun' are stop words.

This is surprising

**Comment by thvitt** [comment]
Need to look which list is really used, but [this is a quite common one](https://github.com/stopwords-iso/stopwords-de).

Maybe generate a message when we're using stopwords and the query consists of stopwords only

**Comment by thvitt** [comment]
also cf. https://github.com/faustedition/faust-gen-html/issues/623

**Comment by thvitt** [comment]
Duplicate of https://github.com/faustedition/faust-gen-html/issues/623 actually
