### ISSUE TITLE
Header line in tables partially hidden in Firefox

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#60]
![headerlinehidden](https://cloud.githubusercontent.com/assets/10358005/12372802/bdd5022c-bc63-11e5-91ed-cb74900dbaab.PNG)

**Comment by thvitt** [comment]
Doesn't occur on my computer. Looks like the page header has more height due to the _beta_ mark being positioned below the wordmark, cf. #62

**Comment by gerritbruening** [comment]
After strg-shift-r the web page behaves properly on my device.
