### ISSUE TITLE
Distorted appearance of TIL in Chrome

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#601]
https://dev.faustedition.net/document?sigil=1_H.5&page=1&view=facsimile (Chrome)

![grafik](https://user-images.githubusercontent.com/10358005/213407280-54aea396-1795-4b6f-ad20-aad089312aee.png)

**Comment by thvitt** [comment]
switching _views_ causes correct scaling

**Comment by thvitt** [comment]
problem also occurs on 1.0, so its not a regression (but probably new behaviour by the browser version?)

**Comment by thvitt** [comment]
Console has this error in Chrome:

TypeError: Cannot read properties of null (reading 'removeAttribute')  (faust_viewer.js:490)
    at updateControlsToPage (faust_viewer.js:483:27)
    at setPage (faust_viewer.js:566:13)
    at init (faust_viewer.js:379:13)
    at faust_viewer.js:651:9
    at createDocumentViewer (faust_viewer.js:667:7)

**Comment by thvitt** [comment]
[Bisecting](https://www.chromium.org/developers/bisect-builds-py/) chromium showed the problem starts to appear in one of these revisions:

You are probably looking for a change made after 1011831 (known good), but no later than 1011858 (first known bad).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/9e5fa0b4a3a7e1e40be1253d6337b55960556a34..e9ff38845fc8abd0225197633bfcf3b4f5ed9803

**Comment by thvitt** [comment]
The problem has been fixed in Chrome version 112.
