### ISSUE TITLE
Suche: Sortierung nach "Relevanz"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#604]
Was war nochmal "Relevanz"?
Siehe auch #186

**Comment by thvitt** [comment]
Der Relevanzscore kommt aus der Suchmaschine und wird anhand der Höufigkeit und Spezifität der Suchbegriffe berechnet sowie anhand speziell konfigurierter Boost-Werte (Überschriften sind gut, Sprecher sind schlecht). 

Die Aussagekraft wird vermutlich dadurch eingeschränkt, dass die Ebene der Suche (die "Dokumente" im Information-Retrieval-Sinne) z.Z. die Verse sind.

**Comment by gerritbruening** [comment]
Danke, Frage ist aus meiner Sicht damit beantwortet.
