### ISSUE TITLE
Links from `document` to `text` broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#606]
When I am at
https://faustedition.net/document?sigil=2_V_H.2&page=13&view=print&section=2#l11580
and want to return to the "Text", I am pointed to 
`https://faustedition.net/faust.43#l11580`
which doesn't exist (404). The correct link would be
`https://faustedition.net/print/faust.43#l11580`.

**Comment by thvitt** [comment]
Hotfixed via a manual redirect in the .htaccess, but it is still a bug.

**Comment by thvitt** [comment]
`$printbase` from config:
https://github.com/faustedition/faust-gen-html/blob/13a431768c63b1c0aeac6281715813e9ff7938c3/xslt/variant-fragments.xsl#L178
