### ISSUE TITLE
Wordmark underlined in Chrome---intended?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#62]
![wordmarkunderline](https://cloud.githubusercontent.com/assets/10358005/12372840/e618394c-bc64-11e5-891b-deac3cd3d5c5.PNG)

The wordmark is a link, but the underline disturbs its appearance.

**Comment by thvitt** [comment]
Neither that problem nor the strange position of the _beta_ label occur on my system. Can you reproduce this after clearing your browser cache & reloading?

![screenshot_050](https://cloud.githubusercontent.com/assets/1906208/12374448/30787a1a-bc9c-11e5-8b36-86a11cc732de.png)

**Comment by gerritbruening** [comment]
Gone on my device, too! Everything looks normal now.
