### ISSUE TITLE
Why print/text.html instead of text.html?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#66]
* http://beta.faustedition.net/print/text.html

and then

* http://beta.faustedition.net/text/faust2.html and so on

seems preferable to me.

**Comment by thvitt** [comment]
I currently don't want to have the emended versions of text, prints, and manuscripts in different directories. What can easily be done is replacing `/print/text.html` with `/text` (but keep `/print/faust1.html` etc.). Renaming the whole `print/` folder to `text/` could be done with a little more effort (ie renaming references everywhere). Separating text from prints will not happen any time soon

**Comment by gerritbruening** [comment]
OK, I see.
I just wondered why they are called "print" because there is no natural connection between the *Lesetext* and the printed editions.
