### ISSUE TITLE
Breadcrumb in print/faust1.html

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#72]
Before entering one of scenes, the breadcrumb of the first scene appears: "Zueignung". Would be better to have something like "Übersicht", "Inhalt" etc.

**Comment by sbruemmer** [comment]
Regarding the other pages "Archive" and "Genesis" i would suggest:

 * "**Text**" in [/print/text.html](http://beta.faustedition.net/print/text.html)
 * "Text | **Faust 1**" in [/print/faust1.html](http://beta.faustedition.net/print/faust1.html)
 * "Text > Faust 1 | **Zuneigung**" in [/print/faust1.1.html](http://beta.faustedition.net/print/faust1.1.html)
 * ...

The current (last) element, which should be displayed in a bigger font-size, is shown as bold in my list.

**Comment by gerritbruening** [comment]
I like this idea!
The numbers would have to be roman numerals, Faust I instead of Faust 1.
