### ISSUE TITLE
TOC: put //titlePage/docTitle into a "Titel" 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#73]
So that the line synopsis does not appear in the TOC directly, but on a lower level.

**Comment by thvitt** [comment]
I assume this isn't something _I_ should do, since I don't understand it … 

Anyway, TOC reorg post beta probably

**Comment by gerritbruening** [comment]
Yes, post beta!
Let's talk about f2f.

**Comment by thvitt** [comment]
Fixed with the new splitting, faustedition/faust-gen-html#58

**Comment by gerritbruening** [comment]
I don't see the "Titel" when I choose "nach Szenen zerlegt".
