### ISSUE TITLE
Genesis details: Green bar covers blue bar

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#79]
e.g., IV H.20

**Comment by thvitt** [comment]
Maybe we could make the green bars just a little bit (here: 10%) transparent, so you see there is something beneath?

![Slightly transparent green bar](https://cloud.githubusercontent.com/assets/1906208/12747599/46274bb4-c9a5-11e5-9a3c-289b36d9845b.png)

**Comment by gerritbruening** [comment]
In a recent discussion with Anne Bohnenkamp we both had the impression that it would be good to make the blue bar the most visible information. It would even be reasonable to make the blue cover the green bar.

**Comment by thvitt** [comment]
Crosshatched is also the solution that probably requires most effort.

To pick some low-hanging fruit, I have experimentally changed the stacking order of the different types of bars in a7be28b (last entries are on top) and deployed the result on beta. This puts blue bars on top of green ones, but please review the other cases carefully.

**Comment by gerritbruening** [comment]
> Crosshatched is also the solution that probably requires most effort.

:-)

> changed the stacking order

Fine with that!
