### ISSUE TITLE
Improve usability for large documents with few facsimiles

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#8]
e.g., http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/archival/gsa/GSA_24-15-1.xml&page=1&view=structure

Many pages without sensible content

(Nice to have)

**Comment by gerritbruening** [comment]
See, for example, 1 H.6 (Göchhausen's collection of poems).

**Comment by gerritbruening** [comment]
Great!!
