### ISSUE TITLE
genesis: "Faust II" doesn't look like centered

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#81]
Reason: box below the heading.

**Comment by sbruemmer** [comment]
The headline is centered. I have adjusted the graphic to get a more centered impression on the page. Please close this ticket if it is ok.

**Comment by sbruemmer** [comment]
Centering the headline optically to the graphic is quite hard. The graphic doesn't have visually defined dimensions. Adding a background shows the dimensions on which the alignment can be done.

![gensis](https://cloud.githubusercontent.com/assets/13978063/12881340/7a5d08d0-ce49-11e5-8368-095e806563a3.jpg)


Beside that the graphic needs a bit more work on the design.

**Comment by gerritbruening** [comment]
Part of #130
