### ISSUE TITLE
remove class="pure-tiles"

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#83]
please remove class `pure-tiles` in [/faustedition/faust-gen-html/xslt/index.xsl](https://github.com/faustedition/faust-gen-html/blob/master/xslt/index.xsl)

see https://github.com/sbruemmer/faust-web/commit/c8108ccfc9a48e6c556c95afcc1554d274003c

**Comment by thvitt** [comment]
still sth wrong here
