### ISSUE TITLE
Sort bibliography

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#86]
Problem: volume numbers such as
WA I 1
WA I 10
WA I 13
WA I 15,1
WA I 15,2
WA I 2

Also applies to the GJB volumes.

**Comment by thvitt** [comment]
Need a detailed sort spec that works _for all_ citations. 
I suggest we do this post-beta.

Btw. bibliography & metadata pages are created in faustedition/faust-gen-html

**Comment by gerritbruening** [comment]
Yes, lets do this post-beta.
Do you want me to move the issue to faust-gen-html then?

**Comment by gerritbruening** [comment]
See https://github.com/faustedition/faust-gen-html/issues/44
