### ISSUE TITLE
please proof deletion of unused fonts

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#9]
Within the fork i have searched for unused font packages. Therefore some has been removed in https://github.com/sbruemmer/faust-web/commit/b9d0b7b7f8a72bc69a2699f65c417156dec3ad7c and  https://github.com/sbruemmer/faust-web/commit/8fae28fe926c05bf5d9c3f74c2d8d0f5d30ed79e. 

Please double check if they aren't in use before merging the next pull request.

**Comment by thvitt** [comment]
Haven't seen them anywhere, also not in the generated files, so deletion should be fine.
