### ISSUE TITLE
Not possible to browse through 2 II H.15

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#98]
http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.2/gsa_391408.xml&page=1&view=facsimile

**Comment by thvitt** [comment]
TypeError: currentMetadata.docTranscripts[0].images[0] is undefined
createDocumentViewer/loadPage</<() faust_viewer.js:675
createDocumentViewer/setPage</<() faust_viewer.js:1132
createDocumentViewer/nextPage</<() faust_viewer.js:1147
onclick() documentViewer:1
1 faust_viewer.js:675:17

**Comment by thvitt** [comment]
Here's the metadata extract for this document:
```json
{
         "page" : [
            {
               "doc" : [
                  {
                     "imgLink" : "97977d33-1b44-4971-9a99-aabf3c5ea97f.svg",
                     "uri" : "0002.xml",
                     "img" : [
                        "gsa/391408/391408_0002",
                        "gsa/391408/391408_0003"
                     ]
                  }
               ]
            },
            {
               "doc" : [
                  {
                     "img" : [],
                     "uri" : "0004.xml"
                  }
               ]
            }
         ],
         "sigils" : {
            "repository" : "gsa",
            "idno_gsa_1" : "GSA 25/XVII,7,16",
            "idno_wa_faust" : "2 II H.15",
            "headNote" : "Einzelblatt. – Zu ‚Faust II‘, Akt 2.",
            "idno_hecker" : "156",
            "idno_gsa_2" : "GSA 25/W 1504",
            "idno_faustedition" : "2 II H.15"
         },
         "text" : "391408.xml",
         "base" : "gsa/391408/",
         "document" : "faust/2.2/gsa_391408.xml"
      }
```
img is strange?

**Comment by thvitt** [comment]
There's two facsimiles in this witnesses first page's transcript, 0002.xml, and none in the second page's transcript, 0004.xml. So either this is wrong or its a use case we don't support yet.

**Comment by gerritbruening** [comment]
OK, I think the transcription has been overwritten. Will restore the previous version.
BTW where could I get backup files when I need them?

**Comment by thvitt** [comment]
From me. Just provide me with details on the file(s) you need and I'll ask the internal repo

**Comment by gerritbruening** [comment]
Repared.
